# Generated by Django 5.2.4 on 2025-08-20 21:21

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contrats', '0003_contrat_avance_loyer_contrat_avance_loyer_payee_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contrat',
            name='avance_loyer',
            field=models.CharField(default='0.00', max_length=20, verbose_name='Avance de loyer'),
        ),
        migrations.AlterField(
            model_name='contrat',
            name='charges_mensuelles',
            field=models.CharField(default='0.00', max_length=20, verbose_name='Charges mensuelles'),
        ),
        migrations.AlterField(
            model_name='contrat',
            name='date_fin',
            field=models.DateField(blank=True, null=True, verbose_name='Date de fin'),
        ),
        migrations.AlterField(
            model_name='contrat',
            name='depot_garantie',
            field=models.CharField(default='0.00', max_length=20, verbose_name='Dépôt de garantie'),
        ),
        migrations.AlterField(
            model_name='contrat',
            name='jour_paiement',
            field=models.PositiveIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(31)], verbose_name='Jour de paiement'),
        ),
        migrations.AlterField(
            model_name='contrat',
            name='loyer_mensuel',
            field=models.CharField(max_length=20, verbose_name='Loyer mensuel'),
        ),
    ]
