# Generated by Django 5.2.5 on 2025-08-25 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contrats', '0004_alter_contrat_avance_loyer_and_more'),
        ('proprietes', '0016_chargesbailleur_montant_deja_deduit_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='contrat',
            name='pieces',
            field=models.ManyToManyField(help_text='Pièces spécifiques louées dans ce contrat', related_name='contrats', through='proprietes.PieceContrat', to='proprietes.piece', verbose_name='Pièces louées'),
        ),
        migrations.AlterField(
            model_name='contrat',
            name='charges_mensuelles',
            field=models.CharField(blank=True, default='0.00', max_length=20, null=True, verbose_name='Charges mensuelles'),
        ),
        migrations.AlterField(
            model_name='contrat',
            name='depot_garantie',
            field=models.CharField(blank=True, default='0.00', max_length=20, null=True, verbose_name='Dépôt de garantie'),
        ),
        migrations.AlterField(
            model_name='contrat',
            name='loyer_mensuel',
            field=models.CharField(blank=True, help_text='Sera automatiquement rempli à partir de la propriété sélectionnée', max_length=20, verbose_name='Loyer mensuel'),
        ),
    ]
