# Generated by Django 5.2.5 on 2025-09-03 13:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contrats', '0006_alter_contrat_depot_garantie_and_more'),
        ('proprietes', '0018_add_unites_locatives_system'),
    ]

    operations = [
        migrations.AddField(
            model_name='contrat',
            name='unite_locative',
            field=models.ForeignKey(blank=True, help_text='Unité locative louée (pour les grandes propriétés)', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='contrats', to='proprietes.unitelocative', verbose_name='Unité locative'),
        ),
        migrations.AlterField(
            model_name='contrat',
            name='pieces',
            field=models.ManyToManyField(blank=True, help_text='Pièces spécifiques louées dans ce contrat', related_name='contrats', through='proprietes.PieceContrat', to='proprietes.piece', verbose_name='Pièces louées'),
        ),
    ]
