# Generated by Django 5.2.6 on 2025-09-05 00:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contrats', '0007_add_unite_locative_support'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contrat',
            name='avance_loyer',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Avance de loyer'),
        ),
        migrations.AlterField(
            model_name='contrat',
            name='charges_mensuelles',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Charges mensuelles'),
        ),
        migrations.AlterField(
            model_name='contrat',
            name='depot_garantie',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Dépôt de garantie ou Caution'),
        ),
        migrations.AlterField(
            model_name='contrat',
            name='loyer_mensuel',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Sera automatiquement rempli à partir de la propriété ou unité locative sélectionnée', max_digits=10, verbose_name='Loyer mensuel'),
        ),
    ]
