# Generated by Django 4.2.24 on 2025-09-17 13:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('utilisateurs', '0008_fix_test_users'),
        ('contrats', '0008_alter_contrat_avance_loyer_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contrat',
            name='avance_loyer',
            field=models.CharField(default='0', max_length=20, verbose_name='Avance de loyer'),
        ),
        migrations.AlterField(
            model_name='contrat',
            name='charges_mensuelles',
            field=models.CharField(default='0', max_length=20, verbose_name='Charges mensuelles'),
        ),
        migrations.AlterField(
            model_name='contrat',
            name='depot_garantie',
            field=models.CharField(default='0', max_length=20, verbose_name='Dépôt de garantie ou Caution'),
        ),
        migrations.AlterField(
            model_name='contrat',
            name='loyer_mensuel',
            field=models.CharField(default='0', help_text='Sera automatiquement rempli à partir de la propriété ou unité locative sélectionnée', max_length=20, verbose_name='Loyer mensuel'),
        ),
        migrations.AlterField(
            model_name='documentcontrat',
            name='imprime_par',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='documents_contrat_imprimes', to='utilisateurs.utilisateur', verbose_name='Imprimé par'),
        ),
        migrations.AlterField(
            model_name='quittance',
            name='montant_charges',
            field=models.CharField(default='0', max_length=20, verbose_name='Montant charges'),
        ),
        migrations.AlterField(
            model_name='quittance',
            name='montant_loyer',
            field=models.CharField(max_length=20, verbose_name='Montant loyer'),
        ),
        migrations.AlterField(
            model_name='quittance',
            name='montant_total',
            field=models.CharField(max_length=20, verbose_name='Montant total'),
        ),
        migrations.AlterField(
            model_name='resiliationcontrat',
            name='cree_par',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='resiliations_crees', to='utilisateurs.utilisateur', verbose_name='Créé par'),
        ),
        migrations.AlterField(
            model_name='resiliationcontrat',
            name='montant_remboursement',
            field=models.CharField(default='0', max_length=20, verbose_name='Montant du remboursement'),
        ),
        migrations.AlterField(
            model_name='resiliationcontrat',
            name='validee_par',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='resiliations_validees', to='utilisateurs.utilisateur', verbose_name='Validée par'),
        ),
    ]
