# Generated by Django 4.2.7 on 2025-07-20 09:28

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('utilisateurs', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='GroupeTravail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(choices=[('CAISSE', 'CAISSE'), ('CONTROLES', 'CONTROLES'), ('ADMINISTRATION', 'ADMINISTRATION'), ('PRIVILEGE', 'PRIVILEGE')], max_length=20, unique=True)),
                ('description', models.TextField(blank=True)),
                ('permissions', models.JSONField(default=dict, help_text='Permissions spécifiques au groupe')),
                ('actif', models.BooleanField(default=True)),
                ('date_creation', models.DateTimeField(default=django.utils.timezone.now)),
                ('date_modification', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Groupe de travail',
                'verbose_name_plural': 'Groupes de travail',
                'ordering': ['nom'],
            },
        ),
        migrations.RemoveField(
            model_name='utilisateur',
            name='est_actif',
        ),
        migrations.RemoveField(
            model_name='utilisateur',
            name='groupe',
        ),
        migrations.AddField(
            model_name='utilisateur',
            name='actif',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='utilisateur',
            name='date_creation',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='utilisateur',
            name='date_modification',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='utilisateur',
            name='date_naissance',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='utilisateur',
            name='departement',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='utilisateur',
            name='derniere_connexion',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='utilisateur',
            name='poste',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='utilisateur',
            name='adresse',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='utilisateur',
            name='date_embauche',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='utilisateur',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='photos_utilisateurs/'),
        ),
        migrations.AlterField(
            model_name='utilisateur',
            name='telephone',
            field=models.CharField(blank=True, max_length=17, validators=[django.core.validators.RegexValidator(message="Le numéro de téléphone doit être au format : '+999999999'. Jusqu'à 15 chiffres autorisés.", regex='^\\+?1?\\d{9,15}$')]),
        ),
        migrations.AddField(
            model_name='utilisateur',
            name='groupe_travail',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='utilisateurs', to='utilisateurs.groupetravail'),
        ),
    ]
