# Generated by Django 4.2.7 on 2025-07-21 15:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('utilisateurs', '0002_groupetravail_remove_utilisateur_est_actif_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='utilisateur',
            name='deleted_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Date de suppression'),
        ),
        migrations.AddField(
            model_name='utilisateur',
            name='deleted_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='utilisateur_deleted', to=settings.AUTH_USER_MODEL, verbose_name='Supprimé par'),
        ),
        migrations.AddField(
            model_name='utilisateur',
            name='is_deleted',
            field=models.BooleanField(default=False, verbose_name='Supprimé logiquement'),
        ),
    ]
