# Generated by Django 5.2.4 on 2025-08-10 18:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('utilisateurs', '0003_utilisateur_deleted_at_utilisateur_deleted_by_and_more'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='utilisateur',
            managers=[
            ],
        ),
    ]
