# Generated by Django 4.2.24 on 2025-10-17 20:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('utilisateurs', '0010_auto_20251005_2002'),
    ]

    operations = [
        migrations.AlterField(
            model_name='groupetravail',
            name='date_creation',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='utilisateur',
            name='date_creation',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
