"""
Commande Django pour créer la table DepenseResiliation si elle n'existe pas
"""
from django.core.management.base import BaseCommand
from django.db import connection


class Command(BaseCommand):
    help = 'Crée la table contrats_depenseresiliation si elle n existe pas'

    def handle(self, *args, **options):
        try:
            with connection.cursor() as cursor:
                # Vérifier si la table existe
                cursor.execute("""
                    SELECT EXISTS (
                        SELECT FROM information_schema.tables 
                        WHERE table_schema = 'public' 
                        AND table_name = 'contrats_depenseresiliation'
                    );
                """)
                exists = cursor.fetchone()[0]
                
                if exists:
                    self.stdout.write(
                        self.style.SUCCESS('La table contrats_depenseresiliation existe deja.')
                    )
                    return
                
                self.stdout.write('La table n existe pas. Creation en cours...')
                
                # Créer la table
                cursor.execute("""
                    CREATE TABLE "contrats_depenseresiliation" (
                        "id" bigint NOT NULL PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
                        "description" varchar(200) NOT NULL,
                        "montant" numeric(12, 2) NOT NULL,
                        "ordre" integer NOT NULL CHECK ("ordre" >= 0),
                        "date_creation" timestamp with time zone NOT NULL,
                        "resiliation_id" bigint NOT NULL
                    );
                """)
                
                # Créer l'index
                cursor.execute("""
                    CREATE INDEX "contrats_depenseresiliation_resiliation_id_0d98ff4c" 
                    ON "contrats_depenseresiliation" ("resiliation_id");
                """)
                
                # Créer la clé étrangère
                cursor.execute("""
                    ALTER TABLE "contrats_depenseresiliation" 
                    ADD CONSTRAINT "contrats_depenseresi_resiliation_id_0d98ff4c_fk_contrats_" 
                    FOREIGN KEY ("resiliation_id") 
                    REFERENCES "contrats_resiliationcontrat" ("id") 
                    DEFERRABLE INITIALLY DEFERRED;
                """)
                
                self.stdout.write(
                    self.style.SUCCESS('Table contrats_depenseresiliation creee avec succes!')
                )
                
        except Exception as e:
            self.stdout.write(
                self.style.ERROR(f'ERREUR lors de la creation de la table: {e}')
            )
            import traceback
            traceback.print_exc()

