services:
  - type: web
    name: appli-kbis
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: ./start_render.sh
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0
      - key: DJANGO_SETTINGS_MODULE
        value: gestion_immobiliere.settings
