services:
  - type: web
    name: appli-kbis-postgresql
    env: python
    buildCommand: "pip install -r requirements.txt && python manage.py collectstatic --noinput"
    startCommand: "python migrate_smart.py && gunicorn gestion_immobiliere.wsgi:application --bind 0.0.0.0:$PORT"
    envVars:
      - key: DATABASE_URL
        value: postgresql://kbis_user:qN64K1DDSffwfTPThqEPgtsH5sVwwKGP@dpg-d3og40k9c44c73cvh1h0-a.oregon-postgres.render.com/kbis_immobilier
      - key: SECRET_KEY
        value: django-insecure-render-key-change-me-in-production
      - key: DEBUG
        value: False
      - key: RENDER
        value: True
      - key: DJANGO_SETTINGS_MODULE
        value: gestion_immobiliere.settings_postgresql
