# Configuration Render pour KBIS INTERNATIONAL
services:
  - type: web
    name: appli-kbis
    env: python
    region: oregon  # ou frankfurt pour l'Europe
    plan: starter  # ou standard/pro selon vos besoins
    buildCommand: |
      pip install -r requirements.txt
      python manage.py collectstatic --noinput
      python manage.py migrate
    startCommand: gunicorn gestion_immobiliere.wsgi:application
    envVars:
      - key: DEBUG
        value: False
      - key: SECRET_KEY
        generateValue: true
      - key: DATABASE_URL
        fromDatabase:
          name: kbis-postgres
          property: connectionString
      - key: ALLOWED_HOSTS
        value: appli-kbis.onrender.com
      - key: STATIC_URL
        value: /static/
      - key: MEDIA_URL
        value: /media/
    healthCheckPath: /admin/

databases:
  - name: kbis-postgres
    plan: starter  # Changer pour standard/pro selon vos besoins
    databaseName: kbis_production
    user: kbis_user
    region: oregon  # ou frankfurt pour l'Europe