services:
  - type: web
    name: appli-kbis
    env: python
    buildCommand: "./render-build.sh"
    startCommand: "gunicorn gestion_immobiliere.wsgi:application"
    plan: free
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0
      - key: SECRET_KEY
        generateValue: true
      - key: DEBUG
        value: False
      - key: ALLOWED_HOSTS
        value: "appli-kbis.onrender.com,.onrender.com"
      - key: DATABASE_URL
        fromDatabase:
          name: appli-kbis-db
          property: connectionString
    healthCheckPath: "/"