services:
  - type: web
    name: appli-kbis
    env: python
    plan: starter
    buildCommand: |
      pip install --upgrade pip
      pip install -r requirements.txt
      python manage.py collectstatic --noinput --settings=gestion_immobiliere.performance_settings
      python manage.py migrate --settings=gestion_immobiliere.performance_settings
    startCommand: |
      gunicorn gestion_immobiliere.wsgi:application --bind 0.0.0.0:$PORT --workers 2 --threads 4 --timeout 120 --max-requests 1000 --max-requests-jitter 100 --preload
    envVars:
      - key: DJANGO_SETTINGS_MODULE
        value: gestion_immobiliere.performance_settings
      - key: PYTHONUNBUFFERED
        value: 1
      - key: DISABLE_COLLECTSTATIC
        value: 1
    healthCheckPath: /utilisateurs/connexion-groupes/
    autoDeploy: true