# Generated by Django 4.2.7 on 2025-07-20 14:55

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ConfigurationEntreprise',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_entreprise', models.CharField(help_text='Nom officiel de votre entreprise', max_length=200, verbose_name="Nom de l'entreprise")),
                ('nom_commercial', models.CharField(blank=True, help_text='Nom commercial si différent du nom officiel', max_length=200, verbose_name='Nom commercial')),
                ('logo', models.ImageField(blank=True, help_text='Logo de votre entreprise (format PNG, JPG, SVG recommandé)', null=True, upload_to='logos/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['png', 'jpg', 'jpeg', 'svg', 'gif'])], verbose_name="Logo de l'entreprise")),
                ('adresse', models.TextField(help_text="Adresse complète de l'entreprise", verbose_name='Adresse complète')),
                ('telephone', models.CharField(blank=True, max_length=20, verbose_name='Téléphone')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='Email de contact')),
                ('site_web', models.URLField(blank=True, verbose_name='Site web')),
                ('siret', models.CharField(blank=True, max_length=14, verbose_name='Numéro SIRET')),
                ('tva_intra', models.CharField(blank=True, max_length=20, verbose_name='Numéro de TVA intracommunautaire')),
                ('rcs', models.CharField(blank=True, max_length=50, verbose_name='RCS')),
                ('banque', models.CharField(blank=True, max_length=100, verbose_name='Banque')),
                ('iban', models.CharField(blank=True, max_length=34, verbose_name='IBAN')),
                ('bic', models.CharField(blank=True, max_length=11, verbose_name='BIC')),
                ('couleur_principale', models.CharField(default='#2c3e50', help_text='Couleur principale pour les reçus (format hexadécimal)', max_length=7, verbose_name='Couleur principale')),
                ('couleur_secondaire', models.CharField(default='#3498db', help_text='Couleur secondaire pour les reçus (format hexadécimal)', max_length=7, verbose_name='Couleur secondaire')),
                ('police_principale', models.CharField(default='Arial', help_text='Police principale pour les reçus', max_length=50, verbose_name='Police principale')),
                ('police_titre', models.CharField(default='Arial', help_text='Police pour les titres des reçus', max_length=50, verbose_name='Police des titres')),
                ('afficher_logo', models.BooleanField(default=True, help_text='Afficher le logo sur les reçus', verbose_name='Afficher le logo')),
                ('afficher_siret', models.BooleanField(default=True, help_text='Afficher le numéro SIRET sur les reçus', verbose_name='Afficher le SIRET')),
                ('afficher_tva', models.BooleanField(default=True, help_text='Afficher le numéro de TVA sur les reçus', verbose_name='Afficher la TVA')),
                ('afficher_iban', models.BooleanField(default=False, help_text="Afficher l'IBAN sur les reçus", verbose_name="Afficher l'IBAN")),
                ('pied_page', models.TextField(blank=True, help_text='Texte personnalisé pour le pied de page des reçus', verbose_name='Pied de page personnalisé')),
                ('conditions_generales', models.TextField(blank=True, help_text='Conditions générales à afficher sur les reçus', verbose_name='Conditions générales')),
                ('date_creation', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
                ('date_modification', models.DateTimeField(auto_now=True, verbose_name='Date de modification')),
                ('actif', models.BooleanField(default=True, help_text='Cette configuration est-elle active ?', verbose_name='Configuration active')),
            ],
            options={
                'verbose_name': 'Configuration entreprise',
                'verbose_name_plural': 'Configurations entreprise',
                'ordering': ['-date_modification'],
            },
        ),
        migrations.CreateModel(
            name='TemplateRecu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100, verbose_name='Nom du template')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('fichier_template', models.FileField(help_text='Fichier HTML du template', upload_to='templates_recus/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['html', 'htm'])], verbose_name='Fichier template')),
                ('couleur_principale', models.CharField(default='#2c3e50', max_length=7, verbose_name='Couleur principale')),
                ('couleur_secondaire', models.CharField(default='#3498db', max_length=7, verbose_name='Couleur secondaire')),
                ('police_principale', models.CharField(default='Arial', max_length=50, verbose_name='Police principale')),
                ('afficher_logo', models.BooleanField(default=True, verbose_name='Afficher le logo')),
                ('afficher_siret', models.BooleanField(default=True, verbose_name='Afficher le SIRET')),
                ('afficher_tva', models.BooleanField(default=True, verbose_name='Afficher la TVA')),
                ('afficher_iban', models.BooleanField(default=False, verbose_name="Afficher l'IBAN")),
                ('date_creation', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
                ('date_modification', models.DateTimeField(auto_now=True, verbose_name='Date de modification')),
                ('actif', models.BooleanField(default=True, verbose_name='Template actif')),
                ('par_defaut', models.BooleanField(default=False, verbose_name='Template par défaut')),
            ],
            options={
                'verbose_name': 'Template de reçu',
                'verbose_name_plural': 'Templates de reçus',
                'ordering': ['nom'],
            },
        ),
    ]
