# Generated by Django 4.2.7 on 2025-07-20 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='configurationentreprise',
            options={'verbose_name': 'Configuration Entreprise', 'verbose_name_plural': 'Configurations Entreprise'},
        ),
        migrations.RemoveField(
            model_name='configurationentreprise',
            name='afficher_iban',
        ),
        migrations.RemoveField(
            model_name='configurationentreprise',
            name='afficher_logo',
        ),
        migrations.RemoveField(
            model_name='configurationentreprise',
            name='afficher_siret',
        ),
        migrations.RemoveField(
            model_name='configurationentreprise',
            name='afficher_tva',
        ),
        migrations.RemoveField(
            model_name='configurationentreprise',
            name='conditions_generales',
        ),
        migrations.RemoveField(
            model_name='configurationentreprise',
            name='logo',
        ),
        migrations.RemoveField(
            model_name='configurationentreprise',
            name='nom_commercial',
        ),
        migrations.RemoveField(
            model_name='configurationentreprise',
            name='pied_page',
        ),
        migrations.RemoveField(
            model_name='configurationentreprise',
            name='police_principale',
        ),
        migrations.RemoveField(
            model_name='configurationentreprise',
            name='police_titre',
        ),
        migrations.RemoveField(
            model_name='configurationentreprise',
            name='rcs',
        ),
        migrations.RemoveField(
            model_name='configurationentreprise',
            name='tva_intra',
        ),
        migrations.AddField(
            model_name='configurationentreprise',
            name='capital_social',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='configurationentreprise',
            name='code_postal',
            field=models.CharField(default='75001', max_length=10),
        ),
        migrations.AddField(
            model_name='configurationentreprise',
            name='forme_juridique',
            field=models.CharField(default='SARL', max_length=100),
        ),
        migrations.AddField(
            model_name='configurationentreprise',
            name='logo_url',
            field=models.URLField(blank=True, help_text="URL du logo de l'entreprise", null=True),
        ),
        migrations.AddField(
            model_name='configurationentreprise',
            name='numero_licence',
            field=models.CharField(default='123456789', max_length=50),
        ),
        migrations.AddField(
            model_name='configurationentreprise',
            name='pays',
            field=models.CharField(default='France', max_length=100),
        ),
        migrations.AddField(
            model_name='configurationentreprise',
            name='slogan',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='configurationentreprise',
            name='ville',
            field=models.CharField(default='Paris', max_length=100),
        ),
        migrations.AlterField(
            model_name='configurationentreprise',
            name='actif',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='configurationentreprise',
            name='adresse',
            field=models.CharField(default='123 Rue de la Paix', max_length=200),
        ),
        migrations.AlterField(
            model_name='configurationentreprise',
            name='banque',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='configurationentreprise',
            name='bic',
            field=models.CharField(blank=True, max_length=11, null=True),
        ),
        migrations.AlterField(
            model_name='configurationentreprise',
            name='couleur_principale',
            field=models.CharField(default='#2c3e50', help_text='Couleur principale (format hex)', max_length=7),
        ),
        migrations.AlterField(
            model_name='configurationentreprise',
            name='couleur_secondaire',
            field=models.CharField(default='#3498db', help_text='Couleur secondaire (format hex)', max_length=7),
        ),
        migrations.AlterField(
            model_name='configurationentreprise',
            name='date_creation',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='configurationentreprise',
            name='date_modification',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='configurationentreprise',
            name='email',
            field=models.EmailField(default='contact@gestimmob.fr', max_length=254),
        ),
        migrations.AlterField(
            model_name='configurationentreprise',
            name='iban',
            field=models.CharField(blank=True, max_length=34, null=True),
        ),
        migrations.AlterField(
            model_name='configurationentreprise',
            name='nom_entreprise',
            field=models.CharField(default='GESTIMMOB', max_length=200),
        ),
        migrations.AlterField(
            model_name='configurationentreprise',
            name='siret',
            field=models.CharField(default='123 456 789 00012', max_length=20),
        ),
        migrations.AlterField(
            model_name='configurationentreprise',
            name='site_web',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='configurationentreprise',
            name='telephone',
            field=models.CharField(default='01 23 45 67 89', max_length=20),
        ),
    ]
