# Generated by Django 5.2.4 on 2025-08-21 23:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_configurationentreprise_texte_contrat_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LogAudit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('modele', models.CharField(max_length=100, verbose_name='Modèle concerné')),
                ('instance_id', models.IntegerField(verbose_name="ID de l'instance")),
                ('action', models.CharField(max_length=50, verbose_name='Action effectuée')),
                ('description', models.TextField(verbose_name="Description de l'action")),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='Adresse IP')),
                ('user_agent', models.TextField(blank=True, null=True, verbose_name='User Agent')),
                ('donnees_avant', models.JSONField(default=dict, verbose_name='Données avant modification')),
                ('donnees_apres', models.JSONField(default=dict, verbose_name='Données après modification')),
                ('date_action', models.DateTimeField(auto_now_add=True, verbose_name="Date de l'action")),
                ('deleted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='logaudit_deleted', to=settings.AUTH_USER_MODEL, verbose_name='Supprimé par')),
                ('utilisateur', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name="Utilisateur ayant effectué l'action")),
            ],
            options={
                'verbose_name': "Log d'audit",
                'verbose_name_plural': "Logs d'audit",
                'ordering': ['-date_action'],
                'indexes': [models.Index(fields=['modele', 'instance_id'], name='core_logaud_modele_ce2e6b_idx'), models.Index(fields=['action'], name='core_logaud_action_f4f116_idx'), models.Index(fields=['utilisateur'], name='core_logaud_utilisa_8baf44_idx'), models.Index(fields=['date_action'], name='core_logaud_date_ac_d42c4d_idx')],
            },
        ),
    ]
