# Generated by Django 5.2.5 on 2025-08-23 13:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_fix_devise_model'),
        ('core', '0011_auto_20250823_1502'),
    ]

    operations = [
    ]
