# Generated by Django 5.2.5 on 2025-08-25 08:05

import django.core.validators
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('core', '0014_add_missing_configuration_fields'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='logaudit',
            name='deleted_by',
        ),
        migrations.RemoveField(
            model_name='logaudit',
            name='utilisateur',
        ),
        migrations.AlterModelOptions(
            name='configurationentreprise',
            options={'ordering': ['-date_modification'], 'verbose_name': 'Configuration Entreprise', 'verbose_name_plural': 'Configurations Entreprise'},
        ),
        migrations.AlterModelOptions(
            name='configurationtableaubord',
            options={'ordering': ['utilisateur', '-par_defaut', 'nom_tableau'], 'verbose_name': 'Configuration tableau de bord', 'verbose_name_plural': 'Configurations tableaux de bord'},
        ),
        migrations.AlterModelOptions(
            name='devise',
            options={'ordering': ['nom'], 'verbose_name': 'Devise', 'verbose_name_plural': 'Devises'},
        ),
        migrations.RemoveField(
            model_name='devise',
            name='taux_par_rapport_a_eur',
        ),
        migrations.RemoveField(
            model_name='templaterecu',
            name='afficher_iban',
        ),
        migrations.RemoveField(
            model_name='templaterecu',
            name='afficher_logo',
        ),
        migrations.RemoveField(
            model_name='templaterecu',
            name='afficher_siret',
        ),
        migrations.RemoveField(
            model_name='templaterecu',
            name='afficher_tva',
        ),
        migrations.RemoveField(
            model_name='templaterecu',
            name='couleur_principale',
        ),
        migrations.RemoveField(
            model_name='templaterecu',
            name='couleur_secondaire',
        ),
        migrations.RemoveField(
            model_name='templaterecu',
            name='deleted_at',
        ),
        migrations.RemoveField(
            model_name='templaterecu',
            name='deleted_by',
        ),
        migrations.RemoveField(
            model_name='templaterecu',
            name='fichier_template',
        ),
        migrations.RemoveField(
            model_name='templaterecu',
            name='is_deleted',
        ),
        migrations.RemoveField(
            model_name='templaterecu',
            name='par_defaut',
        ),
        migrations.RemoveField(
            model_name='templaterecu',
            name='police_principale',
        ),
        migrations.AddField(
            model_name='auditlog',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='Description'),
        ),
        migrations.AddField(
            model_name='templaterecu',
            name='contenu_html',
            field=models.TextField(default='<p>Template vide</p>', help_text='Template HTML avec variables Django', verbose_name='Contenu HTML'),
        ),
        migrations.AddField(
            model_name='templaterecu',
            name='variables_disponibles',
            field=models.JSONField(default=list, help_text='Liste des variables utilisables dans le template', verbose_name='Variables disponibles'),
        ),
        migrations.AlterField(
            model_name='auditlog',
            name='action',
            field=models.CharField(choices=[('create', 'Création'), ('update', 'Modification'), ('delete', 'Suppression'), ('view', 'Consultation'), ('export', 'Export'), ('import', 'Import'), ('login', 'Connexion'), ('logout', 'Déconnexion'), ('validation', 'Validation'), ('rejection', 'Rejet')], max_length=20, verbose_name='Action'),
        ),
        migrations.AlterField(
            model_name='configurationentreprise',
            name='actif',
            field=models.BooleanField(default=True, verbose_name='Actif'),
        ),
        migrations.AlterField(
            model_name='configurationentreprise',
            name='adresse',
            field=models.CharField(default='123 Rue de la Paix', max_length=200, verbose_name='Adresse'),
        ),
        migrations.AlterField(
            model_name='configurationentreprise',
            name='banque',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Banque'),
        ),
        migrations.AlterField(
            model_name='configurationentreprise',
            name='bic',
            field=models.CharField(blank=True, max_length=11, null=True, verbose_name='BIC'),
        ),
        migrations.AlterField(
            model_name='configurationentreprise',
            name='capital_social',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Capital social'),
        ),
        migrations.AlterField(
            model_name='configurationentreprise',
            name='code_postal',
            field=models.CharField(default='75001', max_length=10, verbose_name='Code postal'),
        ),
        migrations.AlterField(
            model_name='configurationentreprise',
            name='couleur_principale',
            field=models.CharField(default='#2c3e50', help_text='Couleur principale (format hex)', max_length=7, verbose_name='Couleur principale'),
        ),
        migrations.AlterField(
            model_name='configurationentreprise',
            name='couleur_secondaire',
            field=models.CharField(default='#3498db', help_text='Couleur secondaire (format hex)', max_length=7, verbose_name='Couleur secondaire'),
        ),
        migrations.AlterField(
            model_name='configurationentreprise',
            name='email',
            field=models.EmailField(default='contact@gestimmob.fr', max_length=254, verbose_name='Email'),
        ),
        migrations.AlterField(
            model_name='configurationentreprise',
            name='forme_juridique',
            field=models.CharField(default='SARL', max_length=100, verbose_name='Forme juridique'),
        ),
        migrations.AlterField(
            model_name='configurationentreprise',
            name='iban',
            field=models.CharField(blank=True, max_length=34, null=True, verbose_name='IBAN'),
        ),
        migrations.AlterField(
            model_name='configurationentreprise',
            name='logo_url',
            field=models.URLField(blank=True, help_text="URL du logo de l'entreprise", null=True, verbose_name='URL du logo'),
        ),
        migrations.AlterField(
            model_name='configurationentreprise',
            name='nom_entreprise',
            field=models.CharField(default='GESTIMMOB', max_length=200, verbose_name="Nom de l'entreprise"),
        ),
        migrations.AlterField(
            model_name='configurationentreprise',
            name='numero_licence',
            field=models.CharField(default='123456789', max_length=50, verbose_name='Numéro de licence'),
        ),
        migrations.AlterField(
            model_name='configurationentreprise',
            name='pays',
            field=models.CharField(default='France', max_length=100, verbose_name='Pays'),
        ),
        migrations.AlterField(
            model_name='configurationentreprise',
            name='siret',
            field=models.CharField(default='123 456 789 00012', max_length=20, verbose_name='Numéro SIRET'),
        ),
        migrations.AlterField(
            model_name='configurationentreprise',
            name='site_web',
            field=models.URLField(blank=True, null=True, verbose_name='Site web'),
        ),
        migrations.AlterField(
            model_name='configurationentreprise',
            name='slogan',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Slogan'),
        ),
        migrations.AlterField(
            model_name='configurationentreprise',
            name='telephone',
            field=models.CharField(default='01 23 45 67 89', max_length=20, verbose_name='Téléphone'),
        ),
        migrations.AlterField(
            model_name='configurationentreprise',
            name='ville',
            field=models.CharField(default='Paris', max_length=100, verbose_name='Ville'),
        ),
        migrations.AlterField(
            model_name='configurationtableaubord',
            name='affichage_anonymise',
            field=models.BooleanField(default=False, help_text='Remplacer les noms par des codes', verbose_name='Affichage anonymisé'),
        ),
        migrations.AlterField(
            model_name='configurationtableaubord',
            name='configuration_widgets',
            field=models.JSONField(default=dict, help_text='Configuration spécifique de chaque widget', verbose_name='Configuration des widgets'),
        ),
        migrations.AlterField(
            model_name='configurationtableaubord',
            name='nom_tableau',
            field=models.CharField(max_length=100, verbose_name='Nom du tableau de bord'),
        ),
        migrations.AlterField(
            model_name='configurationtableaubord',
            name='ordre_widgets',
            field=models.JSONField(default=list, help_text="Ordre d'affichage des widgets", verbose_name='Ordre des widgets'),
        ),
        migrations.AlterField(
            model_name='configurationtableaubord',
            name='par_defaut',
            field=models.BooleanField(default=False, verbose_name='Tableau par défaut'),
        ),
        migrations.AlterField(
            model_name='configurationtableaubord',
            name='widgets_actifs',
            field=models.JSONField(default=list, help_text='Liste des widgets activés pour ce tableau', verbose_name='Widgets actifs'),
        ),
        migrations.AlterField(
            model_name='devise',
            name='actif',
            field=models.BooleanField(default=True, verbose_name='Actif'),
        ),
        migrations.AlterField(
            model_name='devise',
            name='code',
            field=models.CharField(help_text='Code ISO 4217 (ex: EUR, USD, XOF)', max_length=3, unique=True, verbose_name='Code devise'),
        ),
        migrations.AlterField(
            model_name='devise',
            name='nom',
            field=models.CharField(max_length=100, verbose_name='Nom de la devise'),
        ),
        migrations.AlterField(
            model_name='devise',
            name='symbole',
            field=models.CharField(max_length=10, verbose_name='Symbole'),
        ),
        migrations.AlterField(
            model_name='niveauacces',
            name='description',
            field=models.TextField(help_text="Description détaillée du niveau d'accès", verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='niveauacces',
            name='groupes_autorises',
            field=models.ManyToManyField(help_text="Groupes d'utilisateurs autorisés à ce niveau", related_name='niveaux_acces', to='auth.group', verbose_name='Groupes autorisés'),
        ),
        migrations.AlterField(
            model_name='niveauacces',
            name='priorite',
            field=models.PositiveIntegerField(help_text='1 = niveau le plus bas, 10 = niveau le plus élevé', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)], verbose_name='Priorité'),
        ),
        migrations.AlterField(
            model_name='permissiontableaubord',
            name='limite_nombre_resultats',
            field=models.PositiveIntegerField(blank=True, help_text='Nombre maximum de résultats affichés (null = illimité)', null=True, verbose_name='Limite nombre de résultats'),
        ),
        migrations.AlterField(
            model_name='permissiontableaubord',
            name='limite_periode_jours',
            field=models.PositiveIntegerField(blank=True, help_text='Nombre de jours maximum dans le passé (null = illimité)', null=True, verbose_name='Limitation période (jours)'),
        ),
        migrations.AlterField(
            model_name='templaterecu',
            name='actif',
            field=models.BooleanField(default=True, verbose_name='Actif'),
        ),
        migrations.AlterField(
            model_name='templaterecu',
            name='date_creation',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='templaterecu',
            name='date_modification',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='templaterecu',
            name='nom',
            field=models.CharField(max_length=100, unique=True, verbose_name='Nom du template'),
        ),
        migrations.AlterUniqueTogether(
            name='configurationtableaubord',
            unique_together={('utilisateur', 'nom_tableau')},
        ),
        migrations.AddIndex(
            model_name='logaccesdonnees',
            index=models.Index(fields=['utilisateur', '-timestamp'], name='core_logacc_utilisa_b4ca68_idx'),
        ),
        migrations.AddIndex(
            model_name='logaccesdonnees',
            index=models.Index(fields=['type_donnees', '-timestamp'], name='core_logacc_type_do_5a8ea6_idx'),
        ),
        migrations.AddIndex(
            model_name='logaccesdonnees',
            index=models.Index(fields=['niveau_acces_utilise', '-timestamp'], name='core_logacc_niveau__2a2d9c_idx'),
        ),
        migrations.DeleteModel(
            name='LogAudit',
        ),
    ]
