# Generated by Django 5.2.5 on 2025-08-25 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_add_missing_auditlog_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='configurationentreprise',
            name='logo_upload',
            field=models.ImageField(blank=True, help_text='Logo uploadé directement (PNG, JPG, GIF - max 5MB)', null=True, upload_to='logos_entreprise/', verbose_name='Logo uploadé'),
        ),
        migrations.AlterField(
            model_name='configurationentreprise',
            name='logo_url',
            field=models.URLField(blank=True, help_text="URL externe du logo de l'entreprise (optionnel)", null=True, verbose_name='URL externe du logo'),
        ),
        migrations.AlterField(
            model_name='devise',
            name='code',
            field=models.CharField(help_text='Code ISO 4217 (ex: EUR, USD, F CFA)', max_length=3, unique=True, verbose_name='Code devise'),
        ),
    ]
