# Generated by Django 4.2.24 on 2025-10-17 20:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0019_auto_20251005_2002'),
    ]

    operations = [
        migrations.CreateModel(
            name='TemplateDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100, unique=True)),
                ('type_document', models.CharField(choices=[('recu', 'Reçu de paiement'), ('facture', 'Facture'), ('contrat', 'Contrat de location'), ('quittance', 'Quittance de loyer'), ('courrier', 'Courrier officiel'), ('rapport', 'Rapport'), ('autre', 'Autre document')], max_length=20)),
                ('description', models.TextField(blank=True)),
                ('format_page', models.CharField(choices=[('A4', 'Format A4'), ('A5', 'Format A5'), ('letter', 'Format Lettre US')], default='A4', max_length=10)),
                ('marge_haut', models.IntegerField(default=20, help_text='Marge en mm')),
                ('marge_bas', models.IntegerField(default=20, help_text='Marge en mm')),
                ('marge_gauche', models.IntegerField(default=20, help_text='Marge en mm')),
                ('marge_droite', models.IntegerField(default=20, help_text='Marge en mm')),
                ('inclure_entete', models.BooleanField(default=True)),
                ('inclure_pied_page', models.BooleanField(default=True)),
                ('hauteur_entete', models.IntegerField(default=80, help_text='Hauteur en mm')),
                ('hauteur_pied_page', models.IntegerField(default=40, help_text='Hauteur en mm')),
                ('template_html', models.TextField(blank=True, help_text='Template HTML personnalisé')),
                ('css_personnalise', models.TextField(blank=True, help_text='CSS personnalisé')),
                ('par_defaut', models.BooleanField(default=False)),
                ('actif', models.BooleanField(default=True)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('date_modification', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Template de Document',
                'verbose_name_plural': 'Templates de Documents',
                'ordering': ['type_document', 'nom'],
            },
        ),
        migrations.AlterModelOptions(
            name='configurationentreprise',
            options={'verbose_name': "Configuration d'Entreprise", 'verbose_name_plural': "Configurations d'Entreprise"},
        ),
        migrations.RemoveField(
            model_name='configurationentreprise',
            name='actif',
        ),
        migrations.RemoveField(
            model_name='configurationentreprise',
            name='adresse',
        ),
        migrations.RemoveField(
            model_name='configurationentreprise',
            name='banque',
        ),
        migrations.RemoveField(
            model_name='configurationentreprise',
            name='bic',
        ),
        migrations.RemoveField(
            model_name='configurationentreprise',
            name='capital_social',
        ),
        migrations.RemoveField(
            model_name='configurationentreprise',
            name='entete_upload',
        ),
        migrations.RemoveField(
            model_name='configurationentreprise',
            name='forme_juridique',
        ),
        migrations.RemoveField(
            model_name='configurationentreprise',
            name='iban',
        ),
        migrations.RemoveField(
            model_name='configurationentreprise',
            name='logo_upload',
        ),
        migrations.RemoveField(
            model_name='configurationentreprise',
            name='logo_url',
        ),
        migrations.RemoveField(
            model_name='configurationentreprise',
            name='numero_licence',
        ),
        migrations.RemoveField(
            model_name='configurationentreprise',
            name='siret',
        ),
        migrations.RemoveField(
            model_name='configurationentreprise',
            name='texte_contrat',
        ),
        migrations.RemoveField(
            model_name='configurationentreprise',
            name='texte_resiliation',
        ),
        migrations.RemoveField(
            model_name='devise',
            name='actif',
        ),
        migrations.RemoveField(
            model_name='niveauacces',
            name='actif',
        ),
        migrations.RemoveField(
            model_name='permissiontableaubord',
            name='actif',
        ),
        migrations.RemoveField(
            model_name='templaterecu',
            name='actif',
        ),
        migrations.AddField(
            model_name='configurationentreprise',
            name='active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='configurationentreprise',
            name='adresse_ligne1',
            field=models.CharField(default='Avenue de la République', max_length=200),
        ),
        migrations.AddField(
            model_name='configurationentreprise',
            name='adresse_ligne2',
            field=models.CharField(blank=True, default='Quartier Centre-Ville', max_length=200),
        ),
        migrations.AddField(
            model_name='configurationentreprise',
            name='ifu',
            field=models.CharField(blank=True, default='XXXXXXXXXX', max_length=20),
        ),
        migrations.AddField(
            model_name='configurationentreprise',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='logos/'),
        ),
        migrations.AddField(
            model_name='configurationentreprise',
            name='numero_compte_contribuable',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AddField(
            model_name='configurationentreprise',
            name='rccm',
            field=models.CharField(blank=True, default='CI-ABJ-XXXX-X-XXXXX', max_length=50),
        ),
        migrations.AddField(
            model_name='configurationentreprise',
            name='telephone_2',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='devise',
            name='active',
            field=models.BooleanField(default=True, verbose_name='Actif'),
        ),
        migrations.AddField(
            model_name='niveauacces',
            name='active',
            field=models.BooleanField(default=True, verbose_name='Actif'),
        ),
        migrations.AddField(
            model_name='permissiontableaubord',
            name='active',
            field=models.BooleanField(default=True, verbose_name='Actif'),
        ),
        migrations.AddField(
            model_name='templaterecu',
            name='active',
            field=models.BooleanField(default=True, verbose_name='Actif'),
        ),
        migrations.AlterField(
            model_name='configurationentreprise',
            name='code_postal',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='configurationentreprise',
            name='couleur_principale',
            field=models.CharField(default='#2c5aa0', help_text='Couleur hexadécimale', max_length=7),
        ),
        migrations.AlterField(
            model_name='configurationentreprise',
            name='couleur_secondaire',
            field=models.CharField(default='#f8f9fa', help_text='Couleur hexadécimale', max_length=7),
        ),
        migrations.AlterField(
            model_name='configurationentreprise',
            name='email',
            field=models.EmailField(default='contact@kbis-immobilier.ci', max_length=254),
        ),
        migrations.AlterField(
            model_name='configurationentreprise',
            name='nom_entreprise',
            field=models.CharField(default='KBIS IMMOBILIER', max_length=200),
        ),
        migrations.AlterField(
            model_name='configurationentreprise',
            name='pays',
            field=models.CharField(default="Côte d'Ivoire", max_length=100),
        ),
        migrations.AlterField(
            model_name='configurationentreprise',
            name='site_web',
            field=models.URLField(blank=True, default='www.kbis-immobilier.ci'),
        ),
        migrations.AlterField(
            model_name='configurationentreprise',
            name='slogan',
            field=models.CharField(default='Votre Partenaire Immobilier de Confiance', max_length=300),
        ),
        migrations.AlterField(
            model_name='configurationentreprise',
            name='telephone',
            field=models.CharField(default='+225 XX XX XX XX XX', max_length=20),
        ),
        migrations.AlterField(
            model_name='configurationentreprise',
            name='ville',
            field=models.CharField(default='Abidjan', max_length=100),
        ),
        migrations.CreateModel(
            name='HistoriqueGeneration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_document', models.CharField(max_length=20)),
                ('nom_fichier', models.CharField(max_length=200)),
                ('taille_fichier', models.IntegerField(blank=True, help_text='Taille en octets', null=True)),
                ('reference_objet', models.CharField(blank=True, help_text="ID de l'objet source", max_length=100)),
                ('type_objet', models.CharField(blank=True, help_text="Type de l'objet source", max_length=50)),
                ('date_generation', models.DateTimeField(auto_now_add=True)),
                ('succes', models.BooleanField(default=True)),
                ('message_erreur', models.TextField(blank=True)),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.templatedocument')),
            ],
            options={
                'verbose_name': 'Historique de Génération',
                'verbose_name_plural': 'Historiques de Génération',
                'ordering': ['-date_generation'],
            },
        ),
    ]
