# Generated by Django 4.2.24 on 2025-10-19 00:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0020_templatedocument_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SecurityEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(choices=[('login_success', 'Connexion réussie'), ('login_failed', 'Échec de connexion'), ('logout', 'Déconnexion'), ('password_change', 'Changement de mot de passe'), ('permission_denied', 'Accès refusé'), ('suspicious_activity', 'Activité suspecte'), ('file_upload', 'Upload de fichier'), ('data_access', 'Accès aux données'), ('data_modification', 'Modification de données'), ('session_invalidated', 'Session invalidée'), ('rate_limit_exceeded', 'Limite de taux dépassée'), ('sql_injection_attempt', "Tentative d'injection SQL"), ('xss_attempt', 'Tentative XSS'), ('file_security_violation', 'Violation de sécurité fichier')], max_length=50)),
                ('severity', models.CharField(choices=[('low', 'Faible'), ('medium', 'Moyen'), ('high', 'Élevé'), ('critical', 'Critique')], default='medium', max_length=20)),
                ('ip_address', models.GenericIPAddressField()),
                ('user_agent', models.TextField(blank=True)),
                ('description', models.TextField()),
                ('details', models.JSONField(blank=True, default=dict)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('resolved', models.BooleanField(default=False)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['event_type', 'timestamp'], name='core_securi_event_t_72c930_idx'), models.Index(fields=['severity', 'timestamp'], name='core_securi_severit_382860_idx'), models.Index(fields=['user', 'timestamp'], name='core_securi_user_id_8e89f8_idx'), models.Index(fields=['ip_address', 'timestamp'], name='core_securi_ip_addr_a2d011_idx')],
            },
        ),
    ]
