# Generated by Django 4.2.24 on 2025-10-25 07:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0021_securityevent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='devise',
            name='code',
            field=models.CharField(help_text='Code ISO 4217 (ex: XOF, USD, F CFA)', max_length=3, unique=True, verbose_name='Code devise'),
        ),
    ]
