# Generated by Django 4.2.24 on 2025-10-30 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0022_alter_devise_code'),
    ]

    operations = [
        migrations.CreateModel(
            name='AutoNumberSequence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scope', models.CharField(max_length=50, verbose_name='Portée')),
                ('year', models.PositiveIntegerField(verbose_name='Année')),
                ('current', models.PositiveIntegerField(default=0, verbose_name='Compteur courant')),
            ],
            options={
                'verbose_name': 'Séquence de numérotation',
                'verbose_name_plural': 'Séquences de numérotation',
                'indexes': [models.Index(fields=['scope', 'year'], name='core_autonu_scope_90f76c_idx')],
                'unique_together': {('scope', 'year')},
            },
        ),
    ]
