# Generated by Django 4.2.24 on 2026-01-20 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0024_add_telephone_3_4'),
    ]

    operations = [
        migrations.AddField(
            model_name='configurationentreprise',
            name='nombre_mois_avance',
            field=models.PositiveIntegerField(default=1, help_text='Nombre de mois de loyer à payer en avance (généralement 1)', verbose_name="Nombre de mois d'avance"),
        ),
        migrations.AddField(
            model_name='configurationentreprise',
            name='nombre_mois_caution',
            field=models.PositiveIntegerField(default=3, help_text='Nombre de mois de loyer pour la caution (généralement 3)', verbose_name='Nombre de mois de caution'),
        ),
    ]
