# Generated by Django 4.2.7 on 2025-07-19 19:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Bailleur',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100, verbose_name='Nom')),
                ('prenom', models.CharField(max_length=100, verbose_name='Prénom')),
                ('email', models.EmailField(max_length=254, verbose_name='Email')),
                ('telephone', models.CharField(max_length=20, verbose_name='Téléphone')),
                ('adresse', models.TextField(verbose_name='Adresse')),
                ('profession', models.CharField(blank=True, max_length=100, verbose_name='Profession')),
                ('entreprise', models.CharField(blank=True, max_length=100, verbose_name='Entreprise')),
                ('iban', models.CharField(blank=True, max_length=34, verbose_name='IBAN')),
                ('bic', models.CharField(blank=True, max_length=11, verbose_name='BIC')),
                ('date_creation', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
                ('date_modification', models.DateTimeField(auto_now=True, verbose_name='Date de modification')),
                ('est_actif', models.BooleanField(default=True, verbose_name='Actif')),
                ('notes', models.TextField(blank=True, verbose_name='Notes')),
                ('cree_par', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bailleurs_crees', to=settings.AUTH_USER_MODEL, verbose_name='Créé par')),
            ],
            options={
                'verbose_name': 'Bailleur',
                'verbose_name_plural': 'Bailleurs',
                'ordering': ['nom', 'prenom'],
                'unique_together': {('nom', 'prenom', 'email')},
            },
        ),
        migrations.CreateModel(
            name='TypeBien',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=50, unique=True, verbose_name='Nom')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
            ],
            options={
                'verbose_name': 'Type de bien',
                'verbose_name_plural': 'Types de biens',
                'ordering': ['nom'],
            },
        ),
        migrations.CreateModel(
            name='Propriete',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=200, verbose_name='Titre')),
                ('adresse', models.TextField(verbose_name='Adresse')),
                ('code_postal', models.CharField(max_length=10, verbose_name='Code postal')),
                ('ville', models.CharField(max_length=100, verbose_name='Ville')),
                ('pays', models.CharField(default='France', max_length=100, verbose_name='Pays')),
                ('surface', models.DecimalField(decimal_places=2, max_digits=8, verbose_name='Surface (m²)')),
                ('nombre_pieces', models.PositiveIntegerField(verbose_name='Nombre de pièces')),
                ('nombre_chambres', models.PositiveIntegerField(default=0, verbose_name='Nombre de chambres')),
                ('nombre_salles_bain', models.PositiveIntegerField(default=0, verbose_name='Nombre de salles de bain')),
                ('ascenseur', models.BooleanField(default=False, verbose_name='Ascenseur')),
                ('parking', models.BooleanField(default=False, verbose_name='Parking')),
                ('balcon', models.BooleanField(default=False, verbose_name='Balcon')),
                ('jardin', models.BooleanField(default=False, verbose_name='Jardin')),
                ('prix_achat', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name="Prix d'achat")),
                ('loyer_actuel', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, verbose_name='Loyer actuel')),
                ('charges', models.DecimalField(decimal_places=2, default=0, max_digits=8, verbose_name='Charges')),
                ('etat', models.CharField(choices=[('excellent', 'Excellent'), ('bon', 'Bon'), ('moyen', 'Moyen'), ('mauvais', 'Mauvais'), ('tres_mauvais', 'Très mauvais')], default='bon', max_length=20, verbose_name='État')),
                ('disponible', models.BooleanField(default=True, verbose_name='Disponible')),
                ('date_creation', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
                ('date_modification', models.DateTimeField(auto_now=True, verbose_name='Date de modification')),
                ('est_actif', models.BooleanField(default=True, verbose_name='Actif')),
                ('notes', models.TextField(blank=True, verbose_name='Notes')),
                ('bailleur', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='proprietes', to='proprietes.bailleur', verbose_name='Bailleur')),
                ('cree_par', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='proprietes_crees', to=settings.AUTH_USER_MODEL, verbose_name='Créé par')),
                ('type_bien', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='proprietes.typebien', verbose_name='Type de bien')),
            ],
            options={
                'verbose_name': 'Propriété',
                'verbose_name_plural': 'Propriétés',
                'ordering': ['ville', 'adresse'],
            },
        ),
        migrations.CreateModel(
            name='Locataire',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100, verbose_name='Nom')),
                ('prenom', models.CharField(max_length=100, verbose_name='Prénom')),
                ('email', models.EmailField(max_length=254, verbose_name='Email')),
                ('telephone', models.CharField(max_length=20, verbose_name='Téléphone')),
                ('adresse_actuelle', models.TextField(verbose_name='Adresse actuelle')),
                ('profession', models.CharField(blank=True, max_length=100, verbose_name='Profession')),
                ('employeur', models.CharField(blank=True, max_length=100, verbose_name='Employeur')),
                ('salaire_mensuel', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Salaire mensuel')),
                ('iban', models.CharField(blank=True, max_length=34, verbose_name='IBAN')),
                ('bic', models.CharField(blank=True, max_length=11, verbose_name='BIC')),
                ('date_creation', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
                ('date_modification', models.DateTimeField(auto_now=True, verbose_name='Date de modification')),
                ('est_actif', models.BooleanField(default=True, verbose_name='Actif')),
                ('notes', models.TextField(blank=True, verbose_name='Notes')),
                ('cree_par', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='locataires_crees', to=settings.AUTH_USER_MODEL, verbose_name='Créé par')),
            ],
            options={
                'verbose_name': 'Locataire',
                'verbose_name_plural': 'Locataires',
                'ordering': ['nom', 'prenom'],
                'unique_together': {('nom', 'prenom', 'email')},
            },
        ),
    ]
