# Generated by Django 5.2.4 on 2025-08-06 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proprietes', '0003_bailleur_deleted_at_bailleur_deleted_by_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chargesbailleur',
            name='montant',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Montant (XOF)'),
        ),
        migrations.AlterField(
            model_name='chargesbailleur',
            name='montant_rembourse',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Montant remboursé (XOF)'),
        ),
    ]
