# Generated by Django 5.2.4 on 2025-08-10 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proprietes', '0004_alter_chargesbailleur_montant_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='chargesbailleur',
            name='est_actif',
            field=models.BooleanField(default=True, verbose_name='Actif'),
        ),
        migrations.AddField(
            model_name='typebien',
            name='est_actif',
            field=models.BooleanField(default=True, verbose_name='Actif'),
        ),
    ]
