# Generated by Django 5.2.4 on 2025-08-19 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proprietes', '0005_add_est_actif_to_typebien_chargesbailleur'),
    ]

    operations = [
        migrations.AddField(
            model_name='bailleur',
            name='code_bailleur',
            field=models.CharField(blank=True, help_text='Code unique pour identifier le bailleur', max_length=20, null=True, unique=True, verbose_name='Code Bailleur'),
        ),
        migrations.AddField(
            model_name='locataire',
            name='code_locataire',
            field=models.CharField(blank=True, help_text='Code unique pour identifier le locataire', max_length=20, null=True, unique=True, verbose_name='Code Locataire'),
        ),
    ]
