# Generated by Django 5.2.4 on 2025-08-20 07:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proprietes', '0006_add_unique_codes'),
    ]

    operations = [
        migrations.AddField(
            model_name='bailleur',
            name='numero_bailleur',
            field=models.CharField(blank=True, help_text='Numéro unique professionnel du bailleur', max_length=50, null=True, unique=True, verbose_name='Numéro Bailleur'),
        ),
        migrations.AddField(
            model_name='locataire',
            name='numero_locataire',
            field=models.CharField(blank=True, help_text='Numéro unique professionnel du locataire', max_length=50, null=True, unique=True, verbose_name='Numéro Locataire'),
        ),
        migrations.AddField(
            model_name='propriete',
            name='numero_propriete',
            field=models.CharField(blank=True, help_text='Numéro unique professionnel de la propriété', max_length=50, null=True, unique=True, verbose_name='Numéro Propriété'),
        ),
    ]
