# Generated by Django 5.2.4 on 2025-08-20 09:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proprietes', '0007_bailleur_numero_bailleur_locataire_numero_locataire_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Photo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(help_text='Format recommandé: JPG, PNG. Taille max: 5MB', upload_to='proprietes/photos/', verbose_name='Image')),
                ('titre', models.CharField(help_text='Titre descriptif de la photo', max_length=100, verbose_name='Titre')),
                ('description', models.TextField(blank=True, help_text='Description détaillée de la photo', verbose_name='Description')),
                ('ordre', models.PositiveIntegerField(default=0, help_text="Ordre d'affichage dans la galerie (0 = premier)", verbose_name="Ordre d'affichage")),
                ('est_principale', models.BooleanField(default=False, help_text="Cochez si c'est la photo principale de la propriété", verbose_name='Photo principale')),
                ('date_creation', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
                ('date_modification', models.DateTimeField(auto_now=True, verbose_name='Date de modification')),
                ('propriete', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='proprietes.propriete', verbose_name='Propriété')),
            ],
            options={
                'verbose_name': 'Photo',
                'verbose_name_plural': 'Photos',
                'ordering': ['ordre', 'date_creation'],
                'unique_together': {('propriete', 'ordre')},
            },
        ),
    ]
