# Generated by Django 5.2.4 on 2025-08-20 10:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proprietes', '0008_photo'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='chargesbailleur',
            options={'ordering': ['-date_charge'], 'verbose_name': 'Charge bailleur', 'verbose_name_plural': 'Charges bailleur'},
        ),
        migrations.AlterModelOptions(
            name='propriete',
            options={'ordering': ['-date_creation'], 'verbose_name': 'Propriété', 'verbose_name_plural': 'Propriétés'},
        ),
        migrations.RenameField(
            model_name='bailleur',
            old_name='est_actif',
            new_name='actif',
        ),
        migrations.AlterUniqueTogether(
            name='bailleur',
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name='locataire',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='chargesbailleur',
            name='date_remboursement',
        ),
        migrations.RemoveField(
            model_name='chargesbailleur',
            name='deleted_at',
        ),
        migrations.RemoveField(
            model_name='chargesbailleur',
            name='deleted_by',
        ),
        migrations.RemoveField(
            model_name='chargesbailleur',
            name='est_actif',
        ),
        migrations.RemoveField(
            model_name='chargesbailleur',
            name='facture',
        ),
        migrations.RemoveField(
            model_name='chargesbailleur',
            name='is_deleted',
        ),
        migrations.RemoveField(
            model_name='chargesbailleur',
            name='montant_rembourse',
        ),
        migrations.RemoveField(
            model_name='chargesbailleur',
            name='notes',
        ),
        migrations.RemoveField(
            model_name='chargesbailleur',
            name='numero_facture',
        ),
        migrations.RemoveField(
            model_name='propriete',
            name='deleted_at',
        ),
        migrations.RemoveField(
            model_name='propriete',
            name='deleted_by',
        ),
        migrations.RemoveField(
            model_name='propriete',
            name='est_actif',
        ),
        migrations.RemoveField(
            model_name='propriete',
            name='is_deleted',
        ),
        migrations.RemoveField(
            model_name='typebien',
            name='deleted_at',
        ),
        migrations.RemoveField(
            model_name='typebien',
            name='deleted_by',
        ),
        migrations.RemoveField(
            model_name='typebien',
            name='est_actif',
        ),
        migrations.RemoveField(
            model_name='typebien',
            name='is_deleted',
        ),
        migrations.AddField(
            model_name='bailleur',
            name='banque',
            field=models.CharField(blank=True, max_length=100, verbose_name='Banque'),
        ),
        migrations.AddField(
            model_name='bailleur',
            name='civilite',
            field=models.CharField(choices=[('M', 'Monsieur'), ('Mme', 'Madame'), ('Mlle', 'Mademoiselle')], default='M', max_length=5, verbose_name='Civilité'),
        ),
        migrations.AddField(
            model_name='bailleur',
            name='code_postal',
            field=models.CharField(default='00000', max_length=10, verbose_name='Code postal'),
        ),
        migrations.AddField(
            model_name='bailleur',
            name='date_naissance',
            field=models.DateField(blank=True, null=True, verbose_name='Date de naissance'),
        ),
        migrations.AddField(
            model_name='bailleur',
            name='pays',
            field=models.CharField(default='France', max_length=100, verbose_name='Pays'),
        ),
        migrations.AddField(
            model_name='bailleur',
            name='telephone_mobile',
            field=models.CharField(blank=True, max_length=20, verbose_name='Mobile'),
        ),
        migrations.AddField(
            model_name='bailleur',
            name='ville',
            field=models.CharField(default='Ville', max_length=100, verbose_name='Ville'),
        ),
        migrations.AddField(
            model_name='chargesbailleur',
            name='date_echeance',
            field=models.DateField(blank=True, null=True, verbose_name="Date d'échéance"),
        ),
        migrations.AddField(
            model_name='chargesbailleur',
            name='date_paiement',
            field=models.DateField(blank=True, null=True, verbose_name='Date de paiement'),
        ),
        migrations.AddField(
            model_name='chargesbailleur',
            name='numero_charge',
            field=models.CharField(default='CH0001', help_text='Identifiant unique de la charge', max_length=20, unique=True, verbose_name='Numéro de charge'),
        ),
        migrations.AddField(
            model_name='locataire',
            name='adresse',
            field=models.TextField(default='Adresse', verbose_name='Adresse'),
        ),
        migrations.AddField(
            model_name='locataire',
            name='civilite',
            field=models.CharField(choices=[('M', 'Monsieur'), ('Mme', 'Madame'), ('Mlle', 'Mademoiselle')], default='M', max_length=5, verbose_name='Civilité'),
        ),
        migrations.AddField(
            model_name='locataire',
            name='code_postal',
            field=models.CharField(default='00000', max_length=10, verbose_name='Code postal'),
        ),
        migrations.AddField(
            model_name='locataire',
            name='date_naissance',
            field=models.DateField(blank=True, null=True, verbose_name='Date de naissance'),
        ),
        migrations.AddField(
            model_name='locataire',
            name='pays',
            field=models.CharField(default='France', max_length=100, verbose_name='Pays'),
        ),
        migrations.AddField(
            model_name='locataire',
            name='revenus_mensuels',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Revenus mensuels'),
        ),
        migrations.AddField(
            model_name='locataire',
            name='statut',
            field=models.CharField(choices=[('actif', 'Actif'), ('inactif', 'Inactif'), ('suspendu', 'Suspendu')], default='actif', max_length=20, verbose_name='Statut'),
        ),
        migrations.AddField(
            model_name='locataire',
            name='telephone_mobile',
            field=models.CharField(blank=True, max_length=20, verbose_name='Mobile'),
        ),
        migrations.AddField(
            model_name='locataire',
            name='ville',
            field=models.CharField(default='Ville', max_length=100, verbose_name='Ville'),
        ),
        migrations.AddField(
            model_name='propriete',
            name='description',
            field=models.TextField(blank=True, verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='bailleur',
            name='code_bailleur',
            field=models.CharField(blank=True, default='', help_text='Code personnalisé du bailleur', max_length=50, verbose_name='Code bailleur'),
        ),
        migrations.AlterField(
            model_name='bailleur',
            name='numero_bailleur',
            field=models.CharField(default='BL0001', help_text='Identifiant unique du bailleur', max_length=20, unique=True, verbose_name='Numéro bailleur'),
        ),
        migrations.AlterField(
            model_name='chargesbailleur',
            name='cree_par',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Créé par'),
        ),
        migrations.AlterField(
            model_name='chargesbailleur',
            name='description',
            field=models.TextField(blank=True, verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='chargesbailleur',
            name='montant',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Montant'),
        ),
        migrations.AlterField(
            model_name='chargesbailleur',
            name='statut',
            field=models.CharField(choices=[('en_attente', 'En attente'), ('payee', 'Payée'), ('remboursee', 'Remboursée'), ('annulee', 'Annulée')], default='en_attente', max_length=20, verbose_name='Statut'),
        ),
        migrations.AlterField(
            model_name='chargesbailleur',
            name='titre',
            field=models.CharField(max_length=200, verbose_name='Titre'),
        ),
        migrations.AlterField(
            model_name='chargesbailleur',
            name='type_charge',
            field=models.CharField(choices=[('reparation', 'Réparation'), ('entretien', 'Entretien'), ('assurance', 'Assurance'), ('taxe', 'Taxe'), ('syndic', 'Syndic'), ('travaux', 'Travaux'), ('autre', 'Autre')], max_length=20, verbose_name='Type de charge'),
        ),
        migrations.AlterField(
            model_name='locataire',
            name='numero_locataire',
            field=models.CharField(default='LT0001', help_text='Identifiant unique du locataire', max_length=20, unique=True, verbose_name='Numéro locataire'),
        ),
        migrations.AlterField(
            model_name='propriete',
            name='bailleur',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='proprietes.bailleur', verbose_name='Bailleur'),
        ),
        migrations.AlterField(
            model_name='propriete',
            name='charges_locataire',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Charges locataire'),
        ),
        migrations.AlterField(
            model_name='propriete',
            name='cree_par',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Créé par'),
        ),
        migrations.AlterField(
            model_name='propriete',
            name='etat',
            field=models.CharField(choices=[('excellent', 'Excellent'), ('tres_bon', 'Très bon'), ('bon', 'Bon'), ('moyen', 'Moyen'), ('a_renover', 'À rénover')], default='bon', max_length=20, verbose_name='État'),
        ),
        migrations.AlterField(
            model_name='propriete',
            name='loyer_actuel',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Loyer mensuel'),
        ),
        migrations.AlterField(
            model_name='propriete',
            name='nombre_chambres',
            field=models.PositiveIntegerField(verbose_name='Nombre de chambres'),
        ),
        migrations.AlterField(
            model_name='propriete',
            name='nombre_salles_bain',
            field=models.PositiveIntegerField(verbose_name='Nombre de salles de bain'),
        ),
        migrations.AlterField(
            model_name='propriete',
            name='numero_propriete',
            field=models.CharField(default='PR0001', help_text='Identifiant unique de la propriété', max_length=20, unique=True, verbose_name='Numéro propriété'),
        ),
        migrations.AlterField(
            model_name='typebien',
            name='nom',
            field=models.CharField(max_length=100, verbose_name='Nom'),
        ),
        migrations.RemoveField(
            model_name='bailleur',
            name='cree_par',
        ),
        migrations.RemoveField(
            model_name='bailleur',
            name='deleted_at',
        ),
        migrations.RemoveField(
            model_name='bailleur',
            name='deleted_by',
        ),
        migrations.RemoveField(
            model_name='bailleur',
            name='entreprise',
        ),
        migrations.RemoveField(
            model_name='bailleur',
            name='is_deleted',
        ),
        migrations.RemoveField(
            model_name='bailleur',
            name='notes',
        ),
        migrations.RemoveField(
            model_name='bailleur',
            name='profession',
        ),
        migrations.RemoveField(
            model_name='locataire',
            name='adresse_actuelle',
        ),
        migrations.RemoveField(
            model_name='locataire',
            name='bic',
        ),
        migrations.RemoveField(
            model_name='locataire',
            name='code_locataire',
        ),
        migrations.RemoveField(
            model_name='locataire',
            name='cree_par',
        ),
        migrations.RemoveField(
            model_name='locataire',
            name='deleted_at',
        ),
        migrations.RemoveField(
            model_name='locataire',
            name='deleted_by',
        ),
        migrations.RemoveField(
            model_name='locataire',
            name='est_actif',
        ),
        migrations.RemoveField(
            model_name='locataire',
            name='iban',
        ),
        migrations.RemoveField(
            model_name='locataire',
            name='is_deleted',
        ),
        migrations.RemoveField(
            model_name='locataire',
            name='notes',
        ),
        migrations.RemoveField(
            model_name='locataire',
            name='salaire_mensuel',
        ),
    ]
