# Generated by Django 5.2.4 on 2025-08-20 13:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proprietes', '0009_alter_chargesbailleur_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=200, verbose_name='Nom du document')),
                ('type_document', models.CharField(choices=[('contrat', 'Contrat de bail'), ('etat_lieux', 'État des lieux'), ('quittance', 'Quittance de loyer'), ('facture', 'Facture'), ('devis', 'Devis'), ('assurance', 'Assurance'), ('diagnostic', 'Diagnostic'), ('justificatif', 'Justificatif'), ('courrier', 'Courrier'), ('autre', 'Autre')], max_length=20, verbose_name='Type de document')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('fichier', models.FileField(help_text='Formats acceptés: PDF, DOC, DOCX, JPG, PNG', upload_to='documents/', verbose_name='Fichier')),
                ('taille_fichier', models.PositiveIntegerField(blank=True, null=True, verbose_name='Taille du fichier (bytes)')),
                ('statut', models.CharField(choices=[('brouillon', 'Brouillon'), ('en_attente', 'En attente'), ('valide', 'Validé'), ('archive', 'Archivé'), ('expire', 'Expiré')], default='brouillon', max_length=20, verbose_name='Statut')),
                ('date_creation', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
                ('date_modification', models.DateTimeField(auto_now=True, verbose_name='Date de modification')),
                ('date_expiration', models.DateField(blank=True, null=True, verbose_name="Date d'expiration")),
                ('tags', models.CharField(blank=True, help_text='Mots-clés séparés par des virgules', max_length=200, verbose_name='Tags')),
                ('confidentiel', models.BooleanField(default=False, verbose_name='Document confidentiel')),
                ('bailleur', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='proprietes.bailleur', verbose_name='Bailleur')),
                ('cree_par', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='documents_proprietes', to=settings.AUTH_USER_MODEL, verbose_name='Créé par')),
                ('locataire', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='proprietes.locataire', verbose_name='Locataire')),
                ('propriete', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='proprietes.propriete', verbose_name='Propriété')),
            ],
            options={
                'verbose_name': 'Document',
                'verbose_name_plural': 'Documents',
                'ordering': ['-date_creation'],
            },
        ),
    ]
