# Generated by Django 5.2.4 on 2025-08-20 20:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proprietes', '0010_document'),
    ]

    operations = [
        migrations.AddField(
            model_name='bailleur',
            name='is_deleted',
            field=models.BooleanField(default=False, verbose_name='Supprimé logiquement'),
        ),
        migrations.AddField(
            model_name='locataire',
            name='is_deleted',
            field=models.BooleanField(default=False, verbose_name='Supprimé logiquement'),
        ),
        migrations.AddField(
            model_name='propriete',
            name='is_deleted',
            field=models.BooleanField(default=False, verbose_name='Supprimé logiquement'),
        ),
    ]
