# Generated by Django 5.2.4 on 2025-08-20 21:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proprietes', '0012_document_is_deleted'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bailleur',
            name='adresse',
            field=models.TextField(blank=True, null=True, verbose_name='Adresse'),
        ),
        migrations.AlterField(
            model_name='bailleur',
            name='code_postal',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='Code postal'),
        ),
        migrations.AlterField(
            model_name='bailleur',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True, verbose_name='Email'),
        ),
        migrations.AlterField(
            model_name='bailleur',
            name='pays',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Pays'),
        ),
        migrations.AlterField(
            model_name='bailleur',
            name='ville',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Ville'),
        ),
        migrations.AlterField(
            model_name='locataire',
            name='adresse',
            field=models.TextField(blank=True, null=True, verbose_name='Adresse'),
        ),
        migrations.AlterField(
            model_name='locataire',
            name='code_postal',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='Code postal'),
        ),
        migrations.AlterField(
            model_name='locataire',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True, verbose_name='Email'),
        ),
        migrations.AlterField(
            model_name='locataire',
            name='pays',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Pays'),
        ),
        migrations.AlterField(
            model_name='locataire',
            name='ville',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Ville'),
        ),
        migrations.AlterField(
            model_name='propriete',
            name='adresse',
            field=models.TextField(blank=True, null=True, verbose_name='Adresse'),
        ),
        migrations.AlterField(
            model_name='propriete',
            name='code_postal',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='Code postal'),
        ),
        migrations.AlterField(
            model_name='propriete',
            name='pays',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Pays'),
        ),
        migrations.AlterField(
            model_name='propriete',
            name='ville',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Ville'),
        ),
    ]
