# Generated by Django 5.2.4 on 2025-01-27 10:00

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proprietes', '0013_alter_bailleur_adresse_alter_bailleur_code_postal_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        # Ajouter les nouveaux champs au modèle ChargesBailleur
        migrations.AddField(
            model_name='chargesbailleur',
            name='montant_deja_deduit',
            field=models.DecimalField(
                decimal_places=2,
                default=0,
                max_digits=10,
                verbose_name='Montant déjà déduit des retraits'
            ),
        ),
        migrations.AddField(
            model_name='chargesbailleur',
            name='montant_restant',
            field=models.DecimalField(
                decimal_places=2,
                default=0,
                max_digits=10,
                verbose_name='Montant restant à déduire'
            ),
        ),
        
        # Modifier le statut par défaut
        migrations.AlterField(
            model_name='chargesbailleur',
            name='statut',
            field=models.CharField(
                choices=[
                    ('en_attente', 'En attente'),
                    ('payee', 'Payée'),
                    ('remboursee', 'Remboursée'),
                    ('deduite_retrait', 'Déduite du retrait mensuel'),
                    ('annulee', 'Annulée'),
                ],
                default='en_attente',
                max_length=20,
                verbose_name='Statut'
            ),
        ),
        
        # Créer le modèle de liaison ChargesBailleurRetrait
        migrations.CreateModel(
            name='ChargesBailleurRetrait',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('montant_deduit', models.DecimalField(
                    decimal_places=2,
                    max_digits=10,
                    verbose_name='Montant déduit de ce retrait'
                )),
                ('date_deduction', models.DateTimeField(auto_now_add=True, verbose_name='Date de la déduction')),
                ('notes', models.TextField(blank=True, verbose_name='Notes sur la déduction')),
                ('charge_bailleur', models.ForeignKey(
                    on_delete=django.db.models.deletion.CASCADE,
                    related_name='retraits_lies',
                    to='proprietes.chargesbailleur',
                    verbose_name='Charge bailleur'
                )),
                ('retrait_bailleur', models.ForeignKey(
                    on_delete=django.db.models.deletion.CASCADE,
                    related_name='charges_bailleur_liees',
                    to='paiements.retraitbailleur',
                    verbose_name='Retrait bailleur'
                )),
            ],
            options={
                'verbose_name': 'Liaison charge bailleur - retrait',
                'verbose_name_plural': 'Liaisons charges bailleur - retraits',
                'ordering': ['-date_deduction'],
                'unique_together': {('charge_bailleur', 'retrait_bailleur')},
            },
        ),
    ]
