# Generated by Django 5.2.5 on 2025-08-23 11:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contrats', '0004_alter_contrat_avance_loyer_and_more'),
        ('proprietes', '0014_charges_bailleur_retrait'),
    ]

    operations = [
        migrations.AlterField(
            model_name='propriete',
            name='bailleur',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='proprietes', to='proprietes.bailleur', verbose_name='Bailleur'),
        ),
        migrations.CreateModel(
            name='Piece',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100, verbose_name='Nom de la pièce')),
                ('type_piece', models.CharField(choices=[('chambre', 'Chambre'), ('salon', 'Salon'), ('cuisine', 'Cuisine'), ('salle_bain', 'Salle de bain'), ('toilettes', 'Toilettes'), ('couloir', 'Couloir'), ('balcon', 'Balcon'), ('terrasse', 'Terrasse'), ('jardin', 'Jardin'), ('parking', 'Parking'), ('cave', 'Cave'), ('grenier', 'Grenier'), ('autre', 'Autre')], max_length=20, verbose_name='Type de pièce')),
                ('surface', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True, verbose_name='Surface (m²)')),
                ('numero_piece', models.CharField(blank=True, max_length=10, verbose_name='Numéro de pièce')),
                ('statut', models.CharField(choices=[('disponible', 'Disponible'), ('occupee', 'Occupée'), ('en_renovation', 'En rénovation'), ('hors_service', 'Hors service')], default='disponible', max_length=20, verbose_name='Statut')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('date_creation', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
                ('date_modification', models.DateTimeField(auto_now=True, verbose_name='Date de modification')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='Supprimé logiquement')),
                ('propriete', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pieces', to='proprietes.propriete', verbose_name='Propriété')),
            ],
            options={
                'verbose_name': 'Pièce',
                'verbose_name_plural': 'Pièces',
                'ordering': ['propriete', 'type_piece', 'numero_piece'],
                'unique_together': {('propriete', 'numero_piece')},
            },
        ),
        migrations.CreateModel(
            name='PieceContrat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('loyer_piece', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Loyer spécifique à la pièce')),
                ('charges_piece', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Charges spécifiques à la pièce')),
                ('date_debut_occupation', models.DateField(verbose_name="Date de début d'occupation")),
                ('date_fin_occupation', models.DateField(blank=True, null=True, verbose_name="Date de fin d'occupation")),
                ('actif', models.BooleanField(default=True, verbose_name='Actif')),
                ('date_creation', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
                ('date_modification', models.DateTimeField(auto_now=True, verbose_name='Date de modification')),
                ('contrat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pieces_contrat', to='contrats.contrat', verbose_name='Contrat')),
                ('piece', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contrats_pieces', to='proprietes.piece', verbose_name='Pièce')),
            ],
            options={
                'verbose_name': 'Pièce-Contrat',
                'verbose_name_plural': 'Pièces-Contrats',
                'ordering': ['-date_creation'],
                'unique_together': {('piece', 'contrat')},
            },
        ),
    ]
