# Generated by Django 5.2.5 on 2025-09-04 09:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proprietes', '0019_add_bailleur_to_unite'),
    ]

    operations = [
        migrations.AddField(
            model_name='piece',
            name='cout_acces_mensuel',
            field=models.DecimalField(decimal_places=2, default=0, help_text="Coût mensuel pour l'accès à cet espace partagé (si applicable)", max_digits=8, verbose_name="Coût d'accès mensuel"),
        ),
        migrations.AddField(
            model_name='piece',
            name='est_espace_partage',
            field=models.BooleanField(default=False, help_text='Cochez si cette pièce est un espace partagé (cuisine, salon commun, etc.)', verbose_name='Espace partagé'),
        ),
        migrations.CreateModel(
            name='AccesEspacePartage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('acces_inclus', models.BooleanField(default=True, help_text="L'accès à cet espace est-il inclus dans le loyer de la pièce ?", verbose_name='Accès inclus')),
                ('cout_supplementaire', models.DecimalField(decimal_places=2, default=0, help_text="Coût supplémentaire mensuel pour l'accès (si non inclus)", max_digits=8, verbose_name='Coût supplémentaire mensuel')),
                ('heures_acces_debut', models.TimeField(blank=True, help_text="Heure de début d'accès autorisé (optionnel)", null=True, verbose_name="Heure de début d'accès")),
                ('heures_acces_fin', models.TimeField(blank=True, help_text="Heure de fin d'accès autorisé (optionnel)", null=True, verbose_name="Heure de fin d'accès")),
                ('jours_acces', models.CharField(blank=True, help_text='Jours de la semaine autorisés (ex: Lun-Ven, Weekend, etc.)', max_length=50, verbose_name="Jours d'accès")),
                ('date_debut_acces', models.DateField(verbose_name="Date de début d'accès")),
                ('date_fin_acces', models.DateField(blank=True, null=True, verbose_name="Date de fin d'accès")),
                ('actif', models.BooleanField(default=True, verbose_name='Actif')),
                ('date_creation', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
                ('date_modification', models.DateTimeField(auto_now=True, verbose_name='Date de modification')),
                ('espace_partage', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='acces_depuis_pieces', to='proprietes.piece', verbose_name='Espace partagé')),
                ('piece_privee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='acces_espaces_partages', to='proprietes.piece', verbose_name='Pièce privée')),
            ],
            options={
                'verbose_name': 'Accès espace partagé',
                'verbose_name_plural': 'Accès espaces partagés',
                'ordering': ['-date_creation'],
                'unique_together': {('piece_privee', 'espace_partage')},
            },
        ),
        migrations.AddField(
            model_name='piece',
            name='acces_inclus_dans_pieces',
            field=models.ManyToManyField(blank=True, help_text='Pièces qui ont accès à cet espace partagé', related_name='espaces_partages_accessibles', through='proprietes.AccesEspacePartage', to='proprietes.piece', verbose_name='Accès depuis les pièces'),
        ),
        migrations.CreateModel(
            name='ChargeCommune',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100, verbose_name='Nom de la charge')),
                ('type_charge', models.CharField(choices=[('electricite', 'Électricité'), ('eau', 'Eau'), ('gaz', 'Gaz'), ('internet', 'Internet'), ('entretien', 'Entretien'), ('assurance', 'Assurance'), ('taxes', 'Taxes'), ('gardiennage', 'Gardiennage'), ('nettoyage', 'Nettoyage'), ('autre', 'Autre')], max_length=20, verbose_name='Type de charge')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('montant_mensuel', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Montant mensuel total')),
                ('type_repartition', models.CharField(choices=[('surface', 'Répartition par surface'), ('nb_occupants', "Répartition par nombre d'occupants"), ('equipartition', 'Répartition équitable'), ('personnalisee', 'Répartition personnalisée')], default='equipartition', max_length=20, verbose_name='Type de répartition')),
                ('date_debut', models.DateField(verbose_name='Date de début')),
                ('date_fin', models.DateField(blank=True, null=True, verbose_name='Date de fin')),
                ('active', models.BooleanField(default=True, verbose_name='Active')),
                ('date_creation', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
                ('date_modification', models.DateTimeField(auto_now=True, verbose_name='Date de modification')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='Supprimé logiquement')),
                ('propriete', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='charges_communes', to='proprietes.propriete', verbose_name='Propriété')),
            ],
            options={
                'verbose_name': 'Charge commune',
                'verbose_name_plural': 'Charges communes',
                'ordering': ['-date_creation'],
            },
        ),
        migrations.CreateModel(
            name='RepartitionChargeCommune',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('montant_calcule', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Montant calculé')),
                ('montant_ajuste', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Montant ajusté manuellement')),
                ('mois', models.PositiveIntegerField(verbose_name='Mois')),
                ('annee', models.PositiveIntegerField(verbose_name='Année')),
                ('base_calcul', models.CharField(max_length=100, verbose_name='Base de calcul')),
                ('date_calcul', models.DateTimeField(auto_now_add=True, verbose_name='Date de calcul')),
                ('applique', models.BooleanField(default=False, verbose_name='Appliqué au contrat')),
                ('date_application', models.DateTimeField(blank=True, null=True, verbose_name="Date d'application")),
                ('charge_commune', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='repartitions', to='proprietes.chargecommune', verbose_name='Charge commune')),
                ('piece_contrat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='charges_communes_reparties', to='proprietes.piececontrat', verbose_name='Pièce-Contrat')),
            ],
            options={
                'verbose_name': 'Répartition charge commune',
                'verbose_name_plural': 'Répartitions charges communes',
                'ordering': ['-annee', '-mois'],
                'unique_together': {('charge_commune', 'piece_contrat', 'mois', 'annee')},
            },
        ),
    ]
