# Generated by Django 4.2.24 on 2025-09-18 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proprietes', '0022_add_type_gestion_to_propriete'),
    ]

    operations = [
        migrations.AlterField(
            model_name='propriete',
            name='loyer_actuel',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=10, null=True, verbose_name='Loyer mensuel'),
        ),
    ]
