# Generated by Django 4.2.24 on 2025-09-18 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proprietes', '0023_alter_propriete_loyer_actuel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='propriete',
            name='nombre_chambres',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Nombre de chambres'),
        ),
        migrations.AlterField(
            model_name='propriete',
            name='nombre_pieces',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Nombre de pièces'),
        ),
        migrations.AlterField(
            model_name='propriete',
            name='nombre_salles_bain',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Nombre de salles de bain'),
        ),
    ]
