# Generated by Django 4.2.24 on 2025-09-18 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proprietes', '0024_alter_propriete_nombre_chambres_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='propriete',
            name='cuisine',
            field=models.BooleanField(default=False, verbose_name='Cuisine'),
        ),
    ]
