# Generated by Django 4.2.24 on 2025-09-27 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proprietes', '0026_alter_propriete_numero_propriete'),
    ]

    operations = [
        migrations.AlterField(
            model_name='locataire',
            name='civilite',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Civilité'),
        ),
        migrations.AlterField(
            model_name='locataire',
            name='garant_civilite',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Civilité du garant'),
        ),
    ]
