# Generated by Django 4.2.24 on 2025-10-23 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proprietes', '0030_fix_telephone_length'),
    ]

    operations = [
        migrations.AddField(
            model_name='propriete',
            name='quartier',
            field=models.CharField(blank=True, help_text='Quartier ou secteur où se trouve la propriété (très important pour la localisation)', max_length=100, null=True, verbose_name='Quartier'),
        ),
    ]
