# Generated by Django 4.2.24 on 2025-10-24 19:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proprietes', '0031_propriete_quartier'),
    ]

    operations = [
        migrations.AddField(
            model_name='locataire',
            name='type_personne',
            field=models.CharField(choices=[('physique', 'Personne physique'), ('societe', 'Société/Personne morale')], default='physique', max_length=20, verbose_name='Type de personne'),
        ),
        migrations.AlterField(
            model_name='locataire',
            name='civilite',
            field=models.CharField(blank=True, choices=[('M', 'Monsieur'), ('Mme', 'Madame'), ('Mlle', 'Mademoiselle'), ('Mademoiselle', 'Mademoiselle'), ('Societe', 'Société')], max_length=50, null=True, verbose_name='Civilité'),
        ),
        migrations.AlterField(
            model_name='propriete',
            name='quartier',
            field=models.CharField(blank=True, default='', help_text='Quartier ou secteur où se trouve la propriété (très important pour la localisation)', max_length=100, null=True, verbose_name='Quartier'),
        ),
    ]
