# Generated by Django 4.2.24 on 2025-10-25 06:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proprietes', '0032_locataire_type_personne_alter_locataire_civilite_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='locataire',
            name='prenom',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Prénom'),
        ),
    ]
