# Generated by Django 4.2.24 on 2025-10-25 06:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proprietes', '0033_make_prenom_optional'),
    ]

    operations = [
        migrations.AddField(
            model_name='locataire',
            name='numero_cnib',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Numéro CNIB/CNI'),
        ),
        migrations.AddField(
            model_name='propriete',
            name='numero_maison',
            field=models.CharField(blank=True, help_text='Numéro de la maison (ex: 123, A15, etc.)', max_length=20, null=True, verbose_name='Numéro de maison'),
        ),
    ]
