# Generated by Django 4.2.24 on 2025-10-25 06:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('proprietes', '0034_add_missing_contract_fields'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='propriete',
            name='numero_maison',
        ),
    ]
