# Generated by Django 4.2.24 on 2025-10-26 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proprietes', '0035_remove_numero_maison_field'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chargesbailleur',
            name='numero_charge',
            field=models.CharField(blank=True, help_text='Identifiant unique de la charge', max_length=50, unique=True, verbose_name='Numéro de charge'),
        ),
    ]
