# Generated by Django 4.2.24 on 2025-11-06 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proprietes', '0036_fix_charges_bailleur_numero_unique'),
    ]

    operations = [
        migrations.AlterField(
            model_name='locataire',
            name='civilite',
            field=models.CharField(blank=True, choices=[('M', 'Monsieur'), ('Mme', 'Madame'), ('Mlle', 'Mademoiselle'), ('Societe', 'Société')], max_length=50, null=True, verbose_name='Civilité'),
        ),
        migrations.AlterField(
            model_name='locataire',
            name='garant_civilite',
            field=models.CharField(blank=True, choices=[('M', 'Monsieur'), ('Mme', 'Madame'), ('Mlle', 'Mademoiselle'), ('Societe', 'Société')], max_length=50, null=True, verbose_name='Civilité du garant'),
        ),
    ]
