# Generated by Django 4.2.24 on 2025-11-26 15:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('proprietes', '0037_alter_locataire_civilite_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContratGestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_contrat', models.CharField(help_text='Numéro unique du contrat de gestion', max_length=50, unique=True, verbose_name='Numéro de contrat')),
                ('date_signature', models.DateField(default=django.utils.timezone.now, verbose_name='Date de signature')),
                ('date_debut', models.DateField(help_text='Date de début de la gestion', verbose_name='Date de début')),
                ('date_fin', models.DateField(blank=True, help_text='Date de fin de la gestion (optionnel)', null=True, verbose_name='Date de fin')),
                ('commission_percentage', models.DecimalField(decimal_places=2, default=10.0, help_text='Pourcentage de commission sur les loyers', max_digits=5, verbose_name='Commission (%)')),
                ('est_actif', models.BooleanField(default=True, verbose_name='Contrat actif')),
                ('est_resilie', models.BooleanField(default=False, verbose_name='Contrat résilié')),
                ('notes', models.TextField(blank=True, help_text='Notes additionnelles sur le contrat', verbose_name='Notes')),
                ('date_creation', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
                ('date_modification', models.DateTimeField(auto_now=True, verbose_name='Date de modification')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='Supprimé logiquement')),
                ('bailleur', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='contrats_gestion', to='proprietes.bailleur', verbose_name='Bailleur')),
                ('cree_par', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Créé par')),
                ('proprietes', models.ManyToManyField(help_text='Propriétés confiées en gestion', related_name='contrats_gestion', to='proprietes.propriete', verbose_name='Propriétés')),
            ],
            options={
                'verbose_name': 'Contrat de gestion',
                'verbose_name_plural': 'Contrats de gestion',
                'ordering': ['-date_signature'],
            },
        ),
    ]
