# Generated by Django 4.2.7 on 2025-07-19 19:24

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('proprietes', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('contrats', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CompteBancaire',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100, verbose_name='Nom du compte')),
                ('banque', models.CharField(max_length=100, verbose_name='Banque')),
                ('iban', models.CharField(max_length=34, verbose_name='IBAN')),
                ('bic', models.CharField(max_length=11, verbose_name='BIC')),
                ('solde_actuel', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Solde actuel')),
                ('devise', models.CharField(default='EUR', max_length=3, verbose_name='Devise')),
                ('est_actif', models.BooleanField(default=True, verbose_name='Compte actif')),
                ('date_creation', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
                ('date_modification', models.DateTimeField(auto_now=True, verbose_name='Date de modification')),
                ('notes', models.TextField(blank=True, verbose_name='Notes')),
            ],
            options={
                'verbose_name': 'Compte bancaire',
                'verbose_name_plural': 'Comptes bancaires',
                'ordering': ['nom'],
            },
        ),
        migrations.CreateModel(
            name='Paiement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('montant', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0.01)], verbose_name='Montant')),
                ('type_paiement', models.CharField(choices=[('loyer', 'Loyer'), ('charges', 'Charges'), ('depot_garantie', 'Dépôt de garantie'), ('regularisation', 'Régularisation'), ('autre', 'Autre')], default='loyer', max_length=20, verbose_name='Type de paiement')),
                ('statut', models.CharField(choices=[('en_attente', 'En attente'), ('valide', 'Validé'), ('refuse', 'Refusé'), ('annule', 'Annulé')], default='en_attente', max_length=20, verbose_name='Statut')),
                ('mode_paiement', models.CharField(choices=[('virement', 'Virement bancaire'), ('cheque', 'Chèque'), ('especes', 'Espèces'), ('prelevement', 'Prélèvement automatique'), ('carte', 'Carte bancaire')], max_length=20, verbose_name='Mode de paiement')),
                ('date_paiement', models.DateField(verbose_name='Date de paiement')),
                ('date_encaissement', models.DateField(blank=True, null=True, verbose_name="Date d'encaissement")),
                ('numero_cheque', models.CharField(blank=True, max_length=50, verbose_name='Numéro de chèque')),
                ('reference_virement', models.CharField(blank=True, max_length=100, verbose_name='Référence virement')),
                ('date_creation', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
                ('date_modification', models.DateTimeField(auto_now=True, verbose_name='Date de modification')),
                ('notes', models.TextField(blank=True, verbose_name='Notes')),
                ('contrat', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='paiements', to='contrats.contrat', verbose_name='Contrat')),
                ('cree_par', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='paiements_crees', to=settings.AUTH_USER_MODEL, verbose_name='Créé par')),
                ('valide_par', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='paiements_valides', to=settings.AUTH_USER_MODEL, verbose_name='Validé par')),
            ],
            options={
                'verbose_name': 'Paiement',
                'verbose_name_plural': 'Paiements',
                'ordering': ['-date_paiement'],
            },
        ),
        migrations.CreateModel(
            name='Retrait',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('montant', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0.01)], verbose_name='Montant')),
                ('type_retrait', models.CharField(choices=[('loyers', 'Loyers'), ('charges', 'Charges'), ('depot_garantie', 'Dépôt de garantie'), ('frais_agence', "Frais d'agence"), ('autre', 'Autre')], default='loyers', max_length=20, verbose_name='Type de retrait')),
                ('statut', models.CharField(choices=[('en_attente', 'En attente'), ('valide', 'Validé'), ('annule', 'Annulé')], default='en_attente', max_length=20, verbose_name='Statut')),
                ('mode_retrait', models.CharField(choices=[('virement', 'Virement bancaire'), ('cheque', 'Chèque'), ('especes', 'Espèces')], max_length=20, verbose_name='Mode de retrait')),
                ('date_demande', models.DateField(verbose_name='Date de demande')),
                ('date_versement', models.DateField(blank=True, null=True, verbose_name='Date de versement')),
                ('numero_cheque', models.CharField(blank=True, max_length=50, verbose_name='Numéro de chèque')),
                ('reference_virement', models.CharField(blank=True, max_length=100, verbose_name='Référence virement')),
                ('date_creation', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
                ('date_modification', models.DateTimeField(auto_now=True, verbose_name='Date de modification')),
                ('notes', models.TextField(blank=True, verbose_name='Notes')),
                ('bailleur', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='retraits', to='proprietes.bailleur', verbose_name='Bailleur')),
                ('cree_par', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='retraits_crees', to=settings.AUTH_USER_MODEL, verbose_name='Créé par')),
                ('valide_par', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='retraits_valides', to=settings.AUTH_USER_MODEL, verbose_name='Validé par')),
            ],
            options={
                'verbose_name': 'Retrait',
                'verbose_name_plural': 'Retraits',
                'ordering': ['-date_demande'],
            },
        ),
        migrations.CreateModel(
            name='Recu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_recu', models.CharField(max_length=50, unique=True, verbose_name='Numéro de reçu')),
                ('date_emission', models.DateTimeField(auto_now_add=True, verbose_name="Date d'émission")),
                ('imprime', models.BooleanField(default=False, verbose_name='Imprimé')),
                ('date_impression', models.DateTimeField(blank=True, null=True, verbose_name="Date d'impression")),
                ('imprime_par', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recus_imprimes', to=settings.AUTH_USER_MODEL, verbose_name='Imprimé par')),
                ('paiement', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='recu', to='paiements.paiement', verbose_name='Paiement')),
            ],
            options={
                'verbose_name': 'Reçu',
                'verbose_name_plural': 'Reçus',
                'ordering': ['-date_emission'],
            },
        ),
    ]
