# Generated by Django 4.2.7 on 2025-07-20 12:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('paiements', '0002_recu_date_envoi_email_recu_envoye_email_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='recu',
            name='date_validation',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Date de validation'),
        ),
        migrations.AddField(
            model_name='recu',
            name='email_destinataire',
            field=models.EmailField(blank=True, max_length=254, verbose_name='Email destinataire'),
        ),
        migrations.AddField(
            model_name='recu',
            name='format_impression',
            field=models.CharField(choices=[('a4', 'A4'), ('a5', 'A5'), ('lettre', 'Lettre'), ('recu', 'Format reçu')], default='a4', max_length=20, verbose_name="Format d'impression"),
        ),
        migrations.AddField(
            model_name='recu',
            name='nombre_emails',
            field=models.PositiveIntegerField(default=0, verbose_name="Nombre d'emails envoyés"),
        ),
        migrations.AddField(
            model_name='recu',
            name='nombre_impressions',
            field=models.PositiveIntegerField(default=0, verbose_name="Nombre d'impressions"),
        ),
        migrations.AddField(
            model_name='recu',
            name='notes_internes',
            field=models.TextField(blank=True, verbose_name='Notes internes'),
        ),
        migrations.AddField(
            model_name='recu',
            name='options_impression',
            field=models.JSONField(blank=True, default=dict, verbose_name="Options d'impression"),
        ),
        migrations.AddField(
            model_name='recu',
            name='valide',
            field=models.BooleanField(default=True, verbose_name='Reçu validé'),
        ),
        migrations.AddField(
            model_name='recu',
            name='valide_par',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recus_valides', to=settings.AUTH_USER_MODEL, verbose_name='Validé par'),
        ),
        migrations.AddField(
            model_name='recu',
            name='version_template',
            field=models.CharField(default='1.0', max_length=10, verbose_name='Version du template'),
        ),
        migrations.AlterField(
            model_name='recu',
            name='template_utilise',
            field=models.CharField(choices=[('standard', 'Standard'), ('professionnel', 'Professionnel'), ('simplifie', 'Simplifié'), ('luxe', 'Luxe'), ('entreprise', 'Entreprise')], default='standard', max_length=50, verbose_name='Template utilisé'),
        ),
        migrations.AddIndex(
            model_name='recu',
            index=models.Index(fields=['numero_recu'], name='paiements_r_numero__2a4ff1_idx'),
        ),
        migrations.AddIndex(
            model_name='recu',
            index=models.Index(fields=['date_emission'], name='paiements_r_date_em_d558d9_idx'),
        ),
        migrations.AddIndex(
            model_name='recu',
            index=models.Index(fields=['imprime'], name='paiements_r_imprime_747ade_idx'),
        ),
        migrations.AddIndex(
            model_name='recu',
            index=models.Index(fields=['valide'], name='paiements_r_valide_e5db39_idx'),
        ),
    ]
