# Generated by Django 5.2.4 on 2025-08-20 07:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paiements', '0007_add_reference_paiement'),
    ]

    operations = [
        migrations.AddField(
            model_name='paiement',
            name='numero_paiement',
            field=models.CharField(blank=True, help_text='Numéro unique professionnel du paiement', max_length=50, null=True, unique=True, verbose_name='Numéro Paiement'),
        ),
    ]
