# Generated by Django 5.2.4 on 2025-08-21 07:08

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contrats', '0004_alter_contrat_avance_loyer_and_more'),
        ('paiements', '0009_tableaubordfinancier'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PaiementCautionAvance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_paiement', models.CharField(choices=[('caution', 'Caution'), ('avance_loyer', 'Avance de loyer'), ('caution_et_avance', 'Caution et avance')], max_length=20, verbose_name='Type de paiement')),
                ('montant_caution', models.DecimalField(decimal_places=2, default=0.0, max_digits=10, validators=[django.core.validators.MinValueValidator(0.0)], verbose_name='Montant de la caution')),
                ('montant_avance', models.DecimalField(decimal_places=2, default=0.0, max_digits=10, validators=[django.core.validators.MinValueValidator(0.0)], verbose_name="Montant de l'avance")),
                ('montant_total', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0.01)], verbose_name='Montant total')),
                ('mode_paiement', models.CharField(choices=[('virement', 'Virement bancaire'), ('cheque', 'Chèque'), ('especes', 'Espèces'), ('mobile_money', 'Mobile Money'), ('carte_bancaire', 'Carte bancaire'), ('autre', 'Autre')], max_length=20, verbose_name='Mode de paiement')),
                ('reference_paiement', models.CharField(blank=True, max_length=100, verbose_name='Référence de paiement')),
                ('numero_cheque', models.CharField(blank=True, max_length=50, verbose_name='Numéro de chèque')),
                ('banque_emetteur', models.CharField(blank=True, max_length=100, verbose_name='Banque émettrice')),
                ('statut', models.CharField(choices=[('en_attente', 'En attente'), ('valide', 'Validé'), ('rejete', 'Rejeté'), ('annule', 'Annulé')], default='en_attente', max_length=20, verbose_name='Statut')),
                ('date_paiement', models.DateField(verbose_name='Date de paiement')),
                ('date_validation', models.DateField(blank=True, null=True, verbose_name='Date de validation')),
                ('date_creation', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
                ('date_modification', models.DateTimeField(auto_now=True, verbose_name='Date de modification')),
                ('nom_payeur', models.CharField(max_length=150, verbose_name='Nom du payeur')),
                ('telephone_payeur', models.CharField(blank=True, max_length=20, verbose_name='Téléphone du payeur')),
                ('email_payeur', models.EmailField(blank=True, max_length=254, verbose_name='Email du payeur')),
                ('justificatif_url', models.URLField(blank=True, verbose_name='URL du justificatif')),
                ('recu_genere', models.BooleanField(default=False, verbose_name='Reçu généré')),
                ('numero_recu', models.CharField(blank=True, max_length=50, verbose_name='Numéro de reçu')),
                ('notes', models.TextField(blank=True, verbose_name='Notes et observations')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='Supprimé logiquement')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='Date de suppression')),
                ('contrat', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='paiements_caution_avance', to='contrats.contrat', verbose_name='Contrat')),
                ('cree_par', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='paiements_caution_avance_crees', to=settings.AUTH_USER_MODEL, verbose_name='Créé par')),
                ('deleted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='paiements_caution_avance_deleted', to=settings.AUTH_USER_MODEL, verbose_name='Supprimé par')),
                ('valide_par', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='paiements_caution_avance_valides', to=settings.AUTH_USER_MODEL, verbose_name='Validé par')),
            ],
            options={
                'verbose_name': 'Paiement de caution et avance',
                'verbose_name_plural': 'Paiements de caution et avance',
                'ordering': ['-date_paiement'],
                'unique_together': {('contrat', 'type_paiement', 'date_paiement')},
            },
        ),
    ]
