# Generated by Django 5.2.4 on 2025-08-21 15:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paiements', '0012_remove_chargedeductible_paiements_c_statut_836dc4_idx_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='QuittancePaiement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_quittance', models.CharField(help_text='Numéro unique de la quittance', max_length=50, unique=True, verbose_name='Numéro de quittance')),
                ('date_emission', models.DateTimeField(auto_now_add=True, verbose_name="Date d'émission")),
                ('date_impression', models.DateTimeField(blank=True, null=True, verbose_name="Date d'impression")),
                ('statut', models.CharField(choices=[('generee', 'Générée'), ('imprimee', 'Imprimée'), ('envoyee', 'Envoyée'), ('archivée', 'Archivée')], default='generee', max_length=20, verbose_name='Statut')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='Supprimé logiquement')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='Date de suppression')),
                ('cree_par', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='quittances_crees', to=settings.AUTH_USER_MODEL, verbose_name='Créé par')),
                ('deleted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='quittances_deleted', to=settings.AUTH_USER_MODEL, verbose_name='Supprimé par')),
                ('paiement', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='quittance', to='paiements.paiement', verbose_name='Paiement')),
            ],
            options={
                'verbose_name': 'Quittance de paiement',
                'verbose_name_plural': 'Quittances de paiement',
                'ordering': ['-date_emission'],
            },
        ),
    ]
