# Generated by Django 4.2.24 on 2025-10-19 08:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paiements', '0013_chargebailleur_retraitquittance_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paiement',
            name='type_paiement',
            field=models.CharField(choices=[('loyer', 'Loyer'), ('caution', 'Caution'), ('avance', 'Avance de loyer'), ('charges', 'Charges'), ('regularisation', 'Régularisation'), ('paiement_partiel', 'Paiement partiel'), ('autre', 'Autre')], default='loyer', max_length=20, verbose_name='Type de paiement'),
        ),
    ]
