# Generated by Django 4.2.24 on 2025-10-19 08:30

from django.db import migrations


def update_payment_types(apps, schema_editor):
    """
    Met à jour les types de paiement existants :
    - depot_garantie -> caution
    - avance_loyer -> avance
    """
    Paiement = apps.get_model('paiements', 'Paiement')
    
    # Mettre à jour depot_garantie vers caution
    Paiement.objects.filter(type_paiement='depot_garantie').update(type_paiement='caution')
    
    # Mettre à jour avance_loyer vers avance
    Paiement.objects.filter(type_paiement='avance_loyer').update(type_paiement='avance')


def reverse_update_payment_types(apps, schema_editor):
    """
    Fonction de rollback - ne fait rien car on ne peut pas deviner les types originaux
    """
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('paiements', '0014_remove_depot_garantie_avance_loyer_types'),
    ]

    operations = [
        migrations.RunPython(update_payment_types, reverse_update_payment_types),
    ]
