# Generated by Django 5.2.4 on 2025-08-22 09:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paiements', '0015_retraitbailleur_date_annulation_and_more'),
        ('proprietes', '0013_alter_bailleur_adresse_alter_bailleur_code_postal_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TableauBordFinancier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(help_text='Nom descriptif du tableau de bord', max_length=100, verbose_name='Nom du tableau de bord')),
                ('description', models.TextField(blank=True, help_text='Description détaillée du tableau de bord', verbose_name='Description')),
                ('afficher_revenus', models.BooleanField(default=True, help_text='Inclure les revenus dans le tableau de bord', verbose_name='Afficher les revenus')),
                ('afficher_charges', models.BooleanField(default=True, help_text='Inclure les charges dans le tableau de bord', verbose_name='Afficher les charges')),
                ('afficher_benefices', models.BooleanField(default=True, help_text='Inclure les bénéfices dans le tableau de bord', verbose_name='Afficher les bénéfices')),
                ('afficher_taux_occupation', models.BooleanField(default=True, help_text="Inclure le taux d'occupation dans le tableau de bord", verbose_name="Afficher le taux d'occupation")),
                ('periode', models.CharField(choices=[('mensuel', 'Mensuel'), ('trimestriel', 'Trimestriel'), ('annuel', 'Annuel'), ('personnalise', 'Personnalisé')], default='mensuel', max_length=20, verbose_name="Période d'analyse")),
                ('date_debut_personnalisee', models.DateField(blank=True, null=True, verbose_name='Date de début (période personnalisée)')),
                ('date_fin_personnalisee', models.DateField(blank=True, null=True, verbose_name='Date de fin (période personnalisée)')),
                ('seuil_alerte', models.DecimalField(blank=True, decimal_places=2, help_text='Montant seuil pour déclencher des alertes', max_digits=10, null=True, verbose_name="Seuil d'alerte")),
                ('devise', models.CharField(default='XOF', help_text='Devise utilisée pour les montants', max_length=10, verbose_name='Devise')),
                ('couleur_theme', models.CharField(default='#007bff', help_text='Couleur principale du tableau de bord (format hexadécimal)', max_length=7, verbose_name='Couleur du thème')),
                ('date_creation', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
                ('date_modification', models.DateTimeField(auto_now=True, verbose_name='Date de modification')),
                ('actif', models.BooleanField(default=True, help_text='Désactiver pour masquer ce tableau de bord', verbose_name='Tableau actif')),
                ('bailleurs', models.ManyToManyField(blank=True, help_text='Bailleurs à inclure dans ce tableau de bord', to='proprietes.bailleur', verbose_name='Bailleurs inclus')),
                ('cree_par', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tableaux_bord_crees', to=settings.AUTH_USER_MODEL, verbose_name='Créé par')),
                ('proprietes', models.ManyToManyField(blank=True, help_text='Propriétés à inclure dans ce tableau de bord', to='proprietes.propriete', verbose_name='Propriétés incluses')),
            ],
            options={
                'verbose_name': 'Tableau de bord financier',
                'verbose_name_plural': 'Tableaux de bord financiers',
                'ordering': ['-date_creation'],
                'permissions': [('view_tableau_bord_financier', 'Peut voir les tableaux de bord financiers'), ('add_tableau_bord_financier', 'Peut créer des tableaux de bord financiers'), ('change_tableau_bord_financier', 'Peut modifier les tableaux de bord financiers'), ('delete_tableau_bord_financier', 'Peut supprimer les tableaux de bord financiers')],
            },
        ),
    ]
