# Generated by Django 4.2.24 on 2025-10-19 10:45

from django.db import migrations


def fix_existing_receipts_amounts(apps, schema_editor):
    """
    Corrige les montants des récépissés existants pour les avances.
    Cette migration ne modifie pas les données en base, mais s'assure que
    les récépissés générés utilisent les bons montants.
    """
    Paiement = apps.get_model('paiements', 'Paiement')
    
    # Compter les paiements d'avance qui pourraient avoir des montants incorrects
    paiements_avance = Paiement.objects.filter(type_paiement='avance')
    
    print(f"Migration: {paiements_avance.count()} paiements d'avance trouvés")
    
    # Note: Les corrections sont appliquées au niveau du code (modèles)
    # Cette migration sert principalement à documenter le changement
    print("Les montants des récépissés seront corrigés automatiquement lors de la génération")


def reverse_fix_existing_receipts_amounts(apps, schema_editor):
    """
    Fonction de rollback - ne fait rien car on ne peut pas deviner les montants originaux
    """
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('paiements', '0015_update_payment_types'),
    ]

    operations = [
        migrations.RunPython(fix_existing_receipts_amounts, reverse_fix_existing_receipts_amounts),
    ]
