# Generated by Django 5.2.4 on 2025-08-22 22:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paiements', '0016_add_tableau_bord_financier'),
        ('proprietes', '0013_alter_bailleur_adresse_alter_bailleur_code_postal_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RecapMensuel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mois_recap', models.DateField(help_text='Mois pour lequel le récapitulatif est établi', verbose_name='Mois du récapitulatif')),
                ('total_loyers_bruts', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Total des loyers bruts')),
                ('total_charges_deductibles', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Total des charges déductibles')),
                ('total_net_a_payer', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Total net à payer')),
                ('nombre_proprietes', models.PositiveIntegerField(default=0, verbose_name='Nombre de propriétés')),
                ('nombre_contrats_actifs', models.PositiveIntegerField(default=0, verbose_name='Nombre de contrats actifs')),
                ('nombre_paiements_recus', models.PositiveIntegerField(default=0, verbose_name='Nombre de paiements reçus')),
                ('statut', models.CharField(choices=[('brouillon', 'Brouillon'), ('valide', 'Validé'), ('envoye', 'Envoyé au bailleur'), ('paye', 'Payé au bailleur')], default='brouillon', max_length=20, verbose_name='Statut')),
                ('date_creation', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
                ('date_validation', models.DateTimeField(blank=True, null=True, verbose_name='Date de validation')),
                ('date_envoi', models.DateTimeField(blank=True, null=True, verbose_name="Date d'envoi")),
                ('date_paiement', models.DateTimeField(blank=True, null=True, verbose_name='Date de paiement')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='Supprimé logiquement')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='Date de suppression')),
                ('bailleur', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='recaps_mensuels', to='proprietes.bailleur', verbose_name='Bailleur')),
                ('charges_deductibles', models.ManyToManyField(related_name='recaps_mensuels', to='paiements.chargedeductible', verbose_name='Charges déductibles')),
                ('cree_par', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recaps_mensuels_crees', to=settings.AUTH_USER_MODEL, verbose_name='Créé par')),
                ('deleted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recaps_mensuels_supprimes', to=settings.AUTH_USER_MODEL, verbose_name='Supprimé par')),
                ('paiements_concernes', models.ManyToManyField(related_name='recaps_mensuels', to='paiements.paiement', verbose_name='Paiements concernés')),
                ('retraits_associes', models.ManyToManyField(related_name='recaps_mensuels', to='paiements.retraitbailleur', verbose_name='Retraits associés')),
                ('valide_par', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recaps_mensuels_valides', to=settings.AUTH_USER_MODEL, verbose_name='Validé par')),
            ],
            options={
                'verbose_name': 'Récapitulatif mensuel',
                'verbose_name_plural': 'Récapitulatifs mensuels',
                'ordering': ['-mois_recap'],
                'indexes': [models.Index(fields=['bailleur', 'mois_recap'], name='paiements_r_bailleu_169d13_idx'), models.Index(fields=['statut'], name='paiements_r_statut_e968e9_idx'), models.Index(fields=['date_creation'], name='paiements_r_date_cr_28403c_idx')],
                'unique_together': {('bailleur', 'mois_recap')},
            },
        ),
    ]
