# Generated by Django 4.2.24 on 2025-10-23 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paiements', '0017_add_montant_reste'),
    ]

    operations = [
        migrations.AddField(
            model_name='paiement',
            name='data_extra',
            field=models.JSONField(blank=True, help_text='Données JSON pour les notifications et métadonnées', null=True, verbose_name='Données supplémentaires'),
        ),
    ]
