# Generated by Django 5.2.5 on 2025-08-23 11:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paiements', '0017_recapmensuel'),
        ('proprietes', '0014_charges_bailleur_retrait'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RecapitulatifMensuelBailleur',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mois_recapitulatif', models.DateField(help_text='Mois de référence pour le récapitulatif', verbose_name='Mois du récapitulatif')),
                ('type_recapitulatif', models.CharField(choices=[('mensuel', 'Mensuel'), ('trimestriel', 'Trimestriel'), ('annuel', 'Annuel'), ('exceptionnel', 'Exceptionnel')], default='mensuel', max_length=20, verbose_name='Type de récapitulatif')),
                ('statut', models.CharField(choices=[('en_preparation', 'En préparation'), ('valide', 'Validé'), ('envoye', 'Envoyé au bailleur'), ('paye', 'Payé'), ('annule', 'Annulé')], default='en_preparation', max_length=20, verbose_name='Statut')),
                ('date_creation', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
                ('date_validation', models.DateTimeField(blank=True, null=True, verbose_name='Date de validation')),
                ('date_envoi', models.DateTimeField(blank=True, null=True, verbose_name="Date d'envoi au bailleur")),
                ('date_paiement', models.DateTimeField(blank=True, null=True, verbose_name='Date de paiement')),
                ('notes', models.TextField(blank=True, verbose_name='Notes et observations')),
                ('hash_securite', models.CharField(blank=True, max_length=64, verbose_name='Hash de sécurité')),
                ('version', models.CharField(default='1.0', max_length=10, verbose_name='Version du récapitulatif')),
                ('bailleur', models.ForeignKey(help_text='Bailleur concerné par ce récapitulatif', on_delete=django.db.models.deletion.CASCADE, related_name='recapitulatifs_mensuels_bailleur', to='proprietes.bailleur', verbose_name='Bailleur')),
                ('gestionnaire', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recapitulatifs_crees', to=settings.AUTH_USER_MODEL, verbose_name='Gestionnaire responsable')),
            ],
            options={
                'verbose_name': 'Récapitulatif mensuel',
                'verbose_name_plural': 'Récapitulatifs mensuels',
                'ordering': ['-mois_recapitulatif', '-date_creation'],
                'indexes': [models.Index(fields=['mois_recapitulatif', 'statut'], name='paiements_r_mois_re_1a99f9_idx'), models.Index(fields=['gestionnaire', 'date_creation'], name='paiements_r_gestion_751a82_idx')],
                'unique_together': {('bailleur', 'mois_recapitulatif', 'type_recapitulatif')},
            },
        ),
    ]
