# Generated by Django 4.2.24 on 2025-10-25 12:58

from django.db import migrations, models
import django.db.models.deletion
from django.core.validators import MinValueValidator


class Migration(migrations.Migration):

    dependencies = [
        ('paiements', '0018_paiement_data_extra'),
        ('proprietes', '0035_remove_numero_maison_field'),
        ('utilisateurs', '0014_apply_email_uniqueness'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChargeBailleur',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=200, verbose_name='Description de la charge')),
                ('montant', models.DecimalField(decimal_places=2, max_digits=12, validators=[MinValueValidator(0.01)], verbose_name='Montant de la charge')),
                ('date_charge', models.DateField(verbose_name='Date de la charge')),
                ('mois_charge', models.DateField(help_text="Mois pour lequel cette charge s'applique", verbose_name='Mois de la charge')),
                ('statut', models.CharField(choices=[('en_attente', 'En attente'), ('valide', 'Validé'), ('utilise', 'Utilisé'), ('annule', 'Annulé')], default='en_attente', max_length=20, verbose_name='Statut')),
                ('notes', models.TextField(blank=True, verbose_name='Notes')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Date de modification')),
                ('bailleur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='charges_bailleur', to='proprietes.bailleur', verbose_name='Bailleur')),
                ('cree_par', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='charges_bailleur_crees', to='utilisateurs.utilisateur', verbose_name='Créé par')),
                ('retrait_utilise', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='charges_utilisees', to='paiements.retraitbailleur', verbose_name='Retrait qui a utilisé cette charge')),
            ],
            options={
                'verbose_name': 'Charge Bailleur',
                'verbose_name_plural': 'Charges Bailleur',
                'ordering': ['-date_charge', '-created_at'],
                'app_label': 'paiements',
            },
        ),
    ]
