# Generated by Django 4.2.24 on 2025-10-25 12:58

from django.db import migrations, models
import django.db.models.deletion
from django.core.validators import MinValueValidator


class Migration(migrations.Migration):

    dependencies = [
        ('paiements', '0018_paiement_data_extra'),
        ('proprietes', '0035_remove_numero_maison_field'),
        ('utilisateurs', '0014_apply_email_uniqueness'),
    ]

    operations = [
        migrations.RunSQL(
            # SQL pour créer la table seulement si elle n'existe pas
            sql="""
            CREATE TABLE IF NOT EXISTS paiements_chargebailleur (
                id BIGSERIAL PRIMARY KEY,
                description VARCHAR(200) NOT NULL,
                montant DECIMAL(12,2) NOT NULL CHECK (montant >= 0.01),
                date_charge DATE NOT NULL,
                mois_charge DATE NOT NULL,
                statut VARCHAR(20) NOT NULL DEFAULT 'en_attente',
                notes TEXT,
                created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT NOW(),
                updated_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT NOW(),
                bailleur_id BIGINT NOT NULL REFERENCES proprietes_bailleur(id) ON DELETE CASCADE,
                cree_par_id BIGINT REFERENCES utilisateurs_utilisateur(id) ON DELETE SET NULL,
                retrait_utilise_id BIGINT REFERENCES paiements_retraitbailleur(id) ON DELETE SET NULL
            );
            """,
            reverse_sql="DROP TABLE IF EXISTS paiements_chargebailleur;",
        ),
        # Ajouter les contraintes et index
        migrations.RunSQL(
            sql="""
            ALTER TABLE paiements_chargebailleur 
            ADD CONSTRAINT paiements_chargebailleur_statut_check 
            CHECK (statut IN ('en_attente', 'valide', 'utilise', 'annule'));
            
            CREATE INDEX IF NOT EXISTS paiements_chargebailleur_bailleur_id_idx 
            ON paiements_chargebailleur(bailleur_id);
            
            CREATE INDEX IF NOT EXISTS paiements_chargebailleur_date_charge_idx 
            ON paiements_chargebailleur(date_charge);
            
            CREATE INDEX IF NOT EXISTS paiements_chargebailleur_statut_idx 
            ON paiements_chargebailleur(statut);
            """,
            reverse_sql="",
        ),
    ]
