# Generated by Django 4.2.24 on 2025-10-25 13:36

from django.db import migrations, models
import uuid
from datetime import datetime


def populate_numero_charge(apps, schema_editor):
    """Remplit le champ numero_charge pour les enregistrements existants"""
    ChargeBailleur = apps.get_model('paiements', 'ChargeBailleur')
    
    for charge in ChargeBailleur.objects.filter(numero_charge__isnull=True):
        timestamp = datetime.now().strftime("%Y%m%d%H%M%S")
        unique_id = str(uuid.uuid4())[:8]
        charge.numero_charge = f"CHG-{timestamp}-{unique_id}"
        charge.save()


def reverse_populate_numero_charge(apps, schema_editor):
    """Fonction de rollback - vide le champ numero_charge"""
    ChargeBailleur = apps.get_model('paiements', 'ChargeBailleur')
    ChargeBailleur.objects.update(numero_charge='')


class Migration(migrations.Migration):

    dependencies = [
        ('paiements', '0019_auto_20251025_1458'),
    ]

    operations = [
        # Étape 1: Ajouter le champ sans contrainte unique
        migrations.AddField(
            model_name='chargebailleur',
            name='numero_charge',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Numéro de charge'),
        ),
        # Étape 2: Remplir le champ pour les enregistrements existants
        migrations.RunPython(populate_numero_charge, reverse_populate_numero_charge),
        # Étape 3: Rendre le champ non-nullable
        migrations.AlterField(
            model_name='chargebailleur',
            name='numero_charge',
            field=models.CharField(blank=True, max_length=50, verbose_name='Numéro de charge'),
        ),
        # Étape 4: Ajouter la contrainte unique
        migrations.AlterField(
            model_name='chargebailleur',
            name='numero_charge',
            field=models.CharField(blank=True, max_length=50, unique=True, verbose_name='Numéro de charge'),
        ),
    ]
