# Generated by Django 4.2.24 on 2025-10-25 13:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('paiements', '0020_add_numero_charge_field'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='chargebailleur',
            table='paiements_chargebailleur',
        ),
    ]
