# Generated by Django 4.2.24 on 2025-10-30 15:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('proprietes', '0036_fix_charges_bailleur_numero_unique'),
        ('paiements', '0021_fix_chargebailleur_table_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recapmensuel',
            name='bailleur',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recaps_mensuels', to='proprietes.bailleur', verbose_name='Bailleur'),
        ),
    ]
