# Generated by Django 5.2.5 on 2025-09-03 14:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contrats', '0007_add_unite_locative_support'),
        ('paiements', '0025_add_validation_fields'),
        ('proprietes', '0018_add_unites_locatives_system'),
    ]

    operations = [
        migrations.CreateModel(
            name='DetailRetraitUnite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('loyer_theorique', models.DecimalField(decimal_places=2, max_digits=10, verbose_name="Loyer théorique de l'unité")),
                ('charges_theoriques', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name="Charges théoriques de l'unité")),
                ('paiements_recus', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Paiements effectivement reçus')),
                ('charges_deductibles', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name="Charges déductibles de l'unité")),
                ('revenus_nets_unite', models.DecimalField(decimal_places=2, max_digits=10, verbose_name="Revenus nets de l'unité")),
                ('taux_paiement', models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='Taux de paiement (%)')),
                ('statut_paiement', models.CharField(choices=[('complet', 'Complet'), ('partiel', 'Partiel'), ('impaye', 'Impayé'), ('avance', 'Avance')], default='complet', max_length=20, verbose_name='Statut de paiement')),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('notes', models.TextField(blank=True, verbose_name='Notes spécifiques à cette unité')),
                ('contrat', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='details_retraits', to='contrats.contrat', verbose_name='Contrat')),
                ('retrait', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='details_unites', to='paiements.retraitbailleur', verbose_name='Retrait')),
                ('unite_locative', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='details_retraits', to='proprietes.unitelocative', verbose_name='Unité locative')),
            ],
            options={
                'verbose_name': 'Détail retrait par unité',
                'verbose_name_plural': 'Détails retraits par unités',
                'ordering': ['unite_locative__numero_unite'],
                'unique_together': {('retrait', 'unite_locative')},
            },
        ),
    ]
