# Generated by Django 4.2.24 on 2026-01-08 20:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('paiements', '0027_fix_unique_constraint_recap_allow_deleted'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quittancepaiement',
            name='paiement',
        ),
        migrations.AddField(
            model_name='quittancepaiement',
            name='est_cumulee',
            field=models.BooleanField(default=False, help_text='Indique si cette quittance regroupe plusieurs paiements', verbose_name='Quittance cumulée'),
        ),
        migrations.AddField(
            model_name='quittancepaiement',
            name='paiement_principal',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='quittance_principale', to='paiements.paiement', verbose_name='Paiement principal'),
        ),
        migrations.AddField(
            model_name='quittancepaiement',
            name='paiements',
            field=models.ManyToManyField(related_name='quittances', to='paiements.paiement', verbose_name='Paiements'),
        ),
    ]
