# Generated by Django 4.2.24 on 2025-09-18 10:48

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('paiements', '0028_remove_echelonpaiement_unique_plan_echelon_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='echelonpaiement',
            name='montant',
            field=models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0.01)], verbose_name="Montant de l'étape"),
        ),
        migrations.AlterField(
            model_name='echelonpaiement',
            name='numero_echelon',
            field=models.PositiveIntegerField(verbose_name="Numéro d'étape"),
        ),
        migrations.AlterField(
            model_name='echelonpaiement',
            name='plan',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='echelons', to='paiements.planpaiementpartiel', verbose_name='Accord de paiement'),
        ),
        migrations.AlterField(
            model_name='paiementpartiel',
            name='echelon',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='paiements', to='paiements.echelonpaiement', verbose_name='Étape associée'),
        ),
        migrations.AlterField(
            model_name='planpaiementpartiel',
            name='date_debut',
            field=models.DateField(verbose_name='Date de début'),
        ),
        migrations.AlterField(
            model_name='planpaiementpartiel',
            name='date_fin_prevue',
            field=models.DateField(verbose_name='Date limite'),
        ),
        migrations.AlterField(
            model_name='planpaiementpartiel',
            name='montant_total',
            field=models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0.01)], verbose_name='Montant à payer'),
        ),
        migrations.AlterField(
            model_name='planpaiementpartiel',
            name='nom_plan',
            field=models.CharField(help_text='Ex: Plan de paiement partiel - Janvier 2025', max_length=100, verbose_name='Nom du plan'),
        ),
    ]
