# Generated by Django 4.2.24 on 2026-02-03 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paiements', '0028_quittance_cumulee'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='avanceloyer',
            index=models.Index(fields=['contrat', 'statut'], name='avance_ctr_stat_idx'),
        ),
        migrations.AddIndex(
            model_name='avanceloyer',
            index=models.Index(fields=['statut', 'date_avance'], name='avance_stat_date_idx'),
        ),
        migrations.AddIndex(
            model_name='avanceloyer',
            index=models.Index(fields=['date_avance'], name='avance_date_idx'),
        ),
        migrations.AddIndex(
            model_name='avanceloyer',
            index=models.Index(fields=['mois_debut_couverture'], name='avance_mois_deb_idx'),
        ),
        migrations.AddIndex(
            model_name='avanceloyer',
            index=models.Index(fields=['contrat', 'statut', 'montant_restant'], name='avance_ctr_stat_rst_idx'),
        ),
        migrations.AddIndex(
            model_name='consommationavance',
            index=models.Index(fields=['avance', 'mois_consomme'], name='cons_avance_mois_idx'),
        ),
        migrations.AddIndex(
            model_name='consommationavance',
            index=models.Index(fields=['mois_consomme'], name='cons_mois_idx'),
        ),
        migrations.AddIndex(
            model_name='consommationavance',
            index=models.Index(fields=['avance'], name='cons_avance_idx'),
        ),
    ]
