# Generated by Django 4.2.24 on 2026-02-09 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paiements', '0029_add_indexes_avances_optimisation'),
    ]

    operations = [
        migrations.AddField(
            model_name='paiement',
            name='est_saisie_manuelle_historique',
            field=models.BooleanField(default=False, help_text="Cocher pour un paiement importé de l'ancienne plateforme (désactive les validations automatiques)", verbose_name='Saisie manuelle historique'),
        ),
    ]
