# Generated by Django 4.2.24 on 2026-02-09 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paiements', '0029_add_indexes_avances_optimisation'),
    ]

    operations = [
        migrations.RunSQL(
            sql="""
            ALTER TABLE paiements_paiement
            ADD COLUMN IF NOT EXISTS est_saisie_manuelle_historique BOOLEAN DEFAULT FALSE NOT NULL;
            """,
            reverse_sql="""
            ALTER TABLE paiements_paiement
            DROP COLUMN IF EXISTS est_saisie_manuelle_historique;
            """
        ),
    ]
