# Generated by Django 4.2.24 on 2026-02-12 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paiements', '0030_paiement_est_saisie_manuelle_historique'),
    ]

    operations = [
        # La colonne existe déjà (ajoutée par 0030 via RunSQL).
        # On met à jour uniquement l'état Django pour éviter la recréation de table
        # qui échouerait sur les doublons de reference_paiement (contrainte UNIQUE).
        migrations.SeparateDatabaseAndState(
            state_operations=[
                migrations.AddField(
                    model_name='paiement',
                    name='est_saisie_manuelle_historique',
                    field=models.BooleanField(default=False, help_text="Cocher pour un paiement importé de l'ancienne plateforme (désactive les validations automatiques)", verbose_name='Saisie manuelle historique'),
                ),
            ],
            database_operations=[],
        ),
    ]
