# Generated by Django 4.2.24 on 2025-10-04 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paiements', '0035_add_created_updated_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='retraitbailleur',
            name='montant_charges_bailleur',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Montant des charges bailleur'),
        ),
    ]
