# Generated by Django 4.2.24 on 2025-10-04 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paiements', '0036_auto_20251004_1310'),
    ]

    operations = [
        migrations.AddField(
            model_name='paiement',
            name='notes',
            field=models.TextField(blank=True, help_text='Notes ou commentaires sur le paiement', verbose_name='Notes'),
        ),
    ]
