# Generated by Django 4.2.24 on 2025-10-04 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paiements', '0038_add_date_creation_field'),
    ]

    operations = [
        migrations.AddField(
            model_name='paiement',
            name='date_modification',
            field=models.DateTimeField(auto_now=True, null=True, verbose_name='Date de modification'),
        ),
    ]
