# Generated by Django 4.2.24 on 2025-10-04 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paiements', '0039_add_date_modification_field'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paiement',
            name='montant_net_paye',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Montant net payé'),
        ),
    ]
