# Generated by Django 4.2.24 on 2025-10-04 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paiements', '0040_add_montant_net_paye_default'),
    ]

    operations = [
        migrations.AddField(
            model_name='paiement',
            name='reference_paiement',
            field=models.CharField(blank=True, help_text='Référence unique du paiement', max_length=50, verbose_name='Référence de paiement'),
        ),
    ]
