# Generated by Django 4.2.24 on 2025-10-05 18:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('paiements', '0035_add_created_updated_fields'),
    ]

    operations = [
    ]
