# Generated by Django 4.2.7 on 2025-10-06 12:00:00

from django.db import migrations, models
import django.db.models.deletion
from django.conf import settings


class Migration(migrations.Migration):

    dependencies = [
        ('contrats', '0001_initial'),
        ('paiements', '0036_auto_20251004_1310'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AvanceLoyer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('montant_avance', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(0.01)], verbose_name='Montant de l\'avance')),
                ('loyer_mensuel', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0.01)], verbose_name='Loyer mensuel')),
                ('nombre_mois_couverts', models.PositiveIntegerField(default=0, verbose_name='Nombre de mois couverts')),
                ('montant_restant', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Montant restant')),
                ('date_avance', models.DateField(verbose_name='Date de l\'avance')),
                ('mois_debut_couverture', models.DateField(verbose_name='Mois de début de couverture')),
                ('mois_fin_couverture', models.DateField(blank=True, null=True, verbose_name='Mois de fin de couverture')),
                ('statut', models.CharField(choices=[('active', 'Active'), ('epuisee', 'Épuisée'), ('annulee', 'Annulée')], default='active', max_length=20, verbose_name='Statut')),
                ('notes', models.TextField(blank=True, verbose_name='Notes')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('contrat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='avances_loyer', to='contrats.contrat', verbose_name='Contrat')),
            ],
            options={
                'verbose_name': 'Avance de loyer',
                'verbose_name_plural': 'Avances de loyer',
                'ordering': ['-date_avance'],
                'app_label': 'paiements',
            },
        ),
        migrations.CreateModel(
            name='ConsommationAvance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mois_consomme', models.DateField(verbose_name='Mois consommé')),
                ('montant_consomme', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Montant consommé')),
                ('montant_restant_apres', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Montant restant après')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('avance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='consommations', to='paiements.avanceloyer', verbose_name='Avance')),
                ('paiement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='consommations_avance', to='paiements.paiement', verbose_name='Paiement')),
            ],
            options={
                'verbose_name': 'Consommation d\'avance',
                'verbose_name_plural': 'Consommations d\'avance',
                'ordering': ['-mois_consomme'],
                'app_label': 'paiements',
            },
        ),
        migrations.CreateModel(
            name='HistoriquePaiement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mois_paiement', models.DateField(verbose_name='Mois du paiement')),
                ('montant_paye', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Montant payé')),
                ('montant_du', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Montant dû')),
                ('montant_avance_utilisee', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Montant d\'avance utilisée')),
                ('montant_restant_du', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Montant restant dû')),
                ('mois_regle', models.BooleanField(default=False, verbose_name='Mois réglé')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('contrat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historique_paiements', to='contrats.contrat', verbose_name='Contrat')),
                ('paiement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historique', to='paiements.paiement', verbose_name='Paiement')),
            ],
            options={
                'verbose_name': 'Historique de paiement',
                'verbose_name_plural': 'Historiques de paiement',
                'ordering': ['-mois_paiement'],
                'app_label': 'paiements',
            },
        ),
        migrations.AddConstraint(
            model_name='consommationavance',
            constraint=models.UniqueConstraint(fields=('avance', 'mois_consomme'), name='unique_consommation_per_avance_month'),
        ),
        migrations.AddConstraint(
            model_name='historiquepaiement',
            constraint=models.UniqueConstraint(fields=('contrat', 'mois_paiement'), name='unique_historique_per_contrat_month'),
        ),
    ]
