# Generated by Django 4.2.24 on 2025-10-07 08:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('paiements', '0045_avance_loyer_system'),
        ('paiements', '0047_merge_0045_auto_20251005_2002_0046_fix_statut_field'),
    ]

    operations = [
    ]
