# Generated by Django 4.2.7 on 2025-07-20 16:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='is_sent_sms',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='notificationpreference',
            name='contract_expiring_sms',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='notificationpreference',
            name='maintenance_sms',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='notificationpreference',
            name='payment_due_sms',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='notificationpreference',
            name='payment_overdue_email',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='notificationpreference',
            name='payment_overdue_sms',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='notificationpreference',
            name='payment_received_sms',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='notificationpreference',
            name='phone_number',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='notificationpreference',
            name='sms_notifications',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='notificationpreference',
            name='sms_provider',
            field=models.CharField(choices=[('twilio', 'Twilio'), ('nexmo', 'Nexmo/Vonage'), ('custom', 'Fournisseur personnalisé')], default='twilio', max_length=50),
        ),
        migrations.AddField(
            model_name='notificationpreference',
            name='system_alerts_sms',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='notification',
            name='type',
            field=models.CharField(choices=[('payment_due', 'Échéance de paiement'), ('payment_received', 'Paiement reçu'), ('payment_overdue', 'Paiement en retard'), ('contract_expiring', 'Contrat expirant'), ('maintenance_request', 'Demande de maintenance'), ('maintenance_completed', 'Maintenance terminée'), ('system_alert', 'Alerte système'), ('info', 'Information générale')], default='info', max_length=50),
        ),
        migrations.CreateModel(
            name='SMSNotification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_number', models.CharField(max_length=20)),
                ('message', models.TextField()),
                ('status', models.CharField(choices=[('pending', 'En attente'), ('sent', 'Envoyé'), ('delivered', 'Livré'), ('failed', 'Échec'), ('cancelled', 'Annulé')], default='pending', max_length=20)),
                ('provider', models.CharField(default='twilio', max_length=50)),
                ('provider_message_id', models.CharField(blank=True, max_length=100, null=True)),
                ('provider_response', models.TextField(blank=True, null=True)),
                ('attempts', models.PositiveIntegerField(default=0)),
                ('max_attempts', models.PositiveIntegerField(default=3)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('delivered_at', models.DateTimeField(blank=True, null=True)),
                ('notification', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sms_notifications', to='notifications.notification')),
            ],
            options={
                'verbose_name': 'Notification SMS',
                'verbose_name_plural': 'Notifications SMS',
                'ordering': ['-created_at'],
            },
        ),
    ]
