# Generated by Django 4.2.7 on 2025-07-20 16:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0002_notification_is_sent_sms_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='smsnotification',
            name='notification',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sms_notifications', to='notifications.notification'),
        ),
    ]
