# Generated by Django 4.2.7 on 2025-07-20 08:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('proprietes', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='propriete',
            name='charges',
        ),
        migrations.AddField(
            model_name='propriete',
            name='charges_locataire',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=8, verbose_name='Charges locataire (eau, électricité, etc.)'),
        ),
        migrations.CreateModel(
            name='ChargesBailleur',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=200, verbose_name='Titre de la charge')),
                ('description', models.TextField(verbose_name='Description détaillée')),
                ('type_charge', models.CharField(choices=[('reparation', 'Réparation'), ('entretien', 'Entretien'), ('travaux', 'Travaux'), ('urgence', 'Urgence'), ('autre', 'Autre')], default='reparation', max_length=20, verbose_name='Type de charge')),
                ('montant', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Montant (€)')),
                ('montant_rembourse', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Montant remboursé (€)')),
                ('date_charge', models.DateField(verbose_name='Date de la charge')),
                ('date_remboursement', models.DateField(blank=True, null=True, verbose_name='Date de remboursement')),
                ('statut', models.CharField(choices=[('en_attente', 'En attente de remboursement'), ('rembourse', 'Remboursé'), ('deduit_loyer', 'Déduit du loyer'), ('annule', 'Annulé')], default='en_attente', max_length=20, verbose_name='Statut')),
                ('priorite', models.CharField(choices=[('basse', 'Basse'), ('normale', 'Normale'), ('haute', 'Haute'), ('urgente', 'Urgente')], default='normale', max_length=20, verbose_name='Priorité')),
                ('facture', models.FileField(blank=True, null=True, upload_to='charges_bailleur/factures/', verbose_name='Facture/Justificatif')),
                ('numero_facture', models.CharField(blank=True, max_length=100, verbose_name='Numéro de facture')),
                ('date_creation', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
                ('date_modification', models.DateTimeField(auto_now=True, verbose_name='Date de modification')),
                ('notes', models.TextField(blank=True, verbose_name='Notes')),
                ('cree_par', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='charges_bailleur_crees', to=settings.AUTH_USER_MODEL, verbose_name='Créé par')),
                ('propriete', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='charges_bailleur', to='proprietes.propriete', verbose_name='Propriété')),
            ],
            options={
                'verbose_name': 'Charge bailleur',
                'verbose_name_plural': 'Charges bailleur',
                'ordering': ['-date_charge', '-date_creation'],
            },
        ),
    ]
