# Generated by Django 4.2.7 on 2025-07-21 15:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('proprietes', '0002_remove_propriete_charges_propriete_charges_locataire_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='bailleur',
            name='deleted_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Date de suppression'),
        ),
        migrations.AddField(
            model_name='bailleur',
            name='deleted_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_deleted', to=settings.AUTH_USER_MODEL, verbose_name='Supprimé par'),
        ),
        migrations.AddField(
            model_name='bailleur',
            name='is_deleted',
            field=models.BooleanField(default=False, verbose_name='Supprimé logiquement'),
        ),
        migrations.AddField(
            model_name='chargesbailleur',
            name='deleted_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Date de suppression'),
        ),
        migrations.AddField(
            model_name='chargesbailleur',
            name='deleted_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_deleted', to=settings.AUTH_USER_MODEL, verbose_name='Supprimé par'),
        ),
        migrations.AddField(
            model_name='chargesbailleur',
            name='is_deleted',
            field=models.BooleanField(default=False, verbose_name='Supprimé logiquement'),
        ),
        migrations.AddField(
            model_name='locataire',
            name='deleted_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Date de suppression'),
        ),
        migrations.AddField(
            model_name='locataire',
            name='deleted_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_deleted', to=settings.AUTH_USER_MODEL, verbose_name='Supprimé par'),
        ),
        migrations.AddField(
            model_name='locataire',
            name='is_deleted',
            field=models.BooleanField(default=False, verbose_name='Supprimé logiquement'),
        ),
        migrations.AddField(
            model_name='propriete',
            name='deleted_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Date de suppression'),
        ),
        migrations.AddField(
            model_name='propriete',
            name='deleted_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_deleted', to=settings.AUTH_USER_MODEL, verbose_name='Supprimé par'),
        ),
        migrations.AddField(
            model_name='propriete',
            name='is_deleted',
            field=models.BooleanField(default=False, verbose_name='Supprimé logiquement'),
        ),
        migrations.AddField(
            model_name='typebien',
            name='deleted_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Date de suppression'),
        ),
        migrations.AddField(
            model_name='typebien',
            name='deleted_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_deleted', to=settings.AUTH_USER_MODEL, verbose_name='Supprimé par'),
        ),
        migrations.AddField(
            model_name='typebien',
            name='is_deleted',
            field=models.BooleanField(default=False, verbose_name='Supprimé logiquement'),
        ),
    ]
