# Generated by Django 5.2.4 on 2025-08-20 20:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proprietes', '0011_bailleur_is_deleted_locataire_is_deleted_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='is_deleted',
            field=models.BooleanField(default=False, verbose_name='Supprimé logiquement'),
        ),
    ]
