# Generated by Django 5.2.5 on 2025-08-25 11:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('proprietes', '0002_add_garant_fields'),
        ('proprietes', '0013_alter_bailleur_adresse_alter_bailleur_code_postal_and_more'),
    ]

    operations = [
    ]
