# Generated by Django 5.2.5 on 2025-09-03 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proprietes', '0016_chargesbailleur_montant_deja_deduit_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='propriete',
            name='surface',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Surface en mètres carrés (optionnel)', max_digits=8, null=True, verbose_name='Surface (m²)'),
        ),
    ]
