# Generated by Django 5.2.5 on 2025-09-03 14:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proprietes', '0018_add_unites_locatives_system'),
    ]

    operations = [
        migrations.AddField(
            model_name='unitelocative',
            name='bailleur',
            field=models.ForeignKey(blank=True, help_text='Bailleur spécifique pour cette unité (optionnel, par défaut celui de la propriété)', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='unites_locatives', to='proprietes.bailleur', verbose_name='Bailleur'),
        ),
    ]
