# Generated by Django 4.2.11 on 2025-09-04 20:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proprietes', '0020_piece_cout_acces_mensuel_piece_est_espace_partage_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='propriete',
            name='charges_locataire',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, null=True, verbose_name='Charges locataire'),
        ),
    ]