# Generated by Django 4.2.24 on 2025-09-27 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proprietes', '0025_propriete_cuisine'),
    ]

    operations = [
        migrations.AlterField(
            model_name='propriete',
            name='numero_propriete',
            field=models.CharField(db_index=True, default='PR0001', help_text='Identifiant unique de la propriété', max_length=50, unique=True, verbose_name='Numéro propriété'),
        ),
    ]
