# Generated by Django 4.2.24 on 2025-10-05 18:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('utilisateurs', '0009_alter_utilisateur_deleted_by_and_more'),
    ]

    operations = [
    ]
