# Generated by Django 4.2.24 on 2025-10-18 22:25

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('utilisateurs', '0011_alter_groupetravail_date_creation_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='utilisateur',
            name='telephone',
            field=models.CharField(blank=True, help_text='Format international (ex: +226 70 12 34 56)', max_length=20, null=True, validators=[django.core.validators.RegexValidator(message='Format de téléphone invalide. Utilisez le format international.', regex='^(\\+?[1-9]\\d{0,3})?[1-9]\\d{7,14}$')]),
        ),
    ]
