# Generated by Django 4.2.7 on 2025-07-19 19:24

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('proprietes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contrat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_contrat', models.CharField(max_length=50, unique=True, verbose_name='Numéro de contrat')),
                ('date_debut', models.DateField(verbose_name='Date de début')),
                ('date_fin', models.DateField(verbose_name='Date de fin')),
                ('date_signature', models.DateField(verbose_name='Date de signature')),
                ('loyer_mensuel', models.DecimalField(decimal_places=2, max_digits=8, verbose_name='Loyer mensuel')),
                ('charges_mensuelles', models.DecimalField(decimal_places=2, default=0, max_digits=8, verbose_name='Charges mensuelles')),
                ('depot_garantie', models.DecimalField(decimal_places=2, default=0, max_digits=8, verbose_name='Dépôt de garantie')),
                ('jour_paiement', models.PositiveIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MinValueValidator(31)], verbose_name='Jour de paiement')),
                ('mode_paiement', models.CharField(choices=[('virement', 'Virement bancaire'), ('cheque', 'Chèque'), ('especes', 'Espèces'), ('prelevement', 'Prélèvement automatique')], default='virement', max_length=20, verbose_name='Mode de paiement')),
                ('est_actif', models.BooleanField(default=True, verbose_name='Contrat actif')),
                ('est_resilie', models.BooleanField(default=False, verbose_name='Contrat résilié')),
                ('date_resiliation', models.DateField(blank=True, null=True, verbose_name='Date de résiliation')),
                ('motif_resiliation', models.TextField(blank=True, verbose_name='Motif de résiliation')),
                ('date_creation', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
                ('date_modification', models.DateTimeField(auto_now=True, verbose_name='Date de modification')),
                ('notes', models.TextField(blank=True, verbose_name='Notes')),
                ('cree_par', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='contrats_crees', to=settings.AUTH_USER_MODEL, verbose_name='Créé par')),
                ('locataire', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='contrats', to='proprietes.locataire', verbose_name='Locataire')),
                ('propriete', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='contrats', to='proprietes.propriete', verbose_name='Propriété')),
            ],
            options={
                'verbose_name': 'Contrat',
                'verbose_name_plural': 'Contrats',
                'ordering': ['-date_debut'],
            },
        ),
        migrations.CreateModel(
            name='Quittance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mois', models.DateField(verbose_name='Mois concerné')),
                ('montant_loyer', models.DecimalField(decimal_places=2, max_digits=8, verbose_name='Montant loyer')),
                ('montant_charges', models.DecimalField(decimal_places=2, default=0, max_digits=8, verbose_name='Montant charges')),
                ('montant_total', models.DecimalField(decimal_places=2, max_digits=8, verbose_name='Montant total')),
                ('date_creation', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
                ('date_emission', models.DateTimeField(auto_now_add=True, verbose_name="Date d'émission")),
                ('numero_quittance', models.CharField(max_length=50, unique=True, verbose_name='Numéro de quittance')),
                ('contrat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quittances', to='contrats.contrat', verbose_name='Contrat')),
            ],
            options={
                'verbose_name': 'Quittance',
                'verbose_name_plural': 'Quittances',
                'ordering': ['-mois'],
                'unique_together': {('contrat', 'mois')},
            },
        ),
        migrations.CreateModel(
            name='EtatLieux',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_etat', models.CharField(choices=[('entree', 'Entrée'), ('sortie', 'Sortie')], max_length=10, verbose_name="Type d'état des lieux")),
                ('date_etat', models.DateField(verbose_name="Date de l'état des lieux")),
                ('observations_generales', models.TextField(blank=True, verbose_name='Observations générales')),
                ('etat_murs', models.CharField(choices=[('excellent', 'Excellent'), ('bon', 'Bon'), ('moyen', 'Moyen'), ('mauvais', 'Mauvais')], default='bon', max_length=20, verbose_name='État des murs')),
                ('etat_sol', models.CharField(choices=[('excellent', 'Excellent'), ('bon', 'Bon'), ('moyen', 'Moyen'), ('mauvais', 'Mauvais')], default='bon', max_length=20, verbose_name='État du sol')),
                ('etat_plomberie', models.CharField(choices=[('excellent', 'Excellent'), ('bon', 'Bon'), ('moyen', 'Moyen'), ('mauvais', 'Mauvais')], default='bon', max_length=20, verbose_name='État de la plomberie')),
                ('etat_electricite', models.CharField(choices=[('excellent', 'Excellent'), ('bon', 'Bon'), ('moyen', 'Moyen'), ('mauvais', 'Mauvais')], default='bon', max_length=20, verbose_name="État de l'électricité")),
                ('date_creation', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
                ('notes', models.TextField(blank=True, verbose_name='Notes')),
                ('contrat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='etats_lieux', to='contrats.contrat', verbose_name='Contrat')),
                ('cree_par', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='etats_lieux_crees', to=settings.AUTH_USER_MODEL, verbose_name='Créé par')),
            ],
            options={
                'verbose_name': 'État des lieux',
                'verbose_name_plural': 'États des lieux',
                'ordering': ['-date_etat'],
                'unique_together': {('contrat', 'type_etat')},
            },
        ),
    ]
