# Generated by Django 5.2.4 on 2025-08-19 15:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contrats', '0002_contrat_deleted_at_contrat_deleted_by_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='contrat',
            name='avance_loyer',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=8, verbose_name='Avance de loyer'),
        ),
        migrations.AddField(
            model_name='contrat',
            name='avance_loyer_payee',
            field=models.BooleanField(default=False, verbose_name='Avance de loyer payée'),
        ),
        migrations.AddField(
            model_name='contrat',
            name='caution_payee',
            field=models.BooleanField(default=False, verbose_name='Caution payée'),
        ),
        migrations.AddField(
            model_name='contrat',
            name='date_paiement_avance',
            field=models.DateField(blank=True, null=True, verbose_name="Date de paiement de l'avance"),
        ),
        migrations.AddField(
            model_name='contrat',
            name='date_paiement_caution',
            field=models.DateField(blank=True, null=True, verbose_name='Date de paiement de la caution'),
        ),
        migrations.CreateModel(
            name='DocumentContrat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_document', models.CharField(max_length=50, unique=True, verbose_name='Numéro de document')),
                ('date_creation', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
                ('type_document', models.CharField(choices=[('contrat_complet', 'Contrat complet'), ('contrat_simplifie', 'Contrat simplifié'), ('contrat_professionnel', 'Contrat professionnel')], default='contrat_complet', max_length=25, verbose_name='Type de document')),
                ('imprime', models.BooleanField(default=False, verbose_name='Imprimé')),
                ('date_impression', models.DateTimeField(blank=True, null=True, verbose_name="Date d'impression")),
                ('format_impression', models.CharField(choices=[('a4', 'A4'), ('a3', 'A3')], default='a4', max_length=20, verbose_name="Format d'impression")),
                ('version_template', models.CharField(default='1.0', max_length=10, verbose_name='Version du template')),
                ('notes_internes', models.TextField(blank=True, verbose_name='Notes internes')),
                ('contrat', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='document_contrat', to='contrats.contrat', verbose_name='Contrat')),
                ('imprime_par', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='documents_contrat_imprimes', to=settings.AUTH_USER_MODEL, verbose_name='Imprimé par')),
            ],
            options={
                'verbose_name': 'Document de contrat',
                'verbose_name_plural': 'Documents de contrat',
                'ordering': ['-date_creation'],
            },
        ),
        migrations.CreateModel(
            name='RecuCaution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_recu', models.CharField(max_length=50, unique=True, verbose_name='Numéro de reçu')),
                ('date_emission', models.DateTimeField(auto_now_add=True, verbose_name="Date d'émission")),
                ('type_recu', models.CharField(choices=[('caution', 'Caution'), ('avance', 'Avance de loyer'), ('complet', 'Caution + Avance')], default='complet', max_length=20, verbose_name='Type de reçu')),
                ('imprime', models.BooleanField(default=False, verbose_name='Imprimé')),
                ('date_impression', models.DateTimeField(blank=True, null=True, verbose_name="Date d'impression")),
                ('format_impression', models.CharField(choices=[('a5', 'A5'), ('a4', 'A4')], default='a5', max_length=20, verbose_name="Format d'impression")),
                ('notes_internes', models.TextField(blank=True, verbose_name='Notes internes')),
                ('contrat', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='recu_caution', to='contrats.contrat', verbose_name='Contrat')),
                ('imprime_par', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recus_caution_imprimes', to=settings.AUTH_USER_MODEL, verbose_name='Imprimé par')),
            ],
            options={
                'verbose_name': 'Reçu de caution',
                'verbose_name_plural': 'Reçus de caution',
                'ordering': ['-date_emission'],
            },
        ),
        migrations.CreateModel(
            name='ResiliationContrat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_resiliation', models.DateField(verbose_name='Date de résiliation')),
                ('motif_resiliation', models.TextField(verbose_name='Motif de résiliation')),
                ('type_resiliation', models.CharField(choices=[('locataire', 'Résiliation par le locataire'), ('bailleur', 'Résiliation par le bailleur'), ('accord_mutuel', "Résiliation d'accord mutuel"), ('expiration', 'Expiration naturelle'), ('judiciaire', 'Résiliation judiciaire')], max_length=20, verbose_name='Type de résiliation')),
                ('statut', models.CharField(choices=[('en_cours', 'En cours de traitement'), ('validee', 'Validée'), ('annulee', 'Annulée'), ('supprimee', 'Supprimée définitivement')], default='en_cours', max_length=20, verbose_name='Statut')),
                ('etat_lieux_sortie', models.TextField(blank=True, verbose_name='État des lieux de sortie')),
                ('caution_remboursee', models.BooleanField(default=False, verbose_name='Caution remboursée')),
                ('montant_remboursement', models.DecimalField(decimal_places=2, default=0, max_digits=8, verbose_name='Montant du remboursement')),
                ('date_remboursement', models.DateField(blank=True, null=True, verbose_name='Date de remboursement')),
                ('date_creation', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
                ('date_modification', models.DateTimeField(auto_now=True, verbose_name='Date de modification')),
                ('notes', models.TextField(blank=True, verbose_name='Notes')),
                ('contrat', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='resiliation', to='contrats.contrat', verbose_name='Contrat')),
                ('cree_par', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='resiliations_crees', to=settings.AUTH_USER_MODEL, verbose_name='Créé par')),
                ('validee_par', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='resiliations_validees', to=settings.AUTH_USER_MODEL, verbose_name='Validée par')),
            ],
            options={
                'verbose_name': 'Résiliation de contrat',
                'verbose_name_plural': 'Résiliations de contrat',
                'ordering': ['-date_resiliation'],
            },
        ),
    ]
