# Generated by Django 5.2.5 on 2025-08-23 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contrats', '0004_alter_contrat_avance_loyer_and_more'),
        ('proprietes', '0015_create_recapitulatif_mensuel_bailleur'),
    ]

    operations = [
        migrations.AddField(
            model_name='contrat',
            name='pieces',
            field=models.ManyToManyField(help_text='Pièces spécifiques louées dans ce contrat', related_name='contrats', through='proprietes.PieceContrat', to='proprietes.piece', verbose_name='Pièces louées'),
        ),
    ]
