# Generated by Django 5.2.5 on 2025-08-28 15:01

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contrats', '0005_contrat_pieces_alter_contrat_charges_mensuelles_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contrat',
            name='depot_garantie',
            field=models.CharField(blank=True, default='0.00', max_length=20, null=True, verbose_name='Dépôt de garantie ou Caution'),
        ),
        migrations.AlterField(
            model_name='contrat',
            name='jour_paiement',
            field=models.PositiveIntegerField(blank=True, default=1, help_text='Jour du mois pour le paiement du loyer (optionnel)', null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(31)], verbose_name='Jour de paiement'),
        ),
    ]
