# Generated by Django 4.2.24 on 2025-10-08 11:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contrats', '0002_add_contract_template_fields'),
        ('contrats', '0009_alter_contrat_avance_loyer_and_more'),
    ]

    operations = [
    ]
