# Generated by Django 4.2.24 on 2025-10-17 20:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contrats', '0030_fix_decimal_fields'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contrat',
            name='loyer_mensuel',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Sera automatiquement rempli à partir de la propriété ou unité locative sélectionnée', max_digits=12, verbose_name='Loyer mensuel'),
        ),
    ]
