# Generated by Django 4.2.24 on 2025-10-22 18:39

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contrats', '0031_alter_contrat_loyer_mensuel'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContratKbis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('agence_nom', models.CharField(default='KBIS IMMOBILIER', max_length=200, verbose_name="Nom de l'agence")),
                ('agence_adresse', models.CharField(default='secteur 26 Pissy', max_length=300, verbose_name="Adresse de l'agence")),
                ('agence_representant', models.CharField(default='M. NIKIEMA PA MAMDOU', max_length=200, verbose_name="Représentant de l'agence")),
                ('agence_telephone', models.CharField(default='70-20-64-91', max_length=20, verbose_name="Téléphone de l'agence")),
                ('locataire_cnib', models.CharField(max_length=50, verbose_name='N° CNIB du locataire')),
                ('locataire_profession', models.CharField(max_length=200, verbose_name='Profession du locataire')),
                ('locataire_adresse', models.TextField(verbose_name='Adresse du locataire')),
                ('locataire_telephone', models.CharField(max_length=20, verbose_name='Téléphone du locataire')),
                ('garant_nom', models.CharField(max_length=200, verbose_name='Nom du garant')),
                ('garant_profession', models.CharField(max_length=200, verbose_name='Profession du garant')),
                ('garant_adresse', models.TextField(verbose_name='Adresse du garant')),
                ('garant_telephone', models.CharField(max_length=20, verbose_name='Téléphone du garant')),
                ('garant_cnib', models.CharField(blank=True, max_length=50, null=True, verbose_name='N° CNIB du garant')),
                ('propriete_numero', models.CharField(max_length=50, verbose_name='Numéro de la maison')),
                ('propriete_adresse', models.CharField(max_length=300, verbose_name='Adresse de la propriété')),
                ('caution_montant', models.DecimalField(decimal_places=2, help_text='Montant total de la caution (généralement 3 mois de loyer)', max_digits=12, verbose_name='Montant de la caution')),
                ('caution_nombre_mois', models.IntegerField(default=3, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(12)], verbose_name='Nombre de mois de caution')),
                ('paiement_debut_mois', models.CharField(default='fin du mois de SEPTEMBRE 2025', max_length=50, verbose_name='Début du paiement')),
                ('paiement_echeance', models.CharField(default='03 du mois suivant', max_length=50, verbose_name='Échéance de paiement')),
                ('delai_annulation', models.IntegerField(default=48, verbose_name="Délai d'annulation (heures)")),
                ('preavis_resiliation_locataire', models.CharField(default='un mois', max_length=50, verbose_name='Préavis de résiliation (locataire)')),
                ('preavis_resiliation_agence', models.CharField(default='trois mois', max_length=50, verbose_name='Préavis de résiliation (agence)')),
                ('date_remise_cles', models.CharField(default='01er du mois suivant', max_length=50, verbose_name='Date de remise des clés')),
                ('date_generation', models.DateTimeField(auto_now_add=True, verbose_name='Date de génération')),
                ('version_template', models.CharField(default='1.0', max_length=20, verbose_name='Version du template')),
            ],
            options={
                'verbose_name': 'Contrat KBIS',
                'verbose_name_plural': 'Contrats KBIS',
                'ordering': ['-date_generation'],
            },
        ),
        migrations.AlterField(
            model_name='contrat',
            name='depot_garantie',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Caution'),
        ),
        migrations.AlterField(
            model_name='contrat',
            name='depot_garantie_numerique',
            field=models.CharField(blank=True, max_length=20, verbose_name='Caution en chiffres'),
        ),
        migrations.AlterField(
            model_name='contrat',
            name='depot_garantie_texte',
            field=models.CharField(blank=True, max_length=100, verbose_name='Caution en lettres'),
        ),
        migrations.CreateModel(
            name='EtatLieuxKbis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('indexe_sonabel', models.BooleanField(default=True, verbose_name='Indexé du compteur SONABEL')),
                ('indexe_onea', models.BooleanField(default=True, verbose_name='Indexé du compteur ONEA')),
                ('peinture_murs', models.CharField(choices=[('OK', 'OK'), ('PASSABLE', 'PASSABLE'), ('MAUVAIS', 'MAUVAIS')], default='OK', max_length=20, verbose_name='État de la peinture des murs')),
                ('peinture_couvertures', models.CharField(choices=[('OK', 'OK'), ('PASSABLE', 'PASSABLE'), ('MAUVAIS', 'MAUVAIS')], default='OK', max_length=20, verbose_name='État de la peinture des couvertures')),
                ('peinture_plafond', models.CharField(choices=[('OK', 'OK'), ('PASSABLE', 'PASSABLE'), ('MAUVAIS', 'MAUVAIS')], default='OK', max_length=20, verbose_name='État de la peinture du plafond')),
                ('cremone_vitre', models.CharField(choices=[('OK', 'OK'), ('PASSABLE', 'PASSABLE'), ('MAUVAIS', 'MAUVAIS')], default='OK', max_length=20, verbose_name='État de crémoné de vitre')),
                ('prise_electrique', models.CharField(choices=[('OK', 'OK'), ('PASSABLE', 'PASSABLE'), ('MAUVAIS', 'MAUVAIS')], default='OK', max_length=20, verbose_name='État des prises électriques')),
                ('cles_grand_portail', models.BooleanField(default=True, verbose_name='Clés du grand portail')),
                ('cles_porte_salon', models.BooleanField(default=True, verbose_name='Clés de la porte du salon')),
                ('cles_iso_planes', models.BooleanField(default=True, verbose_name='Clés iso planes')),
                ('cles_placard', models.BooleanField(default=True, verbose_name='Clés du placard')),
                ('porte_rideau', models.BooleanField(default=True, verbose_name='Porte rideau')),
                ('reglettes', models.CharField(choices=[('OK', 'OK'), ('NON', 'NON')], default='OK', max_length=20, verbose_name='Réglettes')),
                ('veilleuses', models.CharField(choices=[('OK', 'OK'), ('NON', 'NON')], default='OK', max_length=20, verbose_name='Veilleuses')),
                ('ventilateurs', models.CharField(choices=[('OK', 'OK'), ('NON', 'NON')], default='OK', max_length=20, verbose_name='Ventilateurs')),
                ('robinets_cuisine', models.CharField(choices=[('OK', 'OK'), ('NON', 'NON')], default='OK', max_length=20, verbose_name='Robinet de la cuisine')),
                ('placards_cuisine', models.CharField(choices=[('OK', 'OK'), ('NON', 'NON')], default='OK', max_length=20, verbose_name='Placards de la cuisine')),
                ('sonnerie', models.CharField(choices=[('OK', 'OK'), ('NON', 'NON')], default='OK', max_length=20, verbose_name='État de la sonnerie')),
                ('wc', models.CharField(choices=[('OK', 'OK'), ('NON', 'NON')], default='OK', max_length=20, verbose_name='WC')),
                ('lavabos', models.CharField(choices=[('OK', 'OK'), ('NON', 'NON')], default='OK', max_length=20, verbose_name='Lavabos')),
                ('miroir', models.CharField(choices=[('OK', 'OK'), ('NON', 'NON')], default='OK', max_length=20, verbose_name='Miroir')),
                ('flexible_douche', models.CharField(choices=[('OK', 'OK'), ('NON', 'NON')], default='OK', max_length=20, verbose_name='Flexible de douche (colonne)')),
                ('accessoires_sanitaires', models.CharField(choices=[('OK', 'OK'), ('NON', 'NON')], default='OK', max_length=20, verbose_name='Accessoires sanitaires')),
                ('lampes_sanitaire', models.CharField(choices=[('OK', 'OK'), ('NON', 'NON')], default='OK', max_length=20, verbose_name='Lampes sanitaires')),
                ('chauffe_eau', models.CharField(choices=[('OK', 'OK'), ('NON', 'NON')], default='OK', max_length=20, verbose_name='Chauffe-eau')),
                ('climatiseur', models.CharField(choices=[('OK', 'OK'), ('NON', 'NON')], default='OK', max_length=20, verbose_name='Climatiseur (entretien)')),
                ('observations', models.TextField(blank=True, null=True, verbose_name='Observations')),
                ('date_generation', models.DateTimeField(auto_now_add=True, verbose_name='Date de génération')),
                ('contrat_kbis', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='etat_lieux', to='contrats.contratkbis', verbose_name='Contrat KBIS')),
            ],
            options={
                'verbose_name': 'État des lieux KBIS',
                'verbose_name_plural': 'États des lieux KBIS',
                'ordering': ['-date_generation'],
            },
        ),
        migrations.AddField(
            model_name='contratkbis',
            name='contrat',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='contrat_kbis', to='contrats.contrat', verbose_name='Contrat de base'),
        ),
    ]
