# Generated by Django 4.2.24 on 2025-10-25 07:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contrats', '0032_contratkbis_alter_contrat_depot_garantie_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contratkbis',
            name='paiement_debut_mois',
            field=models.CharField(default='fin du mois de NOVEMBRE 2025', max_length=50, verbose_name='Début du paiement'),
        ),
    ]
