# Generated by Django 4.2.24 on 2025-10-28 22:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contrats', '0035_make_motif_resiliation_optional'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='resiliationcontrat',
            name='autres_depenses',
        ),
        migrations.RemoveField(
            model_name='resiliationcontrat',
            name='description_autres_depenses',
        ),
        migrations.RemoveField(
            model_name='resiliationcontrat',
            name='facture_onea',
        ),
        migrations.RemoveField(
            model_name='resiliationcontrat',
            name='facture_sonabel',
        ),
        migrations.RemoveField(
            model_name='resiliationcontrat',
            name='travaux_peinture',
        ),
        migrations.RemoveField(
            model_name='resiliationcontrat',
            name='travaux_ventilateur',
        ),
        migrations.CreateModel(
            name='DepenseResiliation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=200, verbose_name='Description de la dépense')),
                ('montant', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Montant (F CFA)')),
                ('ordre', models.PositiveIntegerField(default=0, verbose_name="Ordre d'affichage")),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('resiliation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='depenses', to='contrats.resiliationcontrat', verbose_name='Résiliation')),
            ],
            options={
                'verbose_name': 'Dépense de résiliation',
                'verbose_name_plural': 'Dépenses de résiliation',
                'ordering': ['ordre', 'date_creation'],
            },
        ),
    ]
