# Generated by Django 4.2.24 on 2026-01-08 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contrats', '0038_relax_then_drop_obsolete_resiliation_fields'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contrat',
            name='numero_contrat',
            field=models.CharField(help_text='Vous pouvez saisir un nom personnalisé (ex: DUPONT MARTIN) ou laisser vide pour générer automatiquement un numéro CT-...', max_length=50, unique=True, verbose_name='Numéro de contrat'),
        ),
    ]
