# Generated by Django 4.2.7 on 2025-07-20 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paiements', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='recu',
            name='date_envoi_email',
            field=models.DateTimeField(blank=True, null=True, verbose_name="Date d'envoi email"),
        ),
        migrations.AddField(
            model_name='recu',
            name='envoye_email',
            field=models.BooleanField(default=False, verbose_name='Envoyé par email'),
        ),
        migrations.AddField(
            model_name='recu',
            name='genere_automatiquement',
            field=models.BooleanField(default=True, verbose_name='Généré automatiquement'),
        ),
        migrations.AddField(
            model_name='recu',
            name='template_utilise',
            field=models.CharField(default='standard', max_length=50, verbose_name='Template utilisé'),
        ),
    ]
