# Generated by Django 4.2.7 on 2025-08-06 11:57

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contrats', '0002_contrat_deleted_at_contrat_deleted_by_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('paiements', '0004_paiement_deleted_at_paiement_deleted_by_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='paiement',
            name='montant_charges_deduites',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Montant des charges déduites'),
        ),
        migrations.AddField(
            model_name='paiement',
            name='montant_net_paye',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Montant net payé (après déductions)'),
        ),
        migrations.CreateModel(
            name='ChargeDeductible',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('montant', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0.01)], verbose_name='Montant de la charge')),
                ('libelle', models.CharField(max_length=200, verbose_name='Libellé de la charge')),
                ('description', models.TextField(blank=True, verbose_name='Description détaillée')),
                ('type_charge', models.CharField(choices=[('reparation', 'Réparation'), ('travaux', 'Travaux'), ('entretien', 'Entretien'), ('urgence', 'Urgence'), ('fourniture', 'Fourniture'), ('service', 'Service'), ('autre', 'Autre')], default='reparation', max_length=30, verbose_name='Type de charge')),
                ('statut', models.CharField(choices=[('en_attente', 'En attente de validation'), ('validee', 'Validée'), ('deduite', 'Déduite du loyer'), ('refusee', 'Refusée'), ('annulee', 'Annulée')], default='en_attente', max_length=20, verbose_name='Statut')),
                ('date_charge', models.DateField(verbose_name='Date de la charge')),
                ('date_creation', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
                ('date_validation', models.DateTimeField(blank=True, null=True, verbose_name='Date de validation')),
                ('date_deduction', models.DateTimeField(blank=True, null=True, verbose_name='Date de déduction')),
                ('justificatif_url', models.URLField(blank=True, verbose_name='URL du justificatif')),
                ('facture_numero', models.CharField(blank=True, max_length=100, verbose_name='Numéro de facture')),
                ('fournisseur', models.CharField(blank=True, max_length=150, verbose_name='Fournisseur/Prestataire')),
                ('notes', models.TextField(blank=True, verbose_name='Notes')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='Supprimé logiquement')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='Date de suppression')),
                ('contrat', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='charges_deductibles', to='contrats.contrat', verbose_name='Contrat')),
                ('cree_par', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='charges_deductibles_creees', to=settings.AUTH_USER_MODEL, verbose_name='Créé par')),
                ('deleted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='charges_deductibles_supprimees', to=settings.AUTH_USER_MODEL, verbose_name='Supprimé par')),
                ('paiement_deduction', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='charges_deduites', to='paiements.paiement', verbose_name='Paiement de déduction')),
                ('validee_par', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='charges_deductibles_validees', to=settings.AUTH_USER_MODEL, verbose_name='Validée par')),
            ],
            options={
                'verbose_name': 'Charge déductible',
                'verbose_name_plural': 'Charges déductibles',
                'ordering': ['-date_charge'],
                'indexes': [models.Index(fields=['statut'], name='paiements_c_statut_836dc4_idx'), models.Index(fields=['date_charge'], name='paiements_c_date_ch_5a4d41_idx'), models.Index(fields=['contrat'], name='paiements_c_contrat_83f874_idx')],
            },
        ),
    ]
