# Generated by Django 5.2.4 on 2025-08-19 15:13

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paiements', '0005_paiement_montant_charges_deduites_and_more'),
        ('proprietes', '0005_add_est_actif_to_typebien_chargesbailleur'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='paiement',
            name='est_paiement_partiel',
            field=models.BooleanField(default=False, verbose_name='Paiement partiel'),
        ),
        migrations.AddField(
            model_name='paiement',
            name='mois_paye',
            field=models.DateField(blank=True, help_text='Mois pour lequel ce paiement est effectué', null=True, verbose_name='Mois payé'),
        ),
        migrations.AddField(
            model_name='paiement',
            name='montant_du_mois',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Montant total dû pour le mois (loyer + charges)', max_digits=10, null=True, verbose_name='Montant dû pour le mois'),
        ),
        migrations.AddField(
            model_name='paiement',
            name='montant_restant_du',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Montant restant à payer pour ce mois', max_digits=10, verbose_name='Montant restant dû'),
        ),
        migrations.AlterField(
            model_name='paiement',
            name='type_paiement',
            field=models.CharField(choices=[('loyer', 'Loyer'), ('charges', 'Charges'), ('depot_garantie', 'Dépôt de garantie'), ('regularisation', 'Régularisation'), ('paiement_partiel', 'Paiement partiel'), ('autre', 'Autre')], default='loyer', max_length=20, verbose_name='Type de paiement'),
        ),
        migrations.CreateModel(
            name='RetraitBailleur',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mois_retrait', models.DateField(help_text='Mois pour lequel le retrait est effectué', verbose_name='Mois de retrait')),
                ('montant_loyers_bruts', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(0.01)], verbose_name='Montant total des loyers bruts')),
                ('montant_charges_deductibles', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Montant total des charges déductibles')),
                ('montant_net_a_payer', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Montant net à payer (après déduction des charges)')),
                ('type_retrait', models.CharField(choices=[('mensuel', 'Retrait mensuel'), ('trimestriel', 'Retrait trimestriel'), ('annuel', 'Retrait annuel'), ('exceptionnel', 'Retrait exceptionnel')], default='mensuel', max_length=20, verbose_name='Type de retrait')),
                ('statut', models.CharField(choices=[('en_attente', 'En attente'), ('valide', 'Validé'), ('paye', 'Payé'), ('annule', 'Annulé')], default='en_attente', max_length=20, verbose_name='Statut')),
                ('mode_retrait', models.CharField(choices=[('virement', 'Virement bancaire'), ('cheque', 'Chèque'), ('especes', 'Espèces')], max_length=20, verbose_name='Mode de retrait')),
                ('date_demande', models.DateField(verbose_name='Date de demande')),
                ('date_versement', models.DateField(blank=True, null=True, verbose_name='Date de versement')),
                ('numero_cheque', models.CharField(blank=True, max_length=50, verbose_name='Numéro de chèque')),
                ('reference_virement', models.CharField(blank=True, max_length=100, verbose_name='Référence virement')),
                ('date_creation', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
                ('date_modification', models.DateTimeField(auto_now=True, verbose_name='Date de modification')),
                ('notes', models.TextField(blank=True, verbose_name='Notes')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='Supprimé logiquement')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='Date de suppression')),
                ('bailleur', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='retraits_bailleur', to='proprietes.bailleur', verbose_name='Bailleur')),
                ('cree_par', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='retraits_bailleur_crees', to=settings.AUTH_USER_MODEL, verbose_name='Créé par')),
                ('deleted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='retraits_bailleur_supprimes', to=settings.AUTH_USER_MODEL, verbose_name='Supprimé par')),
                ('paiements_concernes', models.ManyToManyField(related_name='retraits_bailleur', to='paiements.paiement', verbose_name='Paiements concernés')),
                ('valide_par', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='retraits_bailleur_valides', to=settings.AUTH_USER_MODEL, verbose_name='Validé par')),
            ],
            options={
                'verbose_name': 'Retrait bailleur',
                'verbose_name_plural': 'Retraits bailleur',
                'ordering': ['-mois_retrait'],
            },
        ),
        migrations.CreateModel(
            name='RecuRetrait',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_recu', models.CharField(max_length=50, unique=True, verbose_name='Numéro de reçu')),
                ('date_emission', models.DateTimeField(auto_now_add=True, verbose_name="Date d'émission")),
                ('imprime', models.BooleanField(default=False, verbose_name='Imprimé')),
                ('date_impression', models.DateTimeField(blank=True, null=True, verbose_name="Date d'impression")),
                ('genere_automatiquement', models.BooleanField(default=True, verbose_name='Généré automatiquement')),
                ('format_impression', models.CharField(choices=[('a5', 'A5'), ('a4', 'A4')], default='a5', max_length=20, verbose_name="Format d'impression")),
                ('notes_internes', models.TextField(blank=True, verbose_name='Notes internes')),
                ('imprime_par', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recus_retrait_imprimes', to=settings.AUTH_USER_MODEL, verbose_name='Imprimé par')),
                ('retrait_bailleur', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='recu_retrait', to='paiements.retraitbailleur', verbose_name='Retrait bailleur')),
            ],
            options={
                'verbose_name': 'Reçu de retrait',
                'verbose_name_plural': 'Reçus de retrait',
                'ordering': ['-date_emission'],
            },
        ),
        migrations.CreateModel(
            name='RetraitChargeDeductible',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_ajout', models.DateTimeField(auto_now_add=True, verbose_name="Date d'ajout")),
                ('charge_deductible', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='paiements.chargedeductible', verbose_name='Charge déductible')),
                ('retrait_bailleur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='paiements.retraitbailleur', verbose_name='Retrait bailleur')),
            ],
            options={
                'verbose_name': 'Charge déductible du retrait',
                'verbose_name_plural': 'Charges déductibles du retrait',
                'unique_together': {('retrait_bailleur', 'charge_deductible')},
            },
        ),
        migrations.AddField(
            model_name='retraitbailleur',
            name='charges_deductibles',
            field=models.ManyToManyField(related_name='retraits_bailleur', through='paiements.RetraitChargeDeductible', to='paiements.chargedeductible', verbose_name='Charges déductibles'),
        ),
        migrations.CreateModel(
            name='RecapMensuel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mois_recap', models.DateField(help_text='Mois pour lequel le récapitulatif est établi', verbose_name='Mois du récapitulatif')),
                ('total_loyers_bruts', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Total des loyers bruts')),
                ('total_charges_deductibles', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Total des charges déductibles')),
                ('total_net_a_payer', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Total net à payer')),
                ('nombre_proprietes', models.PositiveIntegerField(default=0, verbose_name='Nombre de propriétés')),
                ('nombre_contrats_actifs', models.PositiveIntegerField(default=0, verbose_name='Nombre de contrats actifs')),
                ('nombre_paiements_recus', models.PositiveIntegerField(default=0, verbose_name='Nombre de paiements reçus')),
                ('statut', models.CharField(choices=[('en_cours', 'En cours de préparation'), ('valide', 'Validé'), ('envoye', 'Envoyé au bailleur'), ('paye', 'Payé au bailleur')], default='en_cours', max_length=20, verbose_name='Statut')),
                ('date_creation', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
                ('date_validation', models.DateTimeField(blank=True, null=True, verbose_name='Date de validation')),
                ('date_envoi', models.DateTimeField(blank=True, null=True, verbose_name="Date d'envoi")),
                ('date_paiement', models.DateTimeField(blank=True, null=True, verbose_name='Date de paiement')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='Supprimé logiquement')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='Date de suppression')),
                ('bailleur', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='recaps_mensuels', to='proprietes.bailleur', verbose_name='Bailleur')),
                ('charges_deductibles', models.ManyToManyField(related_name='recaps_mensuels', to='paiements.chargedeductible', verbose_name='Charges déductibles')),
                ('cree_par', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recaps_mensuels_crees', to=settings.AUTH_USER_MODEL, verbose_name='Créé par')),
                ('deleted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recaps_mensuels_supprimes', to=settings.AUTH_USER_MODEL, verbose_name='Supprimé par')),
                ('paiements_concernes', models.ManyToManyField(related_name='recaps_mensuels', to='paiements.paiement', verbose_name='Paiements concernés')),
                ('valide_par', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recaps_mensuels_valides', to=settings.AUTH_USER_MODEL, verbose_name='Validé par')),
                ('retraits_associes', models.ManyToManyField(related_name='recaps_mensuels', to='paiements.retraitbailleur', verbose_name='Retraits associés')),
            ],
            options={
                'verbose_name': 'Récapitulatif mensuel',
                'verbose_name_plural': 'Récapitulatifs mensuels',
                'ordering': ['-mois_recap'],
                'indexes': [models.Index(fields=['bailleur', 'mois_recap'], name='paiements_r_bailleu_169d13_idx'), models.Index(fields=['statut'], name='paiements_r_statut_e968e9_idx'), models.Index(fields=['date_creation'], name='paiements_r_date_cr_28403c_idx')],
                'unique_together': {('bailleur', 'mois_recap')},
            },
        ),
        migrations.AddIndex(
            model_name='retraitbailleur',
            index=models.Index(fields=['bailleur', 'mois_retrait'], name='paiements_r_bailleu_beffb7_idx'),
        ),
        migrations.AddIndex(
            model_name='retraitbailleur',
            index=models.Index(fields=['statut'], name='paiements_r_statut_c047d5_idx'),
        ),
        migrations.AddIndex(
            model_name='retraitbailleur',
            index=models.Index(fields=['date_demande'], name='paiements_r_date_de_729041_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='retraitbailleur',
            unique_together={('bailleur', 'mois_retrait')},
        ),
    ]
