# Generated by Django 5.2.4 on 2025-08-19 18:42

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contrats', '0003_contrat_avance_loyer_contrat_avance_loyer_payee_and_more'),
        ('paiements', '0006_paiement_est_paiement_partiel_paiement_mois_paye_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='paiement',
            options={'ordering': ['-date_paiement', '-date_creation'], 'verbose_name': 'Paiement', 'verbose_name_plural': 'Paiements'},
        ),
        migrations.AddField(
            model_name='paiement',
            name='reference_paiement',
            field=models.CharField(blank=True, help_text='Référence unique pour identifier le paiement', max_length=30, null=True, unique=True, verbose_name='Référence Paiement'),
        ),
        migrations.AddIndex(
            model_name='paiement',
            index=models.Index(fields=['contrat', 'date_paiement'], name='paiements_p_contrat_bd9022_idx'),
        ),
        migrations.AddIndex(
            model_name='paiement',
            index=models.Index(fields=['statut', 'date_paiement'], name='paiements_p_statut_551504_idx'),
        ),
        migrations.AddIndex(
            model_name='paiement',
            index=models.Index(fields=['type_paiement', 'date_paiement'], name='paiements_p_type_pa_17a7c1_idx'),
        ),
    ]
