# Generated by Django 5.2.4 on 2025-08-20 13:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paiements', '0008_paiement_numero_paiement'),
        ('proprietes', '0010_document'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TableauBordFinancier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100, verbose_name='Nom du tableau')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('afficher_revenus', models.BooleanField(default=True, verbose_name='Afficher les revenus')),
                ('afficher_charges', models.BooleanField(default=True, verbose_name='Afficher les charges')),
                ('afficher_benefices', models.BooleanField(default=True, verbose_name='Afficher les bénéfices')),
                ('afficher_taux_occupation', models.BooleanField(default=True, verbose_name="Afficher le taux d'occupation")),
                ('periode', models.CharField(choices=[('mensuel', 'Mensuel'), ('trimestriel', 'Trimestriel'), ('annuel', 'Annuel'), ('personnalise', 'Personnalisé')], default='mensuel', max_length=20, verbose_name="Période d'analyse")),
                ('date_debut_personnalisee', models.DateField(blank=True, null=True, verbose_name='Date de début (période personnalisée)')),
                ('date_fin_personnalisee', models.DateField(blank=True, null=True, verbose_name='Date de fin (période personnalisée)')),
                ('date_creation', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
                ('date_modification', models.DateTimeField(auto_now=True, verbose_name='Date de modification')),
                ('actif', models.BooleanField(default=True, verbose_name='Tableau actif')),
                ('bailleurs', models.ManyToManyField(blank=True, help_text='Bailleurs à inclure dans ce tableau de bord', to='proprietes.bailleur', verbose_name='Bailleurs inclus')),
                ('cree_par', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Créé par')),
                ('proprietes', models.ManyToManyField(help_text='Propriétés à inclure dans ce tableau de bord', to='proprietes.propriete', verbose_name='Propriétés incluses')),
            ],
            options={
                'verbose_name': 'Tableau de bord financier',
                'verbose_name_plural': 'Tableaux de bord financiers',
                'ordering': ['-date_creation'],
            },
        ),
    ]
