# Generated by Django 5.2.4 on 2025-08-21 08:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paiements', '0010_paiementcautionavance'),
    ]

    operations = [
        # Migration pour l'unification du système de paiements
        # Suppression progressive des modèles obsolètes
        
        # D'abord, supprimer les modèles les plus simples
        migrations.DeleteModel(
            name='CompteBancaire',
        ),
        
        migrations.DeleteModel(
            name='Recu',
        ),
        
        migrations.DeleteModel(
            name='RecuRetrait',
        ),
        
        migrations.DeleteModel(
            name='Retrait',
        ),
        
        migrations.DeleteModel(
            name='PaiementCautionAvance',
        ),
        
        migrations.DeleteModel(
            name='RetraitChargeDeductible',
        ),
        
        migrations.DeleteModel(
            name='RetraitBailleur',
        ),
        
        migrations.DeleteModel(
            name='RecapMensuel',
        ),
        
        migrations.DeleteModel(
            name='TableauBordFinancier',
        ),
        
        # Ajouter les nouveaux types de paiement au modèle Paiement
        migrations.AlterField(
            model_name='paiement',
            name='type_paiement',
            field=models.CharField(
                max_length=20,
                choices=[
                    ('loyer', 'Loyer'),
                    ('charges', 'Charges'),
                    ('caution', 'Caution'),
                    ('avance_loyer', 'Avance de loyer'),
                    ('depot_garantie', 'Dépôt de garantie'),
                    ('regularisation', 'Régularisation'),
                    ('paiement_partiel', 'Paiement partiel'),
                    ('autre', 'Autre'),
                ],
                default='loyer',
                verbose_name='Type de paiement'
            ),
        ),
    ]