# Generated by Django 5.2.4 on 2025-08-21 08:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paiements', '0011_auto_20250821_0805'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='chargedeductible',
            name='paiements_c_statut_836dc4_idx',
        ),
        migrations.RemoveIndex(
            model_name='chargedeductible',
            name='paiements_c_date_ch_5a4d41_idx',
        ),
        migrations.RemoveIndex(
            model_name='chargedeductible',
            name='paiements_c_contrat_83f874_idx',
        ),
        migrations.RemoveIndex(
            model_name='paiement',
            name='paiements_p_contrat_bd9022_idx',
        ),
        migrations.RemoveIndex(
            model_name='paiement',
            name='paiements_p_statut_551504_idx',
        ),
        migrations.RemoveIndex(
            model_name='paiement',
            name='paiements_p_type_pa_17a7c1_idx',
        ),
        migrations.RemoveField(
            model_name='chargedeductible',
            name='notes',
        ),
        migrations.RemoveField(
            model_name='chargedeductible',
            name='paiement_deduction',
        ),
        migrations.RemoveField(
            model_name='chargedeductible',
            name='validee_par',
        ),
        migrations.AddField(
            model_name='chargedeductible',
            name='date_modification',
            field=models.DateTimeField(auto_now=True, verbose_name='Date de modification'),
        ),
        migrations.AddField(
            model_name='chargedeductible',
            name='valide_par',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='charges_validees', to=settings.AUTH_USER_MODEL, verbose_name='Validée par'),
        ),
        migrations.AlterField(
            model_name='chargedeductible',
            name='cree_par',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='charges_crees', to=settings.AUTH_USER_MODEL, verbose_name='Créé par'),
        ),
        migrations.AlterField(
            model_name='chargedeductible',
            name='deleted_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='charges_deleted', to=settings.AUTH_USER_MODEL, verbose_name='Supprimé par'),
        ),
        migrations.AlterField(
            model_name='chargedeductible',
            name='fournisseur',
            field=models.CharField(blank=True, max_length=150, verbose_name='Fournisseur'),
        ),
    ]
