# Generated by Django 4.2.24 on 2025-10-17 20:12

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contrats', '0031_alter_contrat_loyer_mensuel'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('proprietes', '0030_fix_telephone_length'),
        ('paiements', '0012_add_paiement_field_to_avance'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChargeBailleur',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=200, verbose_name='Description de la charge')),
                ('montant', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(0.01)], verbose_name='Montant de la charge')),
                ('date_charge', models.DateField(verbose_name='Date de la charge')),
                ('mois_charge', models.DateField(help_text="Mois pour lequel cette charge s'applique", verbose_name='Mois de la charge')),
                ('statut', models.CharField(choices=[('en_attente', 'En attente'), ('valide', 'Validé'), ('utilise', 'Utilisé'), ('annule', 'Annulé')], default='en_attente', max_length=20, verbose_name='Statut')),
                ('notes', models.TextField(blank=True, verbose_name='Notes')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Date de modification')),
            ],
            options={
                'verbose_name': 'Charge Bailleur',
                'verbose_name_plural': 'Charges Bailleur',
                'ordering': ['-date_charge', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='RetraitQuittance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_quittance', models.CharField(max_length=50, unique=True, verbose_name='Numéro de quittance')),
                ('date_emission', models.DateField(auto_now_add=True, verbose_name="Date d'émission")),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
            ],
            options={
                'verbose_name': 'Quittance de retrait',
                'verbose_name_plural': 'Quittances de retrait',
                'ordering': ['-date_emission'],
            },
        ),
        migrations.RemoveField(
            model_name='alertepaiementpartiel',
            name='cree_par',
        ),
        migrations.RemoveField(
            model_name='alertepaiementpartiel',
            name='echelon',
        ),
        migrations.RemoveField(
            model_name='alertepaiementpartiel',
            name='plan',
        ),
        migrations.RemoveField(
            model_name='alertepaiementpartiel',
            name='traite_par',
        ),
        migrations.AlterUniqueTogether(
            name='detailretraitunite',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='detailretraitunite',
            name='contrat',
        ),
        migrations.RemoveField(
            model_name='detailretraitunite',
            name='retrait',
        ),
        migrations.RemoveField(
            model_name='detailretraitunite',
            name='unite_locative',
        ),
        migrations.AlterUniqueTogether(
            name='echelonpaiement',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='echelonpaiement',
            name='cree_par',
        ),
        migrations.RemoveField(
            model_name='echelonpaiement',
            name='paiement',
        ),
        migrations.RemoveField(
            model_name='echelonpaiement',
            name='plan',
        ),
        migrations.RemoveField(
            model_name='paiementpartiel',
            name='cree_par',
        ),
        migrations.RemoveField(
            model_name='paiementpartiel',
            name='deleted_by',
        ),
        migrations.RemoveField(
            model_name='paiementpartiel',
            name='echelon',
        ),
        migrations.RemoveField(
            model_name='paiementpartiel',
            name='paiement_principal',
        ),
        migrations.RemoveField(
            model_name='paiementpartiel',
            name='plan',
        ),
        migrations.RemoveField(
            model_name='paiementpartiel',
            name='valide_par',
        ),
        migrations.RemoveField(
            model_name='planpaiementpartiel',
            name='contrat',
        ),
        migrations.RemoveField(
            model_name='planpaiementpartiel',
            name='cree_par',
        ),
        migrations.RemoveField(
            model_name='planpaiementpartiel',
            name='deleted_by',
        ),
        migrations.RemoveField(
            model_name='planpaiementpartiel',
            name='modifie_par',
        ),
        migrations.AlterUniqueTogether(
            name='recapitulatifmensuelbailleur',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='recapitulatifmensuelbailleur',
            name='bailleur',
        ),
        migrations.RemoveField(
            model_name='recapitulatifmensuelbailleur',
            name='gestionnaire',
        ),
        migrations.RemoveField(
            model_name='recurecapitulatif',
            name='cree_par',
        ),
        migrations.RemoveField(
            model_name='recurecapitulatif',
            name='imprime_par',
        ),
        migrations.RemoveField(
            model_name='recurecapitulatif',
            name='recapitulatif',
        ),
        migrations.RemoveField(
            model_name='recuretrait',
            name='imprime_par',
        ),
        migrations.RemoveField(
            model_name='recuretrait',
            name='retrait_bailleur',
        ),
        migrations.AlterUniqueTogether(
            name='retraitchargedeductible',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='retraitchargedeductible',
            name='charge_deductible',
        ),
        migrations.RemoveField(
            model_name='retraitchargedeductible',
            name='retrait_bailleur',
        ),
        migrations.RemoveField(
            model_name='tableaubordfinancier',
            name='bailleurs',
        ),
        migrations.RemoveField(
            model_name='tableaubordfinancier',
            name='cree_par',
        ),
        migrations.RemoveField(
            model_name='tableaubordfinancier',
            name='proprietes',
        ),
        migrations.AlterModelOptions(
            name='paiement',
            options={'ordering': ['-date_paiement'], 'verbose_name': 'Paiement', 'verbose_name_plural': 'Paiements'},
        ),
        migrations.AlterModelOptions(
            name='retraitbailleur',
            options={'ordering': ['-mois_retrait', '-date_demande'], 'verbose_name': 'Retrait bailleur', 'verbose_name_plural': 'Retraits bailleur'},
        ),
        migrations.RemoveConstraint(
            model_name='consommationavance',
            name='unique_consommation_per_avance_month',
        ),
        migrations.RemoveConstraint(
            model_name='historiquepaiement',
            name='unique_historique_per_contrat_month',
        ),
        migrations.RemoveIndex(
            model_name='recapmensuel',
            name='paiements_r_garanti_b5b187_idx',
        ),
        migrations.AlterUniqueTogether(
            name='retraitbailleur',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='chargedeductible',
            name='cree_par',
        ),
        migrations.RemoveField(
            model_name='chargedeductible',
            name='date_creation',
        ),
        migrations.RemoveField(
            model_name='chargedeductible',
            name='date_deduction',
        ),
        migrations.RemoveField(
            model_name='chargedeductible',
            name='date_modification',
        ),
        migrations.RemoveField(
            model_name='chargedeductible',
            name='date_validation',
        ),
        migrations.RemoveField(
            model_name='chargedeductible',
            name='deleted_at',
        ),
        migrations.RemoveField(
            model_name='chargedeductible',
            name='deleted_by',
        ),
        migrations.RemoveField(
            model_name='chargedeductible',
            name='facture_numero',
        ),
        migrations.RemoveField(
            model_name='chargedeductible',
            name='fournisseur',
        ),
        migrations.RemoveField(
            model_name='chargedeductible',
            name='justificatif_url',
        ),
        migrations.RemoveField(
            model_name='chargedeductible',
            name='libelle',
        ),
        migrations.RemoveField(
            model_name='chargedeductible',
            name='statut',
        ),
        migrations.RemoveField(
            model_name='chargedeductible',
            name='type_charge',
        ),
        migrations.RemoveField(
            model_name='chargedeductible',
            name='valide_par',
        ),
        migrations.RemoveField(
            model_name='recapmensuel',
            name='retraits_associes',
        ),
        migrations.AddField(
            model_name='chargedeductible',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='chargedeductible',
            name='est_deductible_loyer',
            field=models.BooleanField(default=True, verbose_name='Déductible du loyer'),
        ),
        migrations.AddField(
            model_name='chargedeductible',
            name='est_valide',
            field=models.BooleanField(default=False, verbose_name='Validé'),
        ),
        migrations.AddField(
            model_name='chargedeductible',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='retraitbailleur',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='Date de création'),
        ),
        migrations.AddField(
            model_name='retraitbailleur',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Date de modification'),
        ),
        migrations.AlterField(
            model_name='chargedeductible',
            name='contrat',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='charges_deductibles', to='contrats.contrat', verbose_name='Contrat'),
        ),
        migrations.AlterField(
            model_name='chargedeductible',
            name='description',
            field=models.CharField(max_length=200, verbose_name='Description de la charge'),
        ),
        migrations.AlterField(
            model_name='chargedeductible',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='paiement',
            name='contrat',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='paiements', to='contrats.contrat', verbose_name='Contrat'),
        ),
        migrations.AlterField(
            model_name='paiement',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='paiement',
            name='deleted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='paiement',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='paiement',
            name='mode_paiement',
            field=models.CharField(choices=[('especes', 'Espèces'), ('cheque', 'Chèque'), ('virement', 'Virement'), ('mobile_money', 'Mobile Money')], max_length=20, verbose_name='Mode de paiement'),
        ),
        migrations.AlterField(
            model_name='paiement',
            name='mois_paye',
            field=models.CharField(blank=True, help_text='Mois pour lequel le paiement est effectué', max_length=50, verbose_name='Mois payé'),
        ),
        migrations.AlterField(
            model_name='paiement',
            name='montant',
            field=models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0.01)], verbose_name='Montant payé'),
        ),
        migrations.AlterField(
            model_name='paiement',
            name='montant_net_paye',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Montant net payé'),
        ),
        migrations.AlterField(
            model_name='paiement',
            name='notes',
            field=models.TextField(blank=True, help_text='Notes ou commentaires sur le paiement', verbose_name='Notes'),
        ),
        migrations.AlterField(
            model_name='paiement',
            name='reference_paiement',
            field=models.CharField(blank=True, help_text='Référence unique du paiement', max_length=50, unique=True, verbose_name='Référence de paiement'),
        ),
        migrations.AlterField(
            model_name='paiement',
            name='reference_virement',
            field=models.CharField(blank=True, max_length=100, verbose_name='Référence du virement'),
        ),
        migrations.AlterField(
            model_name='paiement',
            name='statut',
            field=models.CharField(choices=[('en_attente', 'En attente'), ('valide', 'Validé'), ('refuse', 'Refusé'), ('annule', 'Annulé')], default='en_attente', max_length=20, verbose_name='Statut'),
        ),
        migrations.AlterField(
            model_name='paiement',
            name='type_paiement',
            field=models.CharField(choices=[('loyer', 'Loyer'), ('caution', 'Caution'), ('avance', 'Avance'), ('avance_loyer', 'Avance de loyer'), ('depot_garantie', 'Dépôt de garantie'), ('charges', 'Charges'), ('regularisation', 'Régularisation'), ('paiement_partiel', 'Paiement partiel'), ('autre', 'Autre')], default='loyer', max_length=20, verbose_name='Type de paiement'),
        ),
        migrations.AlterField(
            model_name='paiement',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='quittancepaiement',
            name='statut',
            field=models.CharField(choices=[('generee', 'Générée'), ('imprimee', 'Imprimée'), ('envoyee', 'Envoyée'), ('archivee', 'Archivée')], default='generee', max_length=20, verbose_name='Statut'),
        ),
        migrations.AlterField(
            model_name='recapmensuel',
            name='garanties_suffisantes',
            field=models.BooleanField(default=True, verbose_name='Garanties financières suffisantes'),
        ),
        migrations.AlterField(
            model_name='retraitbailleur',
            name='bailleur',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='retraits', to='proprietes.bailleur', verbose_name='Bailleur'),
        ),
        migrations.AlterField(
            model_name='retraitbailleur',
            name='date_demande',
            field=models.DateField(auto_now_add=True, verbose_name='Date de demande'),
        ),
        migrations.AlterField(
            model_name='retraitbailleur',
            name='date_paiement',
            field=models.DateField(blank=True, null=True, verbose_name='Date de paiement'),
        ),
        migrations.AlterField(
            model_name='retraitbailleur',
            name='date_validation',
            field=models.DateField(blank=True, null=True, verbose_name='Date de validation'),
        ),
        migrations.AlterField(
            model_name='retraitbailleur',
            name='is_deleted',
            field=models.BooleanField(default=False, verbose_name='Supprimé'),
        ),
        migrations.AlterField(
            model_name='retraitbailleur',
            name='mode_retrait',
            field=models.CharField(choices=[('virement', 'Virement bancaire'), ('cheque', 'Chèque'), ('especes', 'Espèces')], default='virement', max_length=20, verbose_name='Mode de retrait'),
        ),
        migrations.AlterField(
            model_name='retraitbailleur',
            name='montant_charges_deductibles',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Montant des charges déductibles'),
        ),
        migrations.AlterField(
            model_name='retraitbailleur',
            name='montant_loyers_bruts',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Montant des loyers bruts'),
        ),
        migrations.AlterField(
            model_name='retraitbailleur',
            name='montant_net_a_payer',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Montant net à payer'),
        ),
        migrations.AlterUniqueTogether(
            name='consommationavance',
            unique_together={('avance', 'mois_consomme')},
        ),
        migrations.AlterUniqueTogether(
            name='historiquepaiement',
            unique_together={('contrat', 'mois_paiement')},
        ),
        migrations.AddConstraint(
            model_name='retraitbailleur',
            constraint=models.UniqueConstraint(condition=models.Q(('is_deleted', False)), fields=('bailleur', 'mois_retrait'), name='unique_retrait_actif_per_bailleur_month'),
        ),
        migrations.DeleteModel(
            name='AlertePaiementPartiel',
        ),
        migrations.DeleteModel(
            name='DetailRetraitUnite',
        ),
        migrations.DeleteModel(
            name='EchelonPaiement',
        ),
        migrations.DeleteModel(
            name='PaiementPartiel',
        ),
        migrations.DeleteModel(
            name='PlanPaiementPartiel',
        ),
        migrations.DeleteModel(
            name='RecapitulatifMensuelBailleur',
        ),
        migrations.DeleteModel(
            name='RecuRecapitulatif',
        ),
        migrations.DeleteModel(
            name='RecuRetrait',
        ),
        migrations.DeleteModel(
            name='TableauBordFinancier',
        ),
        migrations.AddField(
            model_name='retraitquittance',
            name='cree_par',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Créé par'),
        ),
        migrations.AddField(
            model_name='retraitquittance',
            name='retrait',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='quittance', to='paiements.retraitbailleur', verbose_name='Retrait'),
        ),
        migrations.AddField(
            model_name='chargebailleur',
            name='bailleur',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='charges_bailleur', to='proprietes.bailleur', verbose_name='Bailleur'),
        ),
        migrations.AddField(
            model_name='chargebailleur',
            name='cree_par',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='charges_bailleur_crees', to=settings.AUTH_USER_MODEL, verbose_name='Créé par'),
        ),
        migrations.AddField(
            model_name='chargebailleur',
            name='retrait_utilise',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='charges_utilisees', to='paiements.retraitbailleur', verbose_name='Retrait qui a utilisé cette charge'),
        ),
        migrations.RemoveField(
            model_name='retraitbailleur',
            name='charges_deductibles',
        ),
        migrations.RemoveField(
            model_name='retraitbailleur',
            name='date_annulation',
        ),
        migrations.RemoveField(
            model_name='retraitbailleur',
            name='date_creation',
        ),
        migrations.RemoveField(
            model_name='retraitbailleur',
            name='date_modification',
        ),
        migrations.RemoveField(
            model_name='retraitbailleur',
            name='date_versement',
        ),
        migrations.RemoveField(
            model_name='retraitbailleur',
            name='deleted_at',
        ),
        migrations.RemoveField(
            model_name='retraitbailleur',
            name='deleted_by',
        ),
        migrations.RemoveField(
            model_name='retraitbailleur',
            name='hash_securite',
        ),
        migrations.RemoveField(
            model_name='retraitbailleur',
            name='motif_annulation',
        ),
        migrations.RemoveField(
            model_name='retraitbailleur',
            name='motif_modification',
        ),
        migrations.RemoveField(
            model_name='retraitbailleur',
            name='niveau_autorisation_modification',
        ),
        migrations.RemoveField(
            model_name='retraitbailleur',
            name='numero_cheque',
        ),
        migrations.RemoveField(
            model_name='retraitbailleur',
            name='paiements_concernes',
        ),
        migrations.RemoveField(
            model_name='retraitbailleur',
            name='paye_par',
        ),
        migrations.RemoveField(
            model_name='retraitbailleur',
            name='peut_etre_modifie',
        ),
        migrations.RemoveField(
            model_name='retraitbailleur',
            name='recap_lie',
        ),
        migrations.RemoveField(
            model_name='retraitbailleur',
            name='reference_virement',
        ),
        migrations.DeleteModel(
            name='RetraitChargeDeductible',
        ),
    ]
