# Generated by Django 5.2.4 on 2025-08-21 17:56

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paiements', '0013_quittancepaiement'),
        ('proprietes', '0013_alter_bailleur_adresse_alter_bailleur_code_postal_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RetraitBailleur',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mois_retrait', models.DateField(help_text='Mois pour lequel le retrait est effectué', verbose_name='Mois de retrait')),
                ('montant_loyers_bruts', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(0.01)], verbose_name='Montant total des loyers bruts')),
                ('montant_charges_deductibles', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Montant total des charges déductibles')),
                ('montant_net_a_payer', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Montant net à payer (après déduction des charges)')),
                ('type_retrait', models.CharField(choices=[('mensuel', 'Retrait mensuel'), ('trimestriel', 'Retrait trimestriel'), ('annuel', 'Retrait annuel'), ('exceptionnel', 'Retrait exceptionnel')], default='mensuel', max_length=20, verbose_name='Type de retrait')),
                ('statut', models.CharField(choices=[('en_attente', 'En attente'), ('valide', 'Validé'), ('paye', 'Payé'), ('annule', 'Annulé')], default='en_attente', max_length=20, verbose_name='Statut')),
                ('mode_retrait', models.CharField(choices=[('virement', 'Virement bancaire'), ('cheque', 'Chèque'), ('especes', 'Espèces')], max_length=20, verbose_name='Mode de retrait')),
                ('date_demande', models.DateField(verbose_name='Date de demande')),
                ('date_versement', models.DateField(blank=True, null=True, verbose_name='Date de versement')),
                ('numero_cheque', models.CharField(blank=True, max_length=50, verbose_name='Numéro de chèque')),
                ('reference_virement', models.CharField(blank=True, max_length=100, verbose_name='Référence virement')),
                ('date_creation', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
                ('date_modification', models.DateTimeField(auto_now=True, verbose_name='Date de modification')),
                ('notes', models.TextField(blank=True, verbose_name='Notes')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='Supprimé logiquement')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='Date de suppression')),
                ('bailleur', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='retraits_bailleur', to='proprietes.bailleur', verbose_name='Bailleur')),
                ('cree_par', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='retraits_bailleur_crees', to=settings.AUTH_USER_MODEL, verbose_name='Créé par')),
                ('deleted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='retraits_bailleur_supprimes', to=settings.AUTH_USER_MODEL, verbose_name='Supprimé par')),
                ('paiements_concernes', models.ManyToManyField(related_name='retraits_bailleur', to='paiements.paiement', verbose_name='Paiements concernés')),
                ('valide_par', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='retraits_bailleur_valides', to=settings.AUTH_USER_MODEL, verbose_name='Validé par')),
            ],
            options={
                'verbose_name': 'Retrait bailleur',
                'verbose_name_plural': 'Retraits bailleur',
                'ordering': ['-mois_retrait'],
            },
        ),
        migrations.CreateModel(
            name='RecuRetrait',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_recu', models.CharField(max_length=50, unique=True, verbose_name='Numéro de reçu')),
                ('date_emission', models.DateTimeField(auto_now_add=True, verbose_name="Date d'émission")),
                ('imprime', models.BooleanField(default=False, verbose_name='Imprimé')),
                ('date_impression', models.DateTimeField(blank=True, null=True, verbose_name="Date d'impression")),
                ('genere_automatiquement', models.BooleanField(default=True, verbose_name='Généré automatiquement')),
                ('format_impression', models.CharField(choices=[('a5', 'A5'), ('a4', 'A4')], default='a5', max_length=20, verbose_name="Format d'impression")),
                ('notes_internes', models.TextField(blank=True, verbose_name='Notes internes')),
                ('imprime_par', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recus_retrait_imprimes', to=settings.AUTH_USER_MODEL, verbose_name='Imprimé par')),
                ('retrait_bailleur', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='recu_retrait', to='paiements.retraitbailleur', verbose_name='Retrait bailleur')),
            ],
            options={
                'verbose_name': 'Reçu de retrait',
                'verbose_name_plural': 'Reçus de retrait',
                'ordering': ['-date_emission'],
            },
        ),
        migrations.CreateModel(
            name='RetraitChargeDeductible',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_ajout', models.DateTimeField(auto_now_add=True, verbose_name="Date d'ajout")),
                ('charge_deductible', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='paiements.chargedeductible', verbose_name='Charge déductible')),
                ('retrait_bailleur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='paiements.retraitbailleur', verbose_name='Retrait bailleur')),
            ],
            options={
                'verbose_name': 'Charge déductible du retrait',
                'verbose_name_plural': 'Charges déductibles du retrait',
                'unique_together': {('retrait_bailleur', 'charge_deductible')},
            },
        ),
        migrations.AddField(
            model_name='retraitbailleur',
            name='charges_deductibles',
            field=models.ManyToManyField(related_name='retraits_bailleur', through='paiements.RetraitChargeDeductible', to='paiements.chargedeductible', verbose_name='Charges déductibles'),
        ),
        migrations.AddIndex(
            model_name='retraitbailleur',
            index=models.Index(fields=['bailleur', 'mois_retrait'], name='paiements_r_bailleu_beffb7_idx'),
        ),
        migrations.AddIndex(
            model_name='retraitbailleur',
            index=models.Index(fields=['statut'], name='paiements_r_statut_c047d5_idx'),
        ),
        migrations.AddIndex(
            model_name='retraitbailleur',
            index=models.Index(fields=['date_demande'], name='paiements_r_date_de_729041_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='retraitbailleur',
            unique_together={('bailleur', 'mois_retrait')},
        ),
    ]
