# Generated by Django 5.2.4 on 2025-08-21 23:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paiements', '0014_retraitbailleur_recuretrait_retraitchargedeductible_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='retraitbailleur',
            name='date_annulation',
            field=models.DateTimeField(blank=True, null=True, verbose_name="Date d'annulation"),
        ),
        migrations.AddField(
            model_name='retraitbailleur',
            name='date_paiement',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Date de paiement'),
        ),
        migrations.AddField(
            model_name='retraitbailleur',
            name='date_validation',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Date de validation'),
        ),
        migrations.AddField(
            model_name='retraitbailleur',
            name='hash_securite',
            field=models.CharField(blank=True, max_length=64, null=True, verbose_name='Hash de sécurité'),
        ),
        migrations.AddField(
            model_name='retraitbailleur',
            name='motif_annulation',
            field=models.TextField(blank=True, null=True, verbose_name="Motif de l'annulation"),
        ),
        migrations.AddField(
            model_name='retraitbailleur',
            name='motif_modification',
            field=models.TextField(blank=True, null=True, verbose_name='Motif de la modification'),
        ),
        migrations.AddField(
            model_name='retraitbailleur',
            name='niveau_autorisation_modification',
            field=models.CharField(choices=[('standard', 'Standard'), ('superviseur', 'Superviseur'), ('manager', 'Manager'), ('admin', 'Administrateur'), ('system', 'Système uniquement')], default='standard', max_length=20, verbose_name="Niveau d'autorisation requis pour modification"),
        ),
        migrations.AddField(
            model_name='retraitbailleur',
            name='paye_par',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='retraits_payes', to=settings.AUTH_USER_MODEL, verbose_name='Payé par'),
        ),
        migrations.AddField(
            model_name='retraitbailleur',
            name='peut_etre_modifie',
            field=models.BooleanField(default=True, help_text='Désactivé une fois validé', verbose_name='Peut être modifié'),
        ),
        migrations.AlterField(
            model_name='retraitbailleur',
            name='cree_par',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='retraits_crees', to=settings.AUTH_USER_MODEL, verbose_name='Créé par'),
        ),
        migrations.AlterField(
            model_name='retraitbailleur',
            name='valide_par',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='retraits_valides', to=settings.AUTH_USER_MODEL, verbose_name='Validé par'),
        ),
    ]
