# Generated by Django 5.2.5 on 2025-08-25 12:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paiements', '0017_recapmensuel'),
        ('proprietes', '0015_add_garant_piece_identite_only'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RecapitulatifMensuelBailleur',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mois_recapitulatif', models.DateField(help_text='Mois de référence pour le récapitulatif', verbose_name='Mois du récapitulatif')),
                ('type_recapitulatif', models.CharField(choices=[('mensuel', 'Mensuel'), ('trimestriel', 'Trimestriel'), ('annuel', 'Annuel'), ('exceptionnel', 'Exceptionnel')], default='mensuel', max_length=20, verbose_name='Type de récapitulatif')),
                ('statut', models.CharField(choices=[('en_preparation', 'En préparation'), ('valide', 'Validé'), ('envoye', 'Envoyé au bailleur'), ('paye', 'Payé'), ('annule', 'Annulé')], default='en_preparation', max_length=20, verbose_name='Statut')),
                ('date_creation', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
                ('date_validation', models.DateTimeField(blank=True, null=True, verbose_name='Date de validation')),
                ('date_envoi', models.DateTimeField(blank=True, null=True, verbose_name="Date d'envoi au bailleur")),
                ('date_paiement', models.DateTimeField(blank=True, null=True, verbose_name='Date de paiement')),
                ('notes', models.TextField(blank=True, verbose_name='Notes et observations')),
                ('hash_securite', models.CharField(blank=True, max_length=64, verbose_name='Hash de sécurité')),
                ('version', models.CharField(default='1.0', max_length=10, verbose_name='Version du récapitulatif')),
                ('bailleur', models.ForeignKey(help_text='Bailleur concerné par ce récapitulatif', on_delete=django.db.models.deletion.CASCADE, related_name='recapitulatifs_mensuels_bailleur', to='proprietes.bailleur', verbose_name='Bailleur')),
                ('gestionnaire', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recapitulatifs_crees', to=settings.AUTH_USER_MODEL, verbose_name='Gestionnaire responsable')),
            ],
            options={
                'verbose_name': 'Récapitulatif mensuel',
                'verbose_name_plural': 'Récapitulatifs mensuels',
                'ordering': ['-mois_recapitulatif', '-date_creation'],
                'indexes': [models.Index(fields=['mois_recapitulatif', 'statut'], name='paiements_r_mois_re_1a99f9_idx'), models.Index(fields=['gestionnaire', 'date_creation'], name='paiements_r_gestion_751a82_idx')],
                'unique_together': {('bailleur', 'mois_recapitulatif', 'type_recapitulatif')},
            },
        ),
        migrations.CreateModel(
            name='Recu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_recu', models.CharField(help_text='Numéro unique du reçu', max_length=50, unique=True, verbose_name='Numéro de reçu')),
                ('template_utilise', models.CharField(choices=[('standard', 'Standard'), ('simplified', 'Simplifié'), ('detailed', 'Détaillé'), ('professionnel', 'Professionnel'), ('luxe', 'Luxe'), ('entreprise', 'Entreprise')], default='standard', max_length=20, verbose_name='Template utilisé')),
                ('format_impression', models.CharField(choices=[('A4', 'A4'), ('A5', 'A5'), ('lettre', 'Lettre'), ('personnalise', 'Personnalisé')], default='A4', max_length=20, verbose_name="Format d'impression")),
                ('valide', models.BooleanField(default=True, verbose_name='Reçu validé')),
                ('imprime', models.BooleanField(default=False, verbose_name='Reçu imprimé')),
                ('date_impression', models.DateTimeField(blank=True, null=True, verbose_name="Date d'impression")),
                ('nombre_impressions', models.PositiveIntegerField(default=0, verbose_name="Nombre d'impressions")),
                ('envoye_email', models.BooleanField(default=False, verbose_name='Reçu envoyé par email')),
                ('date_envoi_email', models.DateTimeField(blank=True, null=True, verbose_name="Date d'envoi par email")),
                ('email_destinataire', models.EmailField(blank=True, max_length=254, null=True, verbose_name='Email du destinataire')),
                ('nombre_emails', models.PositiveIntegerField(default=0, verbose_name="Nombre d'emails envoyés")),
                ('date_emission', models.DateTimeField(auto_now_add=True, verbose_name="Date d'émission")),
                ('date_validation', models.DateTimeField(blank=True, null=True, verbose_name='Date de validation')),
                ('genere_automatiquement', models.BooleanField(default=True, verbose_name='Généré automatiquement')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='Supprimé')),
                ('imprime_par', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recus_imprimes', to=settings.AUTH_USER_MODEL, verbose_name='Imprimé par')),
                ('paiement', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='recu', to='paiements.paiement', verbose_name='Paiement')),
                ('valide_par', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recus_valides', to=settings.AUTH_USER_MODEL, verbose_name='Validé par')),
            ],
            options={
                'verbose_name': 'Reçu',
                'verbose_name_plural': 'Reçus',
                'ordering': ['-date_emission'],
                'indexes': [models.Index(fields=['numero_recu'], name='paiements_r_numero__2a4ff1_idx'), models.Index(fields=['date_emission'], name='paiements_r_date_em_d558d9_idx'), models.Index(fields=['valide'], name='paiements_r_valide_e5db39_idx'), models.Index(fields=['imprime'], name='paiements_r_imprime_747ade_idx')],
            },
        ),
    ]
