# Generated by Django 5.2.5 on 2025-08-28 11:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paiements', '0018_recapitulatifmensuelbailleur_recu'),
        ('proprietes', '0016_chargesbailleur_montant_deja_deduit_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='recapmensuel',
            options={'ordering': ['-mois_recap', 'bailleur__nom'], 'verbose_name': 'Récapitulatif mensuel', 'verbose_name_plural': 'Récapitulatifs mensuels'},
        ),
        migrations.RemoveIndex(
            model_name='recapmensuel',
            name='paiements_r_bailleu_169d13_idx',
        ),
        migrations.RemoveIndex(
            model_name='recapmensuel',
            name='paiements_r_statut_e968e9_idx',
        ),
        migrations.RemoveIndex(
            model_name='recapmensuel',
            name='paiements_r_date_cr_28403c_idx',
        ),
        migrations.RemoveField(
            model_name='recapmensuel',
            name='date_envoi',
        ),
        migrations.RemoveField(
            model_name='recapmensuel',
            name='date_paiement',
        ),
        migrations.RemoveField(
            model_name='recapmensuel',
            name='date_validation',
        ),
        migrations.RemoveField(
            model_name='recapmensuel',
            name='valide_par',
        ),
        migrations.AddField(
            model_name='paiement',
            name='libelle',
            field=models.CharField(blank=True, help_text='Description ou motif du paiement', max_length=200, verbose_name='Libellé du paiement'),
        ),
        migrations.AddField(
            model_name='recapmensuel',
            name='date_modification',
            field=models.DateTimeField(auto_now=True, verbose_name='Date de modification'),
        ),
        migrations.AddField(
            model_name='recapmensuel',
            name='garanties_suffisantes',
            field=models.BooleanField(default=False, verbose_name='Garanties financières suffisantes'),
        ),
        migrations.AddField(
            model_name='recapmensuel',
            name='modifie_par',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recaps_mensuels_modifies', to=settings.AUTH_USER_MODEL, verbose_name='Modifié par'),
        ),
        migrations.AddField(
            model_name='recapmensuel',
            name='total_avances_requises',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Total des avances requises'),
        ),
        migrations.AddField(
            model_name='recapmensuel',
            name='total_avances_versees',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Total des avances versées'),
        ),
        migrations.AddField(
            model_name='recapmensuel',
            name='total_cautions_requises',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Total des cautions requises'),
        ),
        migrations.AddField(
            model_name='recapmensuel',
            name='total_cautions_versees',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Total des cautions versées'),
        ),
        migrations.AlterField(
            model_name='recapmensuel',
            name='charges_deductibles',
            field=models.ManyToManyField(blank=True, related_name='recaps_mensuels', to='paiements.chargedeductible', verbose_name='Charges déductibles'),
        ),
        migrations.AlterField(
            model_name='recapmensuel',
            name='mois_recap',
            field=models.DateField(verbose_name='Mois du récapitulatif'),
        ),
        migrations.AlterField(
            model_name='recapmensuel',
            name='paiements_concernes',
            field=models.ManyToManyField(blank=True, related_name='recaps_mensuels', to='paiements.paiement', verbose_name='Paiements concernés'),
        ),
        migrations.AlterField(
            model_name='recapmensuel',
            name='retraits_associes',
            field=models.ManyToManyField(blank=True, related_name='recaps_mensuels', to='paiements.retraitbailleur', verbose_name='Retraits associés'),
        ),
        migrations.AddIndex(
            model_name='recapmensuel',
            index=models.Index(fields=['mois_recap', 'bailleur'], name='paiements_r_mois_re_156b05_idx'),
        ),
        migrations.AddIndex(
            model_name='recapmensuel',
            index=models.Index(fields=['statut', 'mois_recap'], name='paiements_r_statut_c2dd3d_idx'),
        ),
        migrations.AddIndex(
            model_name='recapmensuel',
            index=models.Index(fields=['garanties_suffisantes', 'mois_recap'], name='paiements_r_garanti_b5b187_idx'),
        ),
    ]
