# Generated by Django 5.2.5 on 2025-09-02 12:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('paiements', '0002_retraitbailleur_recap_lie'),
        ('paiements', '0019_alter_recapmensuel_options_and_more'),
    ]

    operations = [
    ]
