# Generated by Django 5.2.5 on 2025-09-02 14:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('paiements', '0020_merge_20250902_1406'),
    ]

    operations = [
    ]
