# Generated by Django 5.2.5 on 2025-09-02 14:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('paiements', '0021_auto_20250902_1617'),
    ]

    operations = [
    ]
