# Generated by Django 5.2.5 on 2025-09-02 14:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paiements', '0023_auto_20250902_1630'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RecuRecapitulatif',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_recu', models.CharField(help_text='Numéro unique du reçu de récapitulatif', max_length=50, unique=True, verbose_name='Numéro de reçu')),
                ('type_recu', models.CharField(choices=[('recapitulatif', 'Récapitulatif'), ('quittance', 'Quittance'), ('attestation', 'Attestation'), ('releve', 'Relevé'), ('facture', 'Facture')], default='recapitulatif', max_length=20, verbose_name='Type de reçu')),
                ('template_utilise', models.CharField(choices=[('professionnel', 'Professionnel'), ('entreprise', 'Entreprise'), ('luxe', 'Luxe'), ('standard', 'Standard'), ('gestimmob', 'GESTIMMOB')], default='professionnel', max_length=20, verbose_name='Template utilisé')),
                ('format_impression', models.CharField(choices=[('A4_paysage', 'A4 Paysage'), ('A4_portrait', 'A4 Portrait'), ('A3_paysage', 'A3 Paysage'), ('lettre_paysage', 'Lettre Paysage')], default='A4_paysage', max_length=20, verbose_name="Format d'impression")),
                ('statut', models.CharField(choices=[('brouillon', 'Brouillon'), ('valide', 'Validé'), ('imprime', 'Imprimé'), ('envoye', 'Envoyé'), ('archive', 'Archivé')], default='brouillon', max_length=20, verbose_name='Statut du reçu')),
                ('imprime', models.BooleanField(default=False, verbose_name='Reçu imprimé')),
                ('date_impression', models.DateTimeField(blank=True, null=True, verbose_name="Date d'impression")),
                ('nombre_impressions', models.PositiveIntegerField(default=0, verbose_name="Nombre d'impressions")),
                ('envoye', models.BooleanField(default=False, verbose_name='Reçu envoyé')),
                ('date_envoi', models.DateTimeField(blank=True, null=True, verbose_name="Date d'envoi")),
                ('mode_envoi', models.CharField(blank=True, choices=[('email', 'Email'), ('courrier', 'Courrier'), ('remise_main', 'Remise en main propre'), ('fax', 'Fax')], max_length=20, verbose_name="Mode d'envoi")),
                ('date_creation', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
                ('hash_securite', models.CharField(blank=True, max_length=64, verbose_name='Hash de sécurité')),
                ('notes', models.TextField(blank=True, verbose_name='Notes')),
                ('cree_par', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recus_recapitulatifs_crees', to=settings.AUTH_USER_MODEL, verbose_name='Créé par')),
                ('imprime_par', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recus_recapitulatifs_imprimes', to=settings.AUTH_USER_MODEL, verbose_name='Imprimé par')),
                ('recapitulatif', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='recu', to='paiements.recapitulatifmensuelbailleur', verbose_name='Récapitulatif')),
            ],
            options={
                'verbose_name': 'Reçu de récapitulatif',
                'verbose_name_plural': 'Reçus de récapitulatifs',
                'ordering': ['-date_creation'],
            },
        ),
        migrations.DeleteModel(
            name='Recu',
        ),
        migrations.AddIndex(
            model_name='recurecapitulatif',
            index=models.Index(fields=['numero_recu'], name='paiements_r_numero__f8c388_idx'),
        ),
        migrations.AddIndex(
            model_name='recurecapitulatif',
            index=models.Index(fields=['statut', 'date_creation'], name='paiements_r_statut_aa7a09_idx'),
        ),
        migrations.AddIndex(
            model_name='recurecapitulatif',
            index=models.Index(fields=['recapitulatif', 'type_recu'], name='paiements_r_recapit_d743c8_idx'),
        ),
    ]
