# Generated by Django 5.2.5 on 2025-09-03 12:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paiements', '0024_recurecapitulatif_delete_recu_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='paiement',
            name='annule_par',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='paiements_annules', to=settings.AUTH_USER_MODEL, verbose_name='Annulé par'),
        ),
        migrations.AddField(
            model_name='paiement',
            name='date_annulation',
            field=models.DateTimeField(blank=True, null=True, verbose_name="Date d'annulation"),
        ),
        migrations.AddField(
            model_name='paiement',
            name='date_refus',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Date de refus'),
        ),
        migrations.AddField(
            model_name='paiement',
            name='date_validation',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Date de validation'),
        ),
        migrations.AddField(
            model_name='paiement',
            name='raison_annulation',
            field=models.TextField(blank=True, verbose_name="Raison de l'annulation"),
        ),
        migrations.AddField(
            model_name='paiement',
            name='raison_refus',
            field=models.TextField(blank=True, verbose_name='Raison du refus'),
        ),
        migrations.AddField(
            model_name='paiement',
            name='refuse_par',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='paiements_refuses', to=settings.AUTH_USER_MODEL, verbose_name='Refusé par'),
        ),
    ]
