# Generated by Django 4.2.24 on 2025-09-17 13:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('utilisateurs', '0008_fix_test_users'),
        ('paiements', '0027_add_partial_payment_models'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='echelonpaiement',
            name='unique_plan_echelon',
        ),
        migrations.AlterField(
            model_name='paiement',
            name='statut',
            field=models.CharField(choices=[('en_attente', 'En attente'), ('partiellement_payé', 'Partiellement payé'), ('valide', 'Validé'), ('refuse', 'Refusé'), ('annule', 'Annulé')], default='en_attente', max_length=20, verbose_name='Statut'),
        ),
        migrations.AlterField(
            model_name='recapmensuel',
            name='cree_par',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recaps_mensuels_crees', to='utilisateurs.utilisateur', verbose_name='Créé par'),
        ),
        migrations.AlterField(
            model_name='recapmensuel',
            name='deleted_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recaps_mensuels_supprimes', to='utilisateurs.utilisateur', verbose_name='Supprimé par'),
        ),
        migrations.AlterField(
            model_name='recapmensuel',
            name='modifie_par',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recaps_mensuels_modifies', to='utilisateurs.utilisateur', verbose_name='Modifié par'),
        ),
        migrations.AlterField(
            model_name='recurecapitulatif',
            name='cree_par',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recus_recapitulatifs_crees', to='utilisateurs.utilisateur', verbose_name='Créé par'),
        ),
        migrations.AlterField(
            model_name='recurecapitulatif',
            name='imprime_par',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recus_recapitulatifs_imprimes', to='utilisateurs.utilisateur', verbose_name='Imprimé par'),
        ),
        migrations.AlterUniqueTogether(
            name='echelonpaiement',
            unique_together={('plan', 'numero_echelon')},
        ),
    ]
