# Generated by Django 4.2.24 on 2025-10-04 10:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('paiements', '0031_add_total_charges_bailleur_column'),
    ]

    operations = [
    ]
