# Generated by Django 4.2.24 on 2025-10-05 23:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('paiements', '0045_auto_20251005_2002'),
        ('paiements', '0046_fix_statut_field'),
    ]

    operations = [
    ]
