# Generated by Django 4.2.24 on 2025-10-07 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paiements', '0049_fix_consommation_avance_paiement_nullable'),
    ]

    operations = [
        migrations.AddField(
            model_name='avanceloyer',
            name='mois_effet_personnalise',
            field=models.DateField(
                blank=True,
                help_text='Laissez vide pour utiliser la logique automatique (15+ du mois)',
                null=True,
                verbose_name='Mois d\'effet personnalisé'
            ),
        ),
    ]
