# Generated by Django 5.2.4 on 2025-08-20 07:06:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        # Cette migration sera appliquée aux modèles des autres apps
        # Nous devons créer des migrations séparées pour chaque app
    ]
