# Generated by Django 4.2.7 on 2025-07-21 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_add_configuration_entreprise'),
    ]

    operations = [
        migrations.CreateModel(
            name='Devise',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=3, unique=True)),
                ('nom', models.CharField(max_length=32)),
                ('symbole', models.CharField(max_length=8)),
                ('taux_par_rapport_a_eur', models.DecimalField(decimal_places=6, default=1, max_digits=12)),
                ('actif', models.BooleanField(default=True)),
            ],
        ),
    ]
