# Generated by Django 5.2.4 on 2025-08-21 01:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_merge_20250820_0724'),
    ]

    operations = [
        migrations.AddField(
            model_name='configurationentreprise',
            name='texte_contrat',
            field=models.TextField(blank=True, help_text='Texte personnalisé pour les obligations et conditions des contrats de bail', null=True, verbose_name='Texte personnalisé pour les contrats'),
        ),
        migrations.AddField(
            model_name='configurationentreprise',
            name='texte_resiliation',
            field=models.TextField(blank=True, help_text='Texte personnalisé pour les conditions de sortie des résiliations', null=True, verbose_name='Texte personnalisé pour les résiliations'),
        ),
    ]
