# Generated by Django 5.2.5 on 2025-08-23 13:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_logaudit'),
    ]

    operations = [
    ]
