# Generated by Django 5.2.5 on 2025-08-23 13:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_auto_20250823_1501'),
    ]

    operations = [
    ]
