# Generated by Django 5.2.5 on 2025-08-25 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_configurationentreprise_logo_upload_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='configurationentreprise',
            name='entete_upload',
            field=models.ImageField(blank=True, help_text='En-tête complet uploadé (PNG, JPG - max 10MB, dimensions recommandées: 800x200 pixels)', null=True, upload_to='entetes_entreprise/', verbose_name='En-tête complet uploadé'),
        ),
    ]
