# Generated by Django 4.2.24 on 2025-09-17 13:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('utilisateurs', '0008_fix_test_users'),
        ('core', '0017_configurationentreprise_entete_upload'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auditlog',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='audit_logs', to='utilisateurs.utilisateur', verbose_name='Utilisateur'),
        ),
    ]
