# Generated by Django 4.2.24 on 2025-10-25 07:19

from django.db import migrations, models
import notifications.validators


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0004_add_user_to_sms_notification'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notificationpreference',
            name='phone_number',
            field=models.CharField(blank=True, help_text='Format: +226 XX XX XX XX', max_length=20, null=True, validators=[notifications.validators.validate_burkina_faso_phone]),
        ),
    ]
